unpackaged/main/default/objects/FSL_Audio_Preferences__c/FSL_Audio_Preferences__c.object-meta.xml
<CustomObject>
    <label>FSL Audio Preferences</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>FSL Audio Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSL Audio Preferences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Audio_Preferences__c/fields/Time_Interval_In_Seconds__c.field-meta.xml
<CustomField>
    <fullName>Time_Interval_In_Seconds__c</fullName>
    <label>Time Interval(In Seconds)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Audio_Preferences__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FSL_Audio_Preferences1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FSL_AudioPreferencesTriggerHandlerTest.cls
@isTest
public class FSL_AudioPreferencesTriggerHandlerTest {
    
    static testmethod void CreateAndUpdateAudioprefRec(){
        
       system.Test.startTest(); 
     
         List<User> userList = [SELECT id, firstName, lastName 
                 FROM USER WHERE alias ='C_Admin'];
        List<User> dispatchUserList = [SELECT id, firstName, lastName 
                 FROM USER WHERE alias ='D_Fleet'];
        System.runAs(userList[0]) {
            list<FSL_Audio_Preferences__c> apref = [select id,User__c from FSL_Audio_Preferences__c LIMIT 1];
             apref[0].User__c = userList[0].id;
             update apref[0];      
            system.debug('------username---------'+apref[0]);
            FSL_Audio_Preferences__c newAup = apref[0];
             newAup.User__c = dispatchUserList[0].id;
             map<id,FSL_Audio_Preferences__c> audnewmap = new map<id,FSL_Audio_Preferences__c>();
             audnewmap.put(newAup.id,newAup);
             
             map<id,FSL_Audio_Preferences__c> audoldmap = new map<id,FSL_Audio_Preferences__c>();
             audoldmap.put(apref[0].id,apref[0]);
             apref[0].Time_Interval_In_Seconds__c = 12;
             update apref[0];
             //FSL_AudioPreferencesTriggerHandler.createAndDeleteUserShareRecords(apref,audnewmap,audoldmap);
        }
         
         
         system.Test.stopTest();   
    } 
    
  
    @testSetup
    public static void dataSetup() {
        FSL_DataFactoryUtility.userdataSetup();
    }   
    

}