unpackaged/main/default/objects/ServiceAppointment/fields/Address_Changed__c.field-meta.xml
<CustomField>
    <fullName>Address_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Address Changed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Status_Change_Notification__e/Status_Change_Notification__e.object-meta.xml
<CustomObject>
    <label>Status Change Notification</label>
    <pluralLabel>Status Change Notifications</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Status_Change_Notification__e/fields/Address_Changed__c.field-meta.xml
<CustomField>
    <fullName>Address_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marked true of address of an SA changes</description>
    <label>Address Changed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Status_Change_Notification__e/fields/Service_Appointment_Id__c.field-meta.xml
<CustomField>
    <fullName>Service_Appointment_Id__c</fullName>
    <label>Service Appointment Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FSL_StatusChangeNotification_Test.cls
@isTest
private class FSL_StatusChangeNotification_Test {
    
    @testSetup
    public static void dataSetup() {
        FSL_DataFactoryUtility.userdataSetup();
    }
    
    static testMethod void testStatusChangeEvent() {
        Test.startTest(); 
        FSL_DataFactory.createWOIntakeCall('FSL_LightCall');
        list<ServiceAppointment> SAs = [select id from ServiceAppointment];
        Status_Change_Notification__e st1 = new Status_Change_Notification__e(Service_Appointment_Id__c = SAs[0].id, Status__c = 'Dispatched', Address_Changed__c=true);
        
        Database.SaveResult result = EventBus.publish(st1);
        Test.stopTest();
        
    }
    
}