unpackaged/main/default/objects/ServiceAppointment/fields/Extend_Work_Time_Counter__c.field-meta.xml
<CustomField>
    <fullName>Extend_Work_Time_Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Extend Work Time Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Schedule_Delta__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Delta__c</fullName>
    <label>Minutes to Add</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Technology_Preference__c.field-meta.xml
<CustomField>
    <fullName>Technology_Preference__c</fullName>
    <formula>TEXT(ServiceTerritory.Dispatch_Method__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Technology Preference</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <formula>Primary_Service_Territory__r.Facility_Number__c</formula>
    <label>Facility Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Primary_Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field auto-populates the Service Territory selected as the Primary Territory</description>
    <label>Primary Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <label>Facility Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Technology_Preference__c/Technology_Preference__c.object-meta.xml
<CustomObject>
    <label>Technology Preference</label>
    <nameField>
        <displayFormat>TECH-{000}</displayFormat>
        <label>Technology Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technology Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/FSL_UpdateSAController_Test.cls
@isTest
public class FSL_UpdateSAController_Test {
    
    static testMethod void SAControllertest(){
        delete [select id from Technology_Preference__c];
        Test.starttest();
        FSL_DataFactory.createWOIntakeCall('FSL_LightCall');        
        Test.stopTest();
		
        Test.setMock(HttpCalloutMock.class, new FSL_WOJeopardy_MockResponseGenerator(false));
        
        list<ServiceAppointment> SAs = [select id, SchedEndTime, status, Schedule_Delta__c, service_resource__c  from ServiceAppointment];        
        system.debug('**SAs: '+SAs);
        system.debug('**serviceresources: '+[select id, IsActive, Primary_Service_Territory__c from ServiceResource]);
        system.debug('**serviceTerritories: '+[select id,facility_number__c  from ServiceTerritory]);
        
        PageReference pageRef = Page.FSL_Extend_WorkType_Duration;
        pageRef.getParameters().put('id',SAs[0].id);
        Test.setCurrentPage(pageRef);   
        FSL_UpdateSAController cntlr = new FSL_UpdateSAController();
        cntlr.saUpdate.Schedule_Delta__c = 10;
        cntlr.saUpdate.Extend_Work_Time_Counter__c=null;
        cntlr.updateServiceAppointment();
    }
    
    @TestSetup
    static void testSetup() {
        FSL_DataFactoryUtility.userdataSetup();
    }    
    
}