unpackaged/main/default/objects/Mobile_Notification_Event__e/Mobile_Notification_Event__e.object-meta.xml
<CustomObject>
    <description>Publish an event that captures the assigned resource insert or update, and creates sharing/subscription based on the condition.</description>
    <label>Mobile Notification Event</label>
    <pluralLabel>Mobile Notification Events</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Mobile_Notification_Event__e/fields/Address_Changed__c.field-meta.xml
<CustomField>
    <fullName>Address_Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the address of the SA changed</description>
    <label>Address Changed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Notification_Event__e/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if status was updated, causing this event</description>
    <label>Status Updated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Mobile_Notification_Event__e/fields/Work_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Id__c</fullName>
    <label>Work Order Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FSL_MobileNotificationTriggerHandler.cls
/**
 * Created by divnaidu on 9/10/2019.
 */

public class FSL_MobileNotificationTriggerHandler extends FSL_TriggerDispatcher.TriggerHandlerBase {
     
    List<Mobile_Notification_Event__e> newList = Trigger.new;
    List<Mobile_Notification_Event__e> oldList = Trigger.old;
    Map<Id, Mobile_Notification_Event__e> newMap = (Map<Id, Mobile_Notification_Event__e>)Trigger.newMap;
    Map<Id, Mobile_Notification_Event__e> oldMap = (Map<Id, Mobile_Notification_Event__e>)Trigger.oldMap;

    //========================================================================================================================
    //========================================================================================================================
    public override Boolean isDisabled() {
        return FSL_TriggerUtility.isDisabled('Mobile_Notification_Event__e');
    }

    //========================================================================================================================
    //========================================================================================================================
    public override void afterInsert() {
        evaluateNotificationAction();
    }


    //========================================================================================================================
    //========================================================================================================================
    //========================================================================================================================


    private void evaluateNotificationAction() {
        System.debug('!@#$%Entering FSL_MobileNotificationTrigger........' + newList);

        List<Mobile_Notification_Event__e> statusChangePostList = new List<Mobile_Notification_Event__e>();
        List<Mobile_Notification_Event__e> addressChangedEventList = new List<Mobile_Notification_Event__e>();
        List<Mobile_Notification_Event__e> violationEventList = new List<Mobile_Notification_Event__e>(); 
        for(Mobile_Notification_Event__e evt : newList) {
            if(evt.Status_Updated__c) {
                statusChangePostList.add(evt);
            }            
            if(evt.Address_Changed__c) {
                addressChangedEventList.add(evt);
            }
            if(!string.isEmpty(evt.Work_Order_Id__c)){
                violationEventList.add(evt);
            }
        }

        if(!violationEventList.isEmpty()){
            FSL_NotificationFramework.violationsPost(violationEventList);
        }
        if(!statusChangePostList.isEmpty()) {
            FSL_NotificationFramework.statusChangePosts(statusChangePostList);
        }
        if(!addressChangedEventList.isEmpty()) {
            FSL_NotificationFramework.addressChangedPost(addressChangedEventList);
        }

    }

}