unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/ACG_Facility_Adjustment_Payment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment Payment</label>
    <nameField>
        <displayFormat>FAP-{000}</displayFormat>
        <label>Facility Adjustment Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustment Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/ACG_Status__c.field-meta.xml
<CustomField>
    <fullName>ACG_Status__c</fullName>
    <description>Visible to System Admin only, read-only for all other users. Gets updated when Invoice.Status__c is updated. 

Implemented this way for Facility Adjustment object to reference as filter criteria for roll-up summary fields.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Facility Adjustment Payments</relationshipLabel>
    <relationshipName>Facility_Adjustment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>SI#{00000000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice_Line_Item__c/fields/Facility_Adjustment_Payment__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Adjustment Payment</label>
    <referenceTo>ACG_Facility_Adjustment_Payment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AAAUpdateFAPWithInvoiceStatusBatch.cls
/**
 * @description       : Batch class that helps update Facility Adjustment Payments with the associated Invoice's status
 * @author            : joshtupas@salesforce.com 
 * @group             : 
 * @last modified on  : 05-28-2024
 * @last modified by  : Josh Tupas
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   05-03-2024   joshtupas@salesforce.com  
 *       05-28-2024   joshtupas@salesforce.com             Refactored query to use SOQL instead of query string
**/
public class AAAUpdateFAPWithInvoiceStatusBatch implements Database.Batchable<SObject>, Database.Stateful, Schedulable {
    public String query;
    private List<String> invcIdList;

    public AAAUpdateFAPWithInvoiceStatusBatch() {
        this.invcIdList = new List<String>();
    }

    public AAAUpdateFAPWithInvoiceStatusBatch(List<String> invcIdList) {
        this.invcIdList = invcIdList;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        if (invcIdList != null && invcIdList.size() > 0) {
            return Database.getQueryLocator(
                [
                    SELECT 
                        Id,
                        Facility_Adjustment_Payment__r.ACG_Status__c,
                        Invoice__r.Status__c
                    FROM Invoice_Line_Item__c
                    WHERE Facility_Adjustment_Payment__c != null
                    AND Invoice__c IN :invcIdList
                ]
            );
        }
        
        return Database.getQueryLocator(
            [
                SELECT 
                    Id,
                    Facility_Adjustment_Payment__r.ACG_Status__c,
                    Invoice__r.Status__c
                FROM Invoice_Line_Item__c
                WHERE Facility_Adjustment_Payment__c != null
                AND Facility_Adjustment_Payment__r.ACG_Status__c = null
            ]
        );
    }

    public void execute(Database.BatchableContext bc, List<Invoice_Line_Item__c> scope) {
        List<ACG_Facility_Adjustment_Payment__c> fapUpdateList = new List<ACG_Facility_Adjustment_Payment__c>();

        for (Invoice_Line_Item__c ili : scope) {
            String invcStatus = ili.Invoice__r.Status__c;
            ACG_Facility_Adjustment_Payment__c fap = ili.Facility_Adjustment_Payment__r;

            if (fap.ACG_Status__c != invcStatus) {
                fap.ACG_Status__c = invcStatus;
                fapUpdateList.add(fap);
            }
        }

        if (fapUpdateList.size() > 0) {
            update fapUpdateList;
        }
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Batch Job Completed');
    }

    public void execute(SchedulableContext ctx) {
        AAAUpdateFAPWithInvoiceStatusBatch batch = new AAAUpdateFAPWithInvoiceStatusBatch();

        Database.executeBatch(batch, 1000);
    }
}