unpackaged/main/default/objects/Facility_Service_Item__c/Facility_Service_Item__c.object-meta.xml
<CustomObject>
    <label>Facility Service Item</label>
    <nameField>
        <displayFormat>FSI-{0000000000}</displayFormat>
        <label>Facility Service Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Service Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Facility_Service_Item__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Facility Service Items</relationshipLabel>
    <relationshipName>Facility_Service_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Facility_Service_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Facility Service Items</relationshipLabel>
    <relationshipName>Facility_Service_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AAAOmniUtilityRemoteActionClass.cls
global class AAAOmniUtilityRemoteActionClass implements omnistudio.VlocityOpenInterface2 {
    public Boolean invokeMethod(String methodName, Map<String,Object> input, Map<String,Object> output, Map<String,Object> options) {
        Boolean result = true;

        try {
            if (methodName.equals('getFilteredProductsByFacSLIs')) {
                getFilteredProductsByFacSLIs(input, output);
            }
        } catch(Exception e) {
            result = false;
            System.debug(e);
        }
        
        return result;
    }

    public void getFilteredProductsByFacSLIs(Map<String,Object> input, Map<String,Object> output) {
        String facId = (String) input.get('ServiceTerritoryId');
        String queryStr = '%' + (String) input.get('ProductName') + '%';
        List<Product2> prod2List = [
            SELECT Id, Name, ProductCode
            FROM Product2 
            WHERE Id NOT IN (
                SELECT Product__c 
                FROM Facility_Service_Item__c 
                WHERE Facility__c = :facId
            )
            AND IsActive = true
            AND Family != 'Trouble Code'
            AND Name LIKE :queryStr
            ORDER BY Name ASC
            LIMIT 20
        ];
        List<Map<String, Object>> respList = new List<Map<String, Object>>();

        for (Product2 prod2 : prod2List) {
            Map<String, Object> obj = new Map<String, Object>();

            obj.put('ProductId', prod2.Id);
            obj.put('ProductCode', prod2.ProductCode);
            obj.put('ProductName', prod2.Name);

            respList.add(obj);
        }

        output.put('Products', respList);
    }
}