unpackaged/main/default/objects/ServiceTerritory/fields/Enable_Calculate_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Enable_Calculate_Mileage__c</fullName>
    <label>Enable Calculate Mileage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>From Service Territory</fullName>
            </value>
            <value>
                <fullName>From Driver Location</fullName>
            </value>
            <value>
                <fullName>Not Calculated Facility</fullName>
                <default>true</default>
                <label>Not Calculated Facility</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/recordTypes/Facility_Territory.recordType-meta.xml
<RecordType>
    <fullName>Facility_Territory</fullName>
    <active>true</active>
    <description>Territory that handles all types of services</description>
    <label>Facility Territory</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/fields/Call_Id__c.field-meta.xml
<CustomField>
    <fullName>Call_Id__c</fullName>
    <label>Call ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Clearing_Code__c.field-meta.xml
<CustomField>
    <fullName>Clearing_Code__c</fullName>
    <label>Clearing Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clear_Codes</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Resolution_Code__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Code__c</fullName>
    <label>Resolution Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CAR_ConsolidatedResoCodes</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Clear_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>8X</fullName>
    </customValue>
    <customValue>
        <fullName>BK</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
    </customValue>
    <customValue>
        <fullName>M8</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <customValue>
        <fullName>MX</fullName>
    </customValue>
    <customValue>
        <fullName>N1</fullName>
    </customValue>
    <customValue>
        <fullName>N2</fullName>
    </customValue>
    <customValue>
        <fullName>N3</fullName>
    </customValue>
    <customValue>
        <fullName>N4</fullName>
    </customValue>
    <customValue>
        <fullName>N5</fullName>
    </customValue>
    <customValue>
        <fullName>N9</fullName>
    </customValue>
    <customValue>
        <fullName>NX</fullName>
    </customValue>
    <customValue>
        <fullName>RR</fullName>
    </customValue>
    <customValue>
        <fullName>XX</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>2A</fullName>
        <isActive>false</isActive>
        <label>2A</label>
    </customValue>
    <customValue>
        <fullName>XE</fullName>
        <isActive>false</isActive>
        <label>XE</label>
    </customValue>
    <customValue>
        <fullName>SF</fullName>
        <isActive>false</isActive>
        <label>SF</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <isActive>false</isActive>
        <label>SD</label>
    </customValue>
    <customValue>
        <fullName>PR</fullName>
        <isActive>false</isActive>
        <label>PR</label>
    </customValue>
    <customValue>
        <fullName>NG</fullName>
        <isActive>false</isActive>
        <label>NG</label>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
        <isActive>false</isActive>
        <label>NE</label>
    </customValue>
    <customValue>
        <fullName>M9</fullName>
        <isActive>false</isActive>
        <label>M9</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <isActive>false</isActive>
        <label>CA</label>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
        <isActive>false</isActive>
        <label>BN</label>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
        <isActive>false</isActive>
        <label>BM</label>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
        <isActive>false</isActive>
        <label>AD</label>
    </customValue>
    <customValue>
        <fullName>2T</fullName>
        <isActive>false</isActive>
        <label>2T</label>
    </customValue>
    <masterLabel>Clear Codes</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/AAAIPInvocableWithOutputsTest.cls
@isTest
class AAAIPInvocableWithOutputsTest {
    @isTest(SeeAllData=true)  
    static void runIntegrationServiceInvocableTest() {
        RecordType facTerritoryType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Facility_Territory' LIMIT 1];

        OperatingHours opHrs = new OperatingHours(
            TimeZone = 'America/New_York',
            Name = 'Apex Test Time Zone'
        );
        insert opHrs;

        ServiceTerritory svcTerritory = new ServiceTerritory(
            Name = 'Apex Test Service Territory',
            RecordTypeId = facTerritoryType.Id,
            OperatingHoursId = opHrs.Id,
            Enable_Calculate_Mileage__c = 'From Service Territory',
            isActive = true
        );
        insert svcTerritory;
        
        WorkOrder wo = new WorkOrder(
            Call_Id__c = 'Apex Test Work Order 22',
            Status = 'Cleared',
            Resolution_Code__c = 'G101',
            ServiceTerritoryId = svcTerritory.Id
        );
        insert wo;

        WorkOrder testWo = [SELECT Id, Status, Resolution_Code__c, Clearing_Code__c FROM WorkOrder WHERE Call_Id__c = 'Apex Test Work Order 22' LIMIT 1];
        List<AAAIPInvocableWithOutputs.IntegrationProcedureInput> ipInputList = new List<AAAIPInvocableWithOutputs.IntegrationProcedureInput>();
        AAAIPInvocableWithOutputs.IntegrationProcedureInput ipInput = new AAAIPInvocableWithOutputs.IntegrationProcedureInput();
        List<AAAIPInvocableWithOutputs.IntegrationProcedureOutput> result = new List<AAAIPInvocableWithOutputs.IntegrationProcedureOutput>();
        Boolean calledIntegrationProcedure = false;

        ipInput.currentWorkOrderId = testWo.Id;
        ipInput.procedureAPIName = 'backOffice_CreateNewServiceLineWithBA';
        ipInputList.add(ipInput);

        Test.startTest();
            try {
                result = AAAIPInvocableWithOutputs.runIntegrationServiceInvocable(ipInputList);
                calledIntegrationProcedure = true;
            } catch (Exception e) {
                System.debug(e.getStackTraceString());
            }
        Test.stopTest();

        System.assertEquals(calledIntegrationProcedure, true, 'Unable to call integration procedure.');
    }
}