unpackaged/main/default/objects/FSL_Call_Comments__c/FSL_Call_Comments__c.object-meta.xml
<CustomObject>
    <label>FSL Call Comments</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Call Comments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Call_Comments__c/fields/FSL_Comment__c.field-meta.xml
<CustomField>
    <fullName>FSL_Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/FSL_Call_Comments__c/fields/FSL_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>FSL_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>Call_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FSL_CallComments.cls
public with sharing class FSL_CallComments {

    // *********************************************
    // * Factory
    // *********************************************
    public interface IFactory {
        ICallCommentsService createService();
    }

    public class Factory implements IFactory {
        public ICallCommentsService createService() {
            ICallCommentsDAO dao = createDAO();
            return new CalLCommentsService( dao );
        }

        private ICallCommentsDAO createDAO() {
            return new CallCommentsDAO();
        }
    }

    // *********************************************
    // * DAO
    // *********************************************
    public interface ICallCommentsDAO extends FSL_DAO.DmlInterface {

    }

    public class CallCommentsDAO extends FSL_DAO.DmlBase implements  ICallCommentsDAO {

    }

    // *********************************************
    // * Service
    // *********************************************
    public interface ICallCommentsService {
        void saveWorkOrderComments(Map<Id, List<String>> workOrderComments);
    }

    public class CallCommentsService implements ICallCommentsService {

        private ICallCommentsDAO dao;

        public CallCommentsService( ICallCommentsDAO dao ) {
            this.dao = dao;
        }

        public void saveWorkOrderComments(Map<Id, List<String>> workOrderComments) {

            List<FSL_Call_Comments__c> allComments = new List<FSL_Call_Comments__c> ();
            List<String> comments;
            for ( Id woId : workOrderComments.keySet()) {
                comments = workOrderComments.get(woId);
                for ( String comment : comments) {
                    allComments.add (new FSL_Call_Comments__c(FSL_Work_Order__c = woId,  FSL_Comment__c = comment));
                }
            }
            dao.insertRecords(allComments);
        }
    }

}