unpackaged/main/default/objects/Account/fields/AAA_Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>AAA_Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Plus</fullName>
            </value>
            <value>
                <fullName>Plus RV</fullName>
            </value>
            <value>
                <fullName>Premier RV</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ACG_AAA_Membership__c.field-meta.xml
<CustomField>
    <fullName>ACG_AAA_Membership__c</fullName>
    <externalId>true</externalId>
    <label>AAA Membership #</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/ACG_Entitlements_Allotted__c.field-meta.xml
<CustomField>
    <fullName>ACG_Entitlements_Allotted__c</fullName>
    <label>Max Entitlements Allotted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ACG_Entitlements_Used__c.field-meta.xml
<CustomField>
    <fullName>ACG_Entitlements_Used__c</fullName>
    <label>Entitlements Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Long_Tow_Kilometers_Used__c.field-meta.xml
<CustomField>
    <fullName>Long_Tow_Kilometers_Used__c</fullName>
    <label>Long Tow Kilometers Used</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Long_Tow_Miles_Used__c.field-meta.xml
<CustomField>
    <fullName>Long_Tow_Miles_Used__c</fullName>
    <label>Long Tow Miles Used</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACURA</fullName>
            </value>
            <value>
                <fullName>ADVANCE MIXER</fullName>
            </value>
            <value>
                <fullName>ALFA ROMEO</fullName>
            </value>
            <value>
                <fullName>ALLSTATE</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMERICAN AUSTIN</fullName>
            </value>
            <value>
                <fullName>AMERICAN BANTAM</fullName>
            </value>
            <value>
                <fullName>AMERICAN COACH</fullName>
            </value>
            <value>
                <fullName>AMERICAN EAGLE</fullName>
            </value>
            <value>
                <fullName>AMERICAN HERITAGE</fullName>
            </value>
            <value>
                <fullName>AMERICAN IRONHORSE</fullName>
            </value>
            <value>
                <fullName>AMERICAN LAFRANCE</fullName>
            </value>
            <value>
                <fullName>AMERICAN QUANTUM</fullName>
            </value>
            <value>
                <fullName>AMERICAN SUNDIRO</fullName>
            </value>
            <value>
                <fullName>ANTHEM</fullName>
            </value>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>APOLLO</fullName>
            </value>
            <value>
                <fullName>APRILIA</fullName>
            </value>
            <value>
                <fullName>ARNOLT-MG</fullName>
            </value>
            <value>
                <fullName>ARROWHEAD</fullName>
            </value>
            <value>
                <fullName>ASPEN</fullName>
            </value>
            <value>
                <fullName>ASTON MARTIN</fullName>
            </value>
            <value>
                <fullName>ATK</fullName>
            </value>
            <value>
                <fullName>AUBURN</fullName>
            </value>
            <value>
                <fullName>AUDI</fullName>
            </value>
            <value>
                <fullName>AUSTIN HEALEY</fullName>
            </value>
            <value>
                <fullName>AUSTIN ROVER</fullName>
            </value>
            <value>
                <fullName>AUTOCAR</fullName>
            </value>
            <value>
                <fullName>AUTOCAR LLC.</fullName>
            </value>
            <value>
                <fullName>AVALANCHE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_AAA_Membership__c.field-meta.xml
<CustomField>
    <fullName>ACG_AAA_Membership__c</fullName>
    <formula>Account.ACG_AAA_Membership__c</formula>
    <inlineHelpText>AAA Membership # of related Account.</inlineHelpText>
    <label>AAA Membership #</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Color__c.field-meta.xml
<CustomField>
    <fullName>ACG_Color__c</fullName>
    <label>Vehicle Color</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Driving_Directions__c.field-meta.xml
<CustomField>
    <fullName>ACG_Driving_Directions__c</fullName>
    <description>This field maps to Driving Directions on the Work Order</description>
    <label>Driver Directions</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Make__c.field-meta.xml
<CustomField>
    <fullName>ACG_Make__c</fullName>
    <label>Vehicle Make</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Model__c.field-meta.xml
<CustomField>
    <fullName>ACG_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Work_Type__c.field-meta.xml
<CustomField>
    <fullName>ACG_Work_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Type</label>
    <referenceTo>WorkType</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Year__c.field-meta.xml
<CustomField>
    <fullName>ACG_Year__c</fullName>
    <description>Vehicle manufacturing year. Populated via Car Care Appointment Page</description>
    <label>Vehicle Year</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Member_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Member_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Vehicle</label>
    <referenceTo>FSL_Member_Vehicle__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Pacesetter_Code__c.field-meta.xml
<CustomField>
    <fullName>Pacesetter_Code__c</fullName>
    <label>Pacesetter Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/T_Code__c.field-meta.xml
<CustomField>
    <fullName>T_Code__c</fullName>
    <label>T-Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Tow_Destination_City__c.field-meta.xml
<CustomField>
    <fullName>Tow_Destination_City__c</fullName>
    <label>Tow Destination City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Tow_Destination_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Tow_Destination_Postal_Code__c</fullName>
    <label>Tow Destination Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Tow_Destination_State__c.field-meta.xml
<CustomField>
    <fullName>Tow_Destination_State__c</fullName>
    <label>Tow Destination State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Tow_Destination_Street__c.field-meta.xml
<CustomField>
    <fullName>Tow_Destination_Street__c</fullName>
    <label>Tow Destination Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vehicle_Location_City__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Location_City__c</fullName>
    <label>Vehicle Location City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vehicle_Location_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Location_Postal_Code__c</fullName>
    <label>Vehicle Location Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vehicle_Location_State__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Location_State__c</fullName>
    <label>Vehicle Location State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vehicle_Location_Street__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Location_Street__c</fullName>
    <label>Vehicle Location Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ACG_AAA_Membership__c.field-meta.xml
<CustomField>
    <fullName>ACG_AAA_Membership__c</fullName>
    <formula>Account.ACG_AAA_Membership__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AAA Membership #</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/FSL_Member_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Member Vehicle</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/ACG_Member__c.field-meta.xml
<CustomField>
    <fullName>ACG_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Member Vehicles</relationshipLabel>
    <relationshipName>Member_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Settings__c/fields/Extra_Header_Value__c.field-meta.xml
<CustomField>
    <fullName>Extra_Header_Value__c</fullName>
    <label>Extra Header Value</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Settings__c/fields/Header_Value__c.field-meta.xml
<CustomField>
    <fullName>Header_Value__c</fullName>
    <label>Header Value</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkType/fields/T_Code__c.field-meta.xml
<CustomField>
    <fullName>T_Code__c</fullName>
    <label>T-Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>GU</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MH</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MP</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <description>US State Abbreviation Codes</description>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/FSL_INTCallMoverOutbound_Test.cls
/**** Apex Test Class Name:    FSL_INTCallMoverOutbound_Test
    * Description        :     This is the test class used to test FSL_INTCallMoverOutbound class
    * ---------------------------------------------------------------------------
    * Developer                   Date                   Description
    * ---------------------------------------------------------------------------
    * Venkat Kommuri               Nov 15 2021             Created
*********************************************************************************/
@isTest(SeeAllData = false)
public class FSL_INTCallMoverOutbound_Test {
    
    @Testsetup
    public static void datasetforCON(){
        
        
        List<Integration_Settings__c> lstIntegrationSetting = new List<Integration_Settings__c>();
        Integration_Settings__c IntegrationSetting = new Integration_Settings__c();
        IntegrationSetting.name = 'CallMover_Outbound_API';
        IntegrationSetting.Method__c='POST';
        IntegrationSetting.Header_Value__c='[{"key":"Content-Type","value":"application/json"}]';
        IntegrationSetting.Enpoint_URL__c='https://api-qa.national.aaa.com/automotive/services/ci/v1/calls/move';
        IntegrationSetting.Request_Timeout__c=120000;
        lstIntegrationSetting.add(IntegrationSetting);
        
        Integration_Settings__c IntegrationSetting1 = new Integration_Settings__c();
        IntegrationSetting1.name = 'National_OAuth_API';
        IntegrationSetting1.Method__c='POST';
        IntegrationSetting1.Header_Value__c='[{"key":"Content-Type","value":"application/json"}]';
        IntegrationSetting1.Extra_Header_Value__c = 'grant_type=client_credentials';
        IntegrationSetting1.Enpoint_URL__c='https://api-qa.national.aaa.com/common/oauth2/token';
        IntegrationSetting1.Request_Timeout__c=120000;
        lstIntegrationSetting.add(IntegrationSetting1);
        
        insert lstIntegrationSetting;
        
        Id recordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ACG_ERS').getRecordTypeId();
        Id MEMBER_ACCOUNT_RECORDTYPEID = ACG_UtilityClass.MEMBER_RECORDTYPE_ID;
        List<Account> lstMembers = ACG_TestDataFactory.createAccounts(MEMBER_ACCOUNT_RECORDTYPEID,1,false,true);
        for(Account objacc:lstMembers){  
            objacc.ACG_AAA_Membership__c='4299941234757815';
            objacc.AAA_Membership_Level__c='Plus';
            objacc.phone = '9999999999';
            objacc.Long_Tow_Kilometers_Used__c =161;
            objacc.Long_Tow_Miles_Used__c=100;
           // objacc.Rental_Days__c=2;
            objacc.ACG_Entitlements_Allotted__c=2;
            objacc.ACG_Entitlements_Used__c=1;
           // objacc.Rental_Days__c=2;
         }
        
        insert lstMembers; 
        
        Account acc = [Select id from Account  where recordtypeId=:MEMBER_ACCOUNT_RECORDTYPEID limit 1];
        FSL_Member_Vehicle__c mem = new FSL_Member_Vehicle__c(Vehicle_Make__c = 'Jeeps',ACG_Member__c = acc.Id);
        insert mem;
        
        WorkType WT_Rec = new WorkType(Name = 'Fuel Delivery', EstimatedDuration = 10.0, DurationType = 'Minutes');
        insert WT_Rec;
        
        Case objcs = new Case();
        objcs = ACG_TestDataFactory.createcase(recordTypeID,'In Progress','Phone',true);
        objcs.AccountId = acc.Id;
        objcs.Member_Vehicle__c = mem.ID;
        objcs.ACG_Make__c = 'Honda';
        objcs.ACG_Color__c = 'Silver';
        objcs.ACG_Year__c = '2019';
        objcs.ACG_Model__c = 'Aista';
        objcs.Vehicle_Location_Street__c = '15029 TYACKE DR';
        objcs.Vehicle_Location_City__c = 'Charlotte';
        objcs.Vehicle_Location_State__c = 'NC';
        objcs.Vehicle_Location_Postal_Code__c  = '28202';
        objcs.ACG_Driving_Directions__c = 'Near Parking plot';
        objcs.Vehicle_Geolocation__Latitude__s = 34.779527;
        objcs.Vehicle_Geolocation__Longitude__s = -122.537032;
        objcs.Tow_Destination_Street__c = '15029 TYACKE DR';
        objcs.Tow_Destination_City__c = 'Charlotte';
        objcs.Tow_Destination_State__c = 'North Carolina';
        objcs.Tow_Destination_Postal_Code__c  = '28202';
        objcs.Tow_Geolocation__Latitude__s = 34.779527;
        objcs.Tow_Geolocation__Longitude__s = -122.537032;
        objcs.T_Code__C = 'T6';
        objcs.Pacesetter_Code__c = 'T480';
        objcs.ACG_Work_type__C = WT_Rec.Id;
        update objcs;
       
    }
    
    @isTest static void casetransfertoNational(){
        Test.startTest();
        Id recordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ACG_ERS').getRecordTypeId();
        string res = '{"access_token": "eyJraWQiOiJVRHZyUHpm","expires_in": 3600,"token_type": "Bearer"}';
        string res1 = '{\"statusCode\":\"200\",\"statusDescription\":\"SuccessfullymovedcalltoD39f719f0c-1231-7cf6-661b-7360b634367e\",\"sourceSystem\":{\"systemId\":\"D3\"},\"header\":{\"version\":\"2.0\",\"type\":\"ResponseType\",\"subType\":\"ResponseSubType\",\"status\":\"SUCCESS\",\"id\":\"9f719f0c-1231-7cf6-661b-7360b634367e\"},\"responsePayload\":{\"callKey\":\"311-20211223-3\",\"pta\":\"2021-12-23T02:05:00.000Z\"}}';
        Test.setMock(HttpCalloutMock.class, new HttpRestCalloutMock(res, 200));
        Test.setMock(HttpCalloutMock.class, new HttpRestCalloutMock(res1, 200));
        case objcs = [select id from case where recordtypeId=:recordTypeID limit 1];
        FSL_INTCallMoverOutbound.Response_wrapper resp = new FSL_INTCallMoverOutbound.Response_wrapper();
        resp=FSL_INTCallMoverOutbound.generateCallMoverRequest(objcs.Id);
        system.assertEquals(resp.isSuccess, true);
        FSL_CallMoverJSONRequest_Wrapper wrp= new FSL_CallMoverJSONRequest_Wrapper();
        FSL_CallMoverJSONRequest_Wrapper.Calls call = new FSL_CallMoverJSONRequest_Wrapper.Calls();
        FSL_CallMoverJSONRequest_Wrapper.Contact con = new FSL_CallMoverJSONRequest_Wrapper.Contact();
        con.userId='2135';
        con.contactType='test con';
        FSL_CallMoverJSONRequest_Wrapper.systemOrganization sys = new FSL_CallMoverJSONRequest_Wrapper.systemOrganization();
        sys.name='test';
        sys.code='1234';
        FSL_CallMoverJSONRequest_Wrapper.SourceSystem src = new FSL_CallMoverJSONRequest_Wrapper.SourceSystem();
        src.systemId='1111111';
        src.systemOrganization=sys;
        FSL_CallMoverJSONRequest_Wrapper.Comments com = new FSL_CallMoverJSONRequest_Wrapper.Comments();
        com.text='test';
        com.visibility='test';
        com.commentType='test';
        com.commentDate='01-05-2022';
        com.contact=con;
        com.system_Z=src;
        FSL_CallMoverJSONRequest_Wrapper.Comments com1 = new FSL_CallMoverJSONRequest_Wrapper.Comments();
        com1.text='test1';
        com1.visibility='test1';
        com1.commentType='test1';
        com1.commentDate='02-05-2022';
        com1.contact=con;
        com1.system_Z=src;
        FSL_CallMoverJSONRequest_Wrapper.Address add = new FSL_CallMoverJSONRequest_Wrapper.Address();
        add.full='test';
        add.streetNumber='99';
        add.streetDirection='right';
        add.streetName='test street';
        add.crossStreet='no';
        FSL_CallMoverJSONRequest_Wrapper.ServiceLocations_Location serloc = new FSL_CallMoverJSONRequest_Wrapper.ServiceLocations_Location();
        serloc.latitude=1.2;
        serloc.longitude=4.5;
        serloc.highway='NH4';
        serloc.mileMarker='194';
        serloc.grid='test';
        serloc.zone='green';
        serloc.locationCode='890759';
        serloc.landmark='test mark';
        serloc.address=add;
        List<FSL_CallMoverJSONRequest_Wrapper.Phones_Contacts> Phones_Contacts=new List<FSL_CallMoverJSONRequest_Wrapper.Phones_Contacts>();
        FSL_CallMoverJSONRequest_Wrapper.Phones_Contacts Phones_Contact= new FSL_CallMoverJSONRequest_Wrapper.Phones_Contacts();
        Phones_Contact.phoneType='test';
        Phones_Contact.phoneNumber='test';
        Phones_Contact.preferred=true;
        Phones_Contacts.add(Phones_Contact);
        List<FSL_CallMoverJSONRequest_Wrapper.Contacts> contacts=new List<FSL_CallMoverJSONRequest_Wrapper.Contacts>();
        FSL_CallMoverJSONRequest_Wrapper.Contacts conts = new FSL_CallMoverJSONRequest_Wrapper.Contacts();
        conts.contactType='test';
        conts.firstName='test1';
        conts.lastName='test2';
        conts.phones=Phones_Contacts;
        contacts.add(conts);
        FSL_CallMoverJSONRequest_Wrapper.Foi fo = new FSL_CallMoverJSONRequest_Wrapper.Foi();
        fo.location=serloc;
        fo.contacts=contacts;
        fo.name='test';
        List<FSL_CallMoverJSONRequest_Wrapper.ServiceLocations> serlocations = new List<FSL_CallMoverJSONRequest_Wrapper.ServiceLocations>();
        FSL_CallMoverJSONRequest_Wrapper.ServiceLocations serlocation=new FSL_CallMoverJSONRequest_Wrapper.ServiceLocations();
        serlocation.foi=fo;
        serlocation.mileageCalculated=1.0;
        serlocation.milesFromOrigin=10;
        serlocation.dropBoxInfo='test';
        serlocations.add(serlocation);
        
        FSL_CallMoverJSONRequest_Wrapper.Status Status = new FSL_CallMoverJSONRequest_Wrapper.Status();
        Status.status='draft';
        Status.updatecode='100';
        Status.modifiedDate=Datetime.newInstance(2022,2, 17);
        Status.pta='test';
        Status.waitTime=90;
        FSL_CallMoverJSONRequest_Wrapper.Service service = new FSL_CallMoverJSONRequest_Wrapper.Service();
        service.serviceLocations=serlocations;
        service.status=Status;
        
        FSL_CallMoverJSONRequest_Wrapper.Payment pay = new FSL_CallMoverJSONRequest_Wrapper.Payment();
        pay.required=true;
        pay.paymentType='net';
        pay.codes='test';
        pay.responsible='yes';
        List<FSL_CallMoverJSONRequest_Wrapper.Comments> lstcom1 = new List<FSL_CallMoverJSONRequest_Wrapper.Comments>();
        lstcom1.add(com1);
        lstcom1.add(com);
        call.service=service;
        call.comments=lstcom1;
        call.payment=pay;
        //wrp.calls.add(call);
        Test.stopTest();
    }

}