unpackaged/main/default/objects/Account/fields/ACG_AAA_Membership__c.field-meta.xml
<CustomField>
    <fullName>ACG_AAA_Membership__c</fullName>
    <externalId>true</externalId>
    <label>AAA Membership #</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/ERS_Member.recordType-meta.xml
<RecordType>
    <fullName>ERS_Member</fullName>
    <active>true</active>
    <label>ERS Member</label>
</RecordType>

unpackaged/main/default/objects/ACG_Reimbursement__c/ACG_Reimbursement__c.object-meta.xml
<CustomObject>
    <label>Reimbursement</label>
    <nameField>
        <displayFormat>RM-{000000}</displayFormat>
        <label>Reimbursement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reimbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Reimbursement__c/fields/ACG_Charge_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>ACG_Charge_Entitlement__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Charge Entitlement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ACG_Reimbursement__c/fields/ACG_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>ACG_Member_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERS Member</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>ERS Member, Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACG_Reimbursement__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Reimbursements</relationshipLabel>
    <relationshipName>Reimbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>Store Authorization information for entitlements for members serviced outside of their respective clubs.</description>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FB-{0000}</displayFormat>
        <label>Feedback</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Feedback__c/fields/Charge_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Charge_Entitlement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox that is set when a Feedback provided by other clubs.</description>
    <label>Charge Entitlement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Feedback__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Feedback__c/fields/Source_Club__c.field-meta.xml
<CustomField>
    <fullName>Source_Club__c</fullName>
    <label>Source Club</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/Reciprocal__c.object-meta.xml
<CustomObject>
    <label>Reciprocal</label>
    <nameField>
        <displayFormat>REC-{000}</displayFormat>
        <label>Reciprocal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reciprocals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reciprocal__c/fields/Charge_Entitlements__c.field-meta.xml
<CustomField>
    <fullName>Charge_Entitlements__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Charge Entitlements</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feedback</label>
    <referenceTo>Feedback__c</referenceTo>
    <relationshipLabel>Reciprocals</relationshipLabel>
    <relationshipName>Reciprocals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Reciprocals</relationshipLabel>
    <relationshipName>Reciprocals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/recordTypes/Feedback.recordType-meta.xml
<RecordType>
    <fullName>Feedback</fullName>
    <active>true</active>
    <label>Feedback</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/fields/AAA_Charge_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>AAA_Charge_Entitlement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox that is set when a WO is cleared. This field is Read Only for users</description>
    <label>Charge Entitlement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Reciprocal__c.field-meta.xml
<CustomField>
    <fullName>Reciprocal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reciprocal</label>
    <referenceTo>Reciprocal__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AAA_EntitlementDetails_Test.cls
@isTest
private class AAA_EntitlementDetails_Test {
   @testSetup
   static void setupTestData() {
       //Get the account record type
       RecordType AccRecType = [
           select Id from RecordType where SObjectType = 'Account' and DeveloperName = 'ERS_Member' limit 1
       ];
       // Create Account
       Account acc = new Account(
           Name = 'Test Account',
           ACG_AAA_Membership__c = '6202408673324206',
           RecordTypeId = AccRecType.Id);
       insert acc;
       // Create Active ServiceContract
       ServiceContract sc = new ServiceContract(
           AccountId = acc.Id,
           StartDate = Date.today(),
           Name = 'Test Service Contract'
       );
       insert sc;
       // WorkOrder
       WorkOrder wo = new WorkOrder(
           Subject = 'Test WO',
           ServiceContractId = sc.Id,
           Status = 'Cleared',
           AAA_Charge_Entitlement__c = true
       );
       insert wo;
       // Reciprocal__c
       Reciprocal__c rc = new Reciprocal__c(
           Service_Contract__c = sc.Id,
           Charge_Entitlements__c = true
       );
       insert rc;
       // ACG_Reimbursement__c
       ACG_Reimbursement__c re = new ACG_Reimbursement__c(
           Service_Contract__c = sc.Id,
           ACG_Charge_Entitlement__c = true,
           ACG_Member_Name__c = acc.id
       );
       insert re;
       // Feedback__c
       Feedback__c fb = new Feedback__c(
           Service_Contract__c = sc.Id,
           Charge_Entitlement__c = true,
           Source_Club__c = '111'
       );
       insert fb;
   }
   @isTest
   static void testWithContractsAndRecords() {
       Account acc = [SELECT Id FROM Account LIMIT 1];
       Test.startTest();
       AAA_EntitlementDetails.responseWrapper result =
           AAA_EntitlementDetails.getWorkOrderbyAccount(acc.Id);
       Test.stopTest();
       System.assertNotEquals(null, result, 'Response should not be null');
       System.assert(result.hasServiceContracts, 'Should detect service contracts');
       System.assert(result.records.size() > 0, 'Should return related records');
       // Validate record types
       Set<String> expectedTypes = new Set<String>{'Work Order','Reciprocal','Reimbursement','Feedback'};
       Set<String> actualTypes = new Set<String>();
       for (AAA_EntitlementDetails.CombinedRecord rec : result.records) {
           actualTypes.add(rec.recType);
           System.assertNotEquals(null, rec.createdDate, 'CreatedDate should be populated');
       }
       System.assertEquals(expectedTypes, actualTypes, 'All record types should be included');
   }
   @isTest
   static void testNoContracts() {
       Account acc2 = new Account(Name = 'No Contract Account');
       insert acc2;
       Test.startTest();
       AAA_EntitlementDetails.responseWrapper result =
           AAA_EntitlementDetails.getWorkOrderbyAccount(acc2.Id);
       Test.stopTest();
       System.assertEquals(false, result.hasServiceContracts, 'No contracts expected');
       System.assertEquals(0, result.records.size(), 'No records expected');
   }
   @isTest
   static void testNullAccountId() {
       Test.startTest();
       AAA_EntitlementDetails.responseWrapper result =
           AAA_EntitlementDetails.getWorkOrderbyAccount(null);
       Test.stopTest();
       System.assertEquals(false, result.hasServiceContracts, 'Should be false when accountId is null');
       System.assertEquals(0, result.records.size(), 'No records expected when accountId is null');
   }
}