unpackaged/main/default/objects/Account/fields/ACG_AAA_Membership__c.field-meta.xml
<CustomField>
    <fullName>ACG_AAA_Membership__c</fullName>
    <externalId>true</externalId>
    <label>AAA Membership #</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <externalId>true</externalId>
    <label>Member ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_AAA_Membership__c.field-meta.xml
<CustomField>
    <fullName>ACG_AAA_Membership__c</fullName>
    <formula>Account.ACG_AAA_Membership__c</formula>
    <inlineHelpText>AAA Membership # of related Account.</inlineHelpText>
    <label>AAA Membership #</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <description>Store Authorization information for entitlements for members serviced outside of their respective clubs.</description>
    <label>Feedback</label>
    <nameField>
        <displayFormat>FB-{0000}</displayFormat>
        <label>Feedback</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Feedback__c/fields/Authorization_Code__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Code__c</fullName>
    <label>Authorization Code</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Feedback__c/fields/Authorization_Level__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Level__c</fullName>
    <label>Authorization Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
                <label>Classic/ Basic (B)</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Plus (P)</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Plus RV (R)</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Premier (E)</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Premier RV (V)</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>COD (C)</label>
            </value>
            <value>
                <fullName>X</fullName>
                <label>Call Club (X)</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Plus (Y)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Feedback__c/fields/Long_Tow_Miles__c.field-meta.xml
<CustomField>
    <fullName>Long_Tow_Miles__c</fullName>
    <label>Long Tow Miles</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Feedback__c/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <label>Member ID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Feedback__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incoming Authorization</fullName>
            </value>
            <value>
                <fullName>Outgoing Authorization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Feedback_Message__mdt/Feedback_Message__mdt.object-meta.xml
<CustomObject>
    <label>Feedback Message</label>
    <pluralLabel>Feedback Messages</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Feedback_Message__mdt/fields/message__c.field-meta.xml
<CustomField>
    <fullName>message__c</fullName>
    <label>message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Membership_Coverage_Metadata__mdt/Membership_Coverage_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Membership Coverage Metadata</label>
    <pluralLabel>Membership Coverage Metadata</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Membership_Coverage_Metadata__mdt/fields/Max_Tow_Miles__c.field-meta.xml
<CustomField>
    <fullName>Max_Tow_Miles__c</fullName>
    <label>Max Tow Miles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Membership_Coverage_Metadata__mdt/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASIC</fullName>
            </value>
            <value>
                <fullName>CLASSIC RV</fullName>
            </value>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>PLUS RV</fullName>
            </value>
            <value>
                <fullName>PREMIER</fullName>
            </value>
            <value>
                <fullName>PREMIER RV</fullName>
            </value>
            <value>
                <fullName>CLASSIC</fullName>
                <isActive>false</isActive>
                <label>CLASSIC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Membership_Type_Mapping__mdt/Membership_Type_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Membership Type Mapping</label>
    <pluralLabel>Membership Type Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Membership_Type_Mapping__mdt/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_ACA_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>AAA_ACA_Member_Status__c</fullName>
    <description>Maps the incoming value of memberStatus as per JSOn from D3 i.e. &quot;memberStatus&quot;: &quot;A&quot;</description>
    <inlineHelpText>Maps the incoming value of memberStatus as per JSOn from D3 i.e. &quot;memberStatus&quot;: &quot;A&quot;</inlineHelpText>
    <label>Member Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_ACA_Membership16ID__c.field-meta.xml
<CustomField>
    <fullName>AAA_ACA_Membership16ID__c</fullName>
    <description>In the 16-Digit membership ID, ISO is the first 3, Club Code is the next 3 digits, Member ID (Household Membership ID) is the next 7 digits, Assoc Member Id is the next 2 digits and Check Digit is the last digit</description>
    <externalId>true</externalId>
    <inlineHelpText>In the 16-Digit membership ID, ISO is the first 3, Club Code is the next 3 digits, Member ID (Household Membership ID) is the next 7 digits, Assoc Member Id is the next 2 digits and Check Digit is the last digit</inlineHelpText>
    <label>Membership ID (16 Digit)</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_ACA_Membership_Coverage_Level__c.field-meta.xml
<CustomField>
    <fullName>AAA_ACA_Membership_Coverage_Level__c</fullName>
    <description>Maps the coverage level as per incoming request from D3</description>
    <inlineHelpText>Maps the coverage level as per incoming request from D3</inlineHelpText>
    <label>Membership Coverage Level</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_ACA_Membership_Status__c.field-meta.xml
<CustomField>
    <fullName>AAA_ACA_Membership_Status__c</fullName>
    <description>Maps the incoming value of memberStatus as per JSOn from D3 i.e. &quot;memberStatus&quot;: &quot;A&quot;</description>
    <inlineHelpText>Maps the incoming value of memberStatus as per JSOn from D3 i.e. &quot;memberStatus&quot;: &quot;A&quot;</inlineHelpText>
    <label>Membership Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_ACA_Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>AAA_ACA_Membership_Type__c</fullName>
    <description>Represent the Membership Type i.e. Member for household Membership. Primary and Associate membership is decided by the 14-15 Digits in the 16 Digit Membership ID being 00 or Non 00 values. RAP comes as the value in the incoming request for RAP requests.</description>
    <inlineHelpText>Represent the Membership Type i.e. Member for household Membership. Primary and Associate membership is decided by the 14-15 Digits in the 16 Digit Membership ID being 00 or Non 00 values. RAP comes as the value in the incoming request for RAP requests.</inlineHelpText>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>RAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_ACA_MembershipID__c.field-meta.xml
<CustomField>
    <fullName>AAA_ACA_MembershipID__c</fullName>
    <description>This is the household level Membership ID in the 16-Digit membership ID where ISO is the first 3, Club Code is the next 3 digits, Member ID (Household Membership ID) is the next 7 digits, Assoc Member Id is the next 2 digits and Check Digit is the last digit

In case of RAP its the ID on the membership.

Example: If the 16-Digit membership ID= 4382121353733023, then the Membership ID will be 2694719. 
This type of membership has no person account associated.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is the household level Membership ID in the 16-Digit membership ID where ISO is the first 3, Club Code is the next 3 digits, Member ID (Household Membership ID) is the next 7 digits, Assoc Member Id is the next 2 digits and Check Digit is the last digit

In case of RAP its the ID on the membership.

Example: If the 16-Digit membership ID= 4382121353733023, then the Membership ID will be 2694719. 
This type of membership has no person account associated.</inlineHelpText>
    <label>Membership ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_Same_Day_Service__c.field-meta.xml
<CustomField>
    <fullName>AAA_Same_Day_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Same Day Service</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_Total_of_Calls_Allowed__c.field-meta.xml
<CustomField>
    <fullName>AAA_Total_of_Calls_Allowed__c</fullName>
    <defaultValue>4</defaultValue>
    <description>Field to store the allowed number of calls each member is entitled to</description>
    <inlineHelpText>The number of Service Calls the member is entitled to during the Service Contract period.</inlineHelpText>
    <label>Total # of Calls Allowed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_Total_of_Calls_Consumed__c.field-meta.xml
<CustomField>
    <fullName>AAA_Total_of_Calls_Consumed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Field that gets incremented when a WO or Reimbursement is cleared and Charge Entitlement checkbox is set to True</description>
    <inlineHelpText>The number of Service Calls the member has consumed in AAA Northeast territory (Work Orders and/or Reimbursements) where the “Charge Entitlement” checkbox is checked.</inlineHelpText>
    <label>Total # of Calls Consumed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_Total_of_Calls_Remaining__c.field-meta.xml
<CustomField>
    <fullName>AAA_Total_of_Calls_Remaining__c</fullName>
    <description>Formula that displays the Current number of calls remaining for the member to consume</description>
    <formula>If( (AAA_Total_of_Calls_Allowed__c -  (AAA_Total_of_Calls_Consumed__c +  AAA_Total_of_Reciprocals__c)) &gt;=  0 , (AAA_Total_of_Calls_Allowed__c -  (AAA_Total_of_Calls_Consumed__c +  AAA_Total_of_Reciprocals__c)), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The number of Service Calls the member has left to consume: calculated as Total # Calls Allowed – (Total # Calls Consumed + Total # Reciprocals)</inlineHelpText>
    <label>Total # of Calls Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/fields/AAA_Total_of_Reciprocals__c.field-meta.xml
<CustomField>
    <fullName>AAA_Total_of_Reciprocals__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Field that gets incremented when the member is serviced outside of the club and a Reciprocal is received</description>
    <inlineHelpText>The number of Service Calls that the member has consumed outside AAA Northeast territory (Reciprocals and/or Feedbacks) where the “Charge Entitlement” checkbox is checked.</inlineHelpText>
    <label>Total # of Reciprocals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ServiceContract/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

unpackaged/main/default/classes/INTERSAuthorize.cls
/**** Apex Class Name    :    INTERSAuthorize
* Description        :    API class  to authorize ERS request when member
*                         needs service outside of member home club service territory.  
* Modification Log   :
* Test Class Name    :    
* ---------------------------------------------------------------------------
* Developer                   Date                   Description
* ---------------------------------------------------------------------------
* Venkat Kommuri              Sep 24 2021             Created
* Vishnu Popuru               Oct 25 2024             Updated(modified the code to send "X" as a authorization code for cancelled memebrs)
*********************************************************************************/
@RestResource(urlMapping='/ERSauthorize/*')
global without sharing class INTERSAuthorize {
    
    /***
    * Method name        : getERSAuthorize
    * Description        : This method  returns generates and returns an ERS Authorization. 
    */ 
    @HttpGet
    global static void getERSAuthorize(){
        
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        response.addHeader('Content-Type', 'application/json');
        
        String strjson;
        String membershipNumber;
        Integer serviceYear;
        Integer serviceMonth;
        Integer serviceDay;
        String sourceClub;
        String memberClub;
        
        try{
            membershipNumber = request.headers.get('mbr_id'); 
            serviceYear  = Integer.valueof(request.params.get('service_year'));
            serviceMonth = Integer.valueof(request.params.get('service_month'));
            serviceDay  = Integer.valueof(request.params.get('service_date'));
            sourceClub = request.params.get('source_clb');
            memberClub = request.params.get('clb_cd');
            system.debug('*********' + membershipNumber);
            system.debug('*********' + serviceYear + serviceMonth + serviceDay);
            system.debug('*********' + '*Source*' + sourceClub + ' ' + '*Target*' + memberClub + ' ' + '*Label*' + Label.FSL_SourceClubCode);
            
            Map<string,string> mapofMemebershiplevels = new Map<string,string>();
            
            for(Membership_Type_Mapping__mdt membeshiptype: [SELECT Id, MasterLabel, Membership_Level__c FROM Membership_Type_Mapping__mdt]){
                mapofMemebershiplevels.put((membeshiptype.MasterLabel).trim().toLowerCase(),membeshiptype.Membership_Level__c);
            }
            system.debug('**mapofMemebershiplevels**' + mapofMemebershiplevels);
            
            
            Map<string,string> mapmetadatacoverage = new Map<string,string>();
            
            for(Membership_Coverage_Metadata__mdt coveragetype: [SELECT Id, MasterLabel, Max_Tow_Miles__c, Membership_Level__c FROM Membership_Coverage_Metadata__mdt]){
                mapmetadatacoverage.put((coveragetype.Membership_Level__c).trim().toLowerCase(),String.valueOf(coveragetype.Max_Tow_Miles__c));
            }
            system.debug('**mapmetadatacoverage**' + mapmetadatacoverage);
            
            Map<string,string> feedbackmessages = new Map<string,string>();
            
            for(Feedback_Message__mdt  feedbackmessage: [SELECT Id, MasterLabel, message__c FROM Feedback_Message__mdt ]){
                feedbackmessages.put(feedbackmessage.MasterLabel,feedbackmessage.message__c);
            }
            system.debug('**feedbackmessages**' + feedbackmessages);
            
            Map<String,String> params = new Map<String,String>();
            params.put('memberId', membershipNumber);
                  
            //Refresh Entitlements - Always In Territory 
            ACG_GlobalSearchController.Results memberDetails;
            
            if(memberClub == Label.FSL_SourceClubCode){
                
                Date serviceDate = Date.newInstance(serviceYear,serviceMonth,serviceDay);
                ServiceContract  objSc;
                if (!Test.isRunningTest())  {
                    memberDetails = ACG_GlobalSearchController.invokeMembershipAPIs('lookup', params, 'ERSINB');
                }
                if(!Test.isRunningTest() && memberDetails.custMessage == 'ERSINB') {
                    response.statusCode =404;
                    String message = 'Member ID not found';
                    strjson = generateErrorResponse('-9',message,membershipNumber );
                }
                else {
                    if(memberDetails != null && memberDetails.contract != null) {
                    objSc = getServiceContractDetails(membershipNumber, date.parse(memberDetails.contract.contractEndDate), date.parse(memberDetails.contract.contractStartDate));
                }
                else {
                    objSc = getServiceContractDetails(membershipNumber, Date.today().addDays(10), Date.today().addDays(-100));
                }
                //Contract data for InTerritory, entitlement data for outside territory
                system.debug('****objSc*****' + objSc);
                
                Boolean hasServiceContract = FALSE;
                if(objSc != null){
                    hasServiceContract = TRUE;
                }else{
                    hasServiceContract = FALSE;
                }
                
                
                Feedback__c objAuth = new Feedback__c();
                
                String message;
                String memberlevel;
                String towMiles;
                
                if(hasServiceContract){
                    if(objSc.AAA_ACA_Membership_Coverage_Level__c != null){
                        memberlevel = mapofMemebershiplevels.get((objSc.AAA_ACA_Membership_Coverage_Level__c).trim().toLowerCase());
                    }
                    
                    if(objSc.AAA_ACA_Membership_Coverage_Level__c != null){
                        towMiles = mapmetadatacoverage.get((objSc.AAA_ACA_Membership_Coverage_Level__c).trim().toLowerCase());
                    }
                    
                    system.debug('****memberlevel*****' + memberlevel ) ;
                    system.debug('****objSc.AAA_ACA_Membership_Status__c*****' + objSc.AAA_ACA_Membership_Status__c);
                    system.debug('****objSc.EndDate*****' + objSc.EndDate);
                    system.debug('****objSc.AAA_Total_of_Calls_Allowed__c*****' + objSc.AAA_Total_of_Calls_Allowed__c);
                    system.debug('****objSc.AAA_Total_of_Calls_Consumed__c*****' + objSc.AAA_Total_of_Calls_Consumed__c);
                    
                    
                    if(objSc.AAA_ACA_Membership_Status__c == AAA_CallIntakeUtils.MEMBER_STATUS_ACTIVE && objSc.EndDate >= serviceDate){
                        if(objSc.AAA_Total_of_Calls_Allowed__c > objSc.AAA_Total_of_Calls_Consumed__c + objSc.AAA_Total_of_Reciprocals__c){
                            
                            if(!Test.isRunningTest() && memberDetails.contract.sameDayService ==  false){
                                //same day service
                                memberlevel = 'C';
                                message = feedbackmessages.get('SAMEDAYSERVICE');
                            }else{
                                //happy path
                                //level = objSc.AAA_ACA_Membership_Coverage_Level__c ;
                                message = 'Good for Service';
                            }
                        }else{
                            //All Calls Consumed
                            memberlevel = 'C' ;
                            message = feedbackmessages.get('ALLCALLCONSUMED');
                        }
                    }
                    else if (objSc.AAA_ACA_Membership_Status__c == AAA_CallIntakeUtils.MEMBER_STATUS_PENDING) {
                        if (objSc.EndDate >= serviceDate) {
                            if (objSc.AAA_Total_of_Calls_Allowed__c == 0 || objSc.AAA_Total_of_Calls_Allowed__c == null) {
                                memberlevel = 'C';
                                message = feedbackmessages.get('CALLSALLOWED0');
                            } else if (objSc.AAA_Total_of_Calls_Allowed__c <= objSc.AAA_Total_of_Calls_Consumed__c + objSc.AAA_Total_of_Reciprocals__c) {
                                // All Calls Consumed for Pending Status
                                memberlevel = 'C';
                                message = feedbackmessages.get('ALLCALLCONSUMED');
                            } else if (objSc.AAA_Total_of_Calls_Allowed__c > objSc.AAA_Total_of_Calls_Consumed__c + objSc.AAA_Total_of_Reciprocals__c) {
                                // Happy path: calls remaining
                                message = 'Good for Service';
                            }
                        } else if (objSc.EndDate < serviceDate) {
                            memberlevel = 'C';
                            message = feedbackmessages.get('ENDDATEPASSED');
                        }
                    }
                    // Ensure Cancelled members always get 'C'
                    else if (objSc.AAA_ACA_Membership_Status__c == AAA_CallIntakeUtils.MEMBER_STATUS_CANCELLED) {
                        memberLevel = 'C';
                        message = feedbackMessages.get('CANCELLED') ?? feedbackMessages.get('CANCELED');
                        towMiles = '0';  // No coverage for cancelled members
                    }
                }else {
                    memberLevel = 'X';  // No valid service contract
                    message = feedbackMessages.get('CANCELLED') ?? feedbackMessages.get('CANCELED');
                    towMiles = '0';
                    Account objAcc = getMemberDetails(membershipNumber);
                    system.debug('objAccSc' + objAcc);
                }  
                system.debug('****memberlevel*****' + memberlevel ) ;
                system.debug('****message*****' + message ) ;
                    
                    if (memberlevel == 'X') {
                        // Set status to 'Closed' when memberlevel is 'X'
                        objAuth = createFeedbackRecord(objSc, membershipNumber, sourceClub, serviceDate, 'Outgoing Authorization', 'Closed', memberlevel, towMiles);
                    } else if (sourceClub == '240' && memberClub == '240') {
                        // Set status to 'Closed' if sourceClub and memberClub are both '240'
                        objAuth = createFeedbackRecord(objSc, membershipNumber, sourceClub, serviceDate, 'Outgoing Authorization', 'Closed', memberlevel, towMiles);
                    } else {
                        // Default case: Set status to 'Open'
                        objAuth = createFeedbackRecord(objSc, membershipNumber, sourceClub, serviceDate, 'Outgoing Authorization', 'Open', memberlevel, towMiles);
                    }

                    system.debug('****objAuth*****' + objAuth);
                    
                if(objAuth.Authorization_Code__c!=null){
                    
                    response.statusCode =ACG_ConstantsClass.STATUS_CODE_SUCCESS;
                    
                    INTERSAuthorize_ResponseSuccess respBody = new INTERSAuthorize_ResponseSuccess();
                    strjson=generateSuccessResponse(objAuth.Authorization_Code__c, objAuth.Authorization_Level__c,objAuth.Long_Tow_Miles__c, objAuth.Member_ID__c, message, 0 );
                    system.debug('***respBody***' + strjson );
                } else{
                    system.debug('****Exception - No Authorization Code Generated*****' );
                    message = 'Internal Server Error - No Authorization Code Generated';
                    strjson = generateErrorResponse('500',message,membershipNumber );
                    system.debug('***strjson***' + strjson );
                    }
                }
                
                response.responseBody = Blob.valueOf(strjson);
                FSL_ApplicationLogCreator.integrationLog (JSON.serialize(request.params),strjson,'ERSAuthorize API','ERSAuthorize',false,'',null);
            }else{
                system.debug('****Incorrect Club Code - Exception Thrown400*****');
                response.statusCode =400;
                String message = 'Internal Server Error - Incorrect Club Code';
                strjson = generateErrorResponse('400',message,membershipNumber );
                system.debug('***strjson***' + strjson );
                response.responseBody = Blob.valueOf(strjson);
                FSL_ApplicationLogCreator.integrationLog (JSON.serialize(request.params),strjson,'ERSAuthorize API','ERSAuthorize',false,'',null);
            }
        } 
        catch (AuraHandledException e) {
            //since the child throws AuraHandledException, catch it here, maybe check what the exception is, then do
            system.debug('@@@@@ line 197 Catching Aura Exception @@@@@');
        }
        Catch(Exception e){
            system.debug('****General Exception*****' + e.getLineNumber() + ' ' + e.getMessage());
            response.statusCode =400;
            String message = 'Internal Server Error' + e.getStackTraceString() +'Line Number: '+e.getLineNumber()+''+e.getMessage();
            strjson = generateErrorResponse('400',message,membershipNumber );
            system.debug('***strjson***' + strjson );
            response.responseBody = Blob.valueOf(strjson);
            FSL_ApplicationLogCreator.integrationLog (JSON.serialize(request.params),strjson,'ERSAuthorize API','ERSAuthorize',false,'',null);
        }
    }
    
    public static ServiceContract getServiceContractDetails(String membershipNumber, Date eDate, Date sDate){
        List<ServiceContract> lstServiceContract= new List<ServiceContract>();
        if(!String.isEmpty(membershipNumber)){
            /*lstServiceContract = [SELECT Id, AAA_Total_of_Calls_Allowed__c,AAA_Total_of_Calls_Consumed__c,AAA_Same_Day_Service__c,EndDate,  AAA_ACA_Membership16ID__c,AccountId, AAA_ACA_Membership_Coverage_Level__c,AAA_ACA_Member_Status__c,AAA_ACA_Membership_Status__c
                                  FROM ServiceContract WHERE AAA_ACA_Membership16ID__c =: membershipNumber LIMIT 1];*/
            lstServiceContract = [Select Id, AAA_ACA_Membership_Type__c,AAA_ACA_Membership16ID__c, AccountId, 
            StartDate, EndDate, AAA_ACA_Member_Status__c, AAA_ACA_MembershipID__c,parentServiceContractId,
            AAA_ACA_Membership_Status__c, AAA_ACA_Membership_Coverage_Level__c,
            AAA_Total_of_Calls_Allowed__c,AAA_Total_of_Calls_Remaining__c,AAA_Total_of_Calls_Consumed__c,AAA_Total_of_Reciprocals__c   
            from ServiceContract where 
                AAA_ACA_Membership16ID__c =: membershipNumber
                AND (EndDate =: eDate OR StartDate =: sDate)
            ];                              
        }
        if(!lstServiceContract.isempty()){
            return lstServiceContract[0];
        } else {
            return null;
        }
    }//End of getServiceContractDetails
    
    public static String generateErrorResponse(String code, String message, String membershipnumber ){
        String jsonresponse = '';
        INTERSAuthorize_ResponseError errorresp = new INTERSAuthorize_ResponseError();
        errorresp.errorCode = code;
        errorresp.errorMessage = message;
        errorresp.transactionId = membershipNumber;
        errorresp.timeStamp = String.valueOf(Datetime.now());
        jsonresponse = JSON.serialize(errorresp);
        return jsonresponse;
    }
    
    public static String generateSuccessResponse(String authCode, String level, String towMiles, String membrId, String message, Integer returnCode ){
        String jsonresponse = '';
        INTERSAuthorize_ResponseSuccess successResp = new INTERSAuthorize_ResponseSuccess();
        successResp.code = authCode;
        successResp.level = level;
        successResp.long_tow_kilometers = '0';
        successResp.long_tow_miles = towMiles;
        successResp.member_id = membrId;
        successResp.message = message;
        successResp.rental_days = '0';
        successResp.return_cd = returnCode;
        jsonresponse = JSON.serialize(successResp);
        return jsonresponse;
    }
    
    public static Account getMemberDetails(String membershipNumber){
        List<Account> lstAccounts= new List<Account>();
        if(membershipNumber!=null && membershipNumber!=''){
            lstAccounts = [SELECT Id,ACG_AAA_Membership__c,Member_ID__c,Member_Card_Num__pc,AAA_Membership_Level__c,Long_Tow_Miles_Used__c,
                           Long_Tow_Kilometers_Used__c,ACG_Membership_Status__c,Authorize_Code__c,ACG_Entitlements_Used__c,
                           ACG_Entitlements_Allotted__c FROM Account WHERE Member_ID__c =: membershipNumber OR Member_Card_Num__pc =: membershipNumber LIMIT 1];
        }
        return lstAccounts[0];
    }//End of getMemberDetails
    
   public static Feedback__c createFeedbackRecord(ServiceContract sc,String membershipNumber, String sourceClub,Date serviceDate, String type, String Status, String level, String maxTowMiles){
        
        Feedback__c objrec = new Feedback__c();
        if(sc != null){
            objrec.Account__c = sc.AccountId;
            objrec.Member_ID__c = sc.AAA_ACA_Membership16ID__c ;
            objrec.Member_Club__c = sc.AAA_ACA_Membership16ID__c.substring(3,6);
            objrec.Service_Contract__c = sc.Id;
        }else{
            Account objAcc = getMemberDetails(membershipNumber);
            
            if(objAcc != null){
                objrec.Account__c  = objAcc.id;
                objrec.Member_ID__c = objAcc.Member_Card_Num__pc ;
                objrec.Member_Club__c = objAcc.Member_Card_Num__pc.substring(3,6);
            }else{
                system.debug('No Acc No Sc' + membershipNumber);
            }
            
            
        }
        
        objrec.Source_Club__c = sourceClub; 
        objrec.Service_Date__c = serviceDate;
        objrec.Type__c = type;
        objrec.Status__c  = status;
        objrec.Authorization_Level__c   = level;
        objrec.Rental_Days__c = '0';
        objrec.Long_Tow_Kilometers__c = '0';
        objrec.Long_Tow_Miles__c = maxTowMiles; //ToTest
        if(objrec!=null){
            insert objrec;
        }
        
        if(objrec.Id!=null){
            objrec = [SELECT Id,Account__c,Member_ID__c,Rental_Days__c,Long_Tow_Kilometers__c,Long_Tow_Miles__c,Member_Club__c,Source_Club__c,Service_Date__c,Service_Contract__c,Type__c,Status__c,Authorization_Level__c
                      ,Auth_Autonumber__c FROM Feedback__c WHERE Id=: objrec.Id];
            objrec.Authorization_Code__c = objrec.Auth_Autonumber__c;
            update objrec;
        }
        return objrec;
    }
    
    global class INTERSAuthorize_ResponseSuccess{
        public String code{get;set;} //88573873
        public String level{get;set;} //E
        public String long_tow_kilometers{get;set;}//100
        public String long_tow_miles{get;set;}//100
        public String member_id{get;set;}//69773315
        public String message {get;set;}//string
        public String rental_days{get;set;}//30
        public Integer return_cd{get;set;}//0
    }//END of INTERSAuthorize_Response
    
    global class INTERSAuthorize_ResponseError{
        public String errorCode{get;set;} //4xx
        public String errorMessage{get;set;} //Error message
        public String transactionId{get;set;}//9bdc1bd3-271d-4f91-8dc1-f1d796765a85
        public String timeStamp{get;set;}//2022-02-18T15:44:06.858Z
    }//END of INTERSAuthorize_Response
    
    
    
}