unpackaged/main/default/objects/Account/fields/ACG_AAA_Membership__c.field-meta.xml
<CustomField>
    <fullName>ACG_AAA_Membership__c</fullName>
    <externalId>true</externalId>
    <label>AAA Membership #</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>Facility_ID__c</fullName>
    <externalId>true</externalId>
    <label>Facility ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Member_Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Member_Club_Code__c</fullName>
    <label>Member Club Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/ACG_AAA_Membership__c.field-meta.xml
<CustomField>
    <fullName>ACG_AAA_Membership__c</fullName>
    <formula>Account.ACG_AAA_Membership__c</formula>
    <inlineHelpText>AAA Membership # of related Account.</inlineHelpText>
    <label>AAA Membership #</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Provider_Comments__c.field-meta.xml
<CustomField>
    <fullName>ACG_Provider_Comments__c</fullName>
    <label>Provider Comments</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ERS_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>ERS_Event_Type__c</fullName>
    <label>ERS Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_ERS_Event_Types</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Call Adjustments</relationshipLabel>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <formula>FSL_Work_Order__r.ServiceTerritory.Facility_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Facility Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/RAP_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>RAP_Case_Number__c</fullName>
    <label>RAP Case Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ACG_AAA_Membership__c.field-meta.xml
<CustomField>
    <fullName>ACG_AAA_Membership__c</fullName>
    <formula>Account.ACG_AAA_Membership__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AAA Membership #</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <description>Contact Member</description>
    <label>Member</label>
</RecordType>

unpackaged/main/default/objects/ERS_Payment__c/ERS_Payment__c.object-meta.xml
<CustomObject>
    <label>ERS Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERS Payments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ERS_Payment__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accident Assist</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>RAP</fullName>
            </value>
            <value>
                <fullName>Tow To Go</fullName>
            </value>
            <value>
                <fullName>Dealership</fullName>
            </value>
            <value>
                <fullName>Motor Club</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>AAA Member - Technical Issue</fullName>
            </value>
            <value>
                <fullName>AAA PROMise</fullName>
            </value>
            <value>
                <fullName>CAA RAP</fullName>
            </value>
            <value>
                <fullName>Essential Workers</fullName>
            </value>
            <value>
                <fullName>Hospital Delivery</fullName>
            </value>
            <value>
                <fullName>RAP Manual</fullName>
            </value>
            <value>
                <fullName>Courtesy International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ERS_Payment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ERS Payments</relationshipLabel>
    <relationshipName>ERS_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ERS_Payment__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ERS Payments (Account)</relationshipLabel>
    <relationshipName>ERS_PaymentFacility</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ERS_Payment__c/fields/Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>Facility_ID__c</fullName>
    <formula>Facility__r.Facility_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Facility ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ERS_Payment__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>ERS Payments</relationshipLabel>
    <relationshipName>ERS_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/FSL_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SLI - {0000}</displayFormat>
        <label>SLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <formula>Work_Order__r.ServiceTerritory.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Facility</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Override_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Override_Pricing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Pricing</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Product2.ProductCode</field>
            <operation>notEqual</operation>
            <value>CE</value>
        </filterItems>
        <filterItems>
            <field>Product2.ProductCode</field>
            <operation>notEqual</operation>
            <value>CT</value>
        </filterItems>
        <filterItems>
            <field>Product2.Name</field>
            <operation>notEqual</operation>
            <value>CT - Calculated Tow</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Line Items (Product)</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Quantity</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Integration_Settings__c/fields/Header_Value__c.field-meta.xml
<CustomField>
    <fullName>Header_Value__c</fullName>
    <label>Header Value</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Enable_Calculate_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Enable_Calculate_Mileage__c</fullName>
    <label>Enable Calculate Mileage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>From Service Territory</fullName>
            </value>
            <value>
                <fullName>From Driver Location</fullName>
            </value>
            <value>
                <fullName>Not Calculated Facility</fullName>
                <default>true</default>
                <label>Not Calculated Facility</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <label>Facility Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/recordTypes/Facility_Territory.recordType-meta.xml
<RecordType>
    <fullName>Facility_Territory</fullName>
    <active>true</active>
    <description>Territory that handles all types of services</description>
    <label>Facility Territory</label>
</RecordType>

unpackaged/main/default/objects/WorkOrder/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Cleared_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Timestamp__c</fullName>
    <label>Cleared Timestamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Clearing_Code__c.field-meta.xml
<CustomField>
    <fullName>Clearing_Code__c</fullName>
    <label>Clearing Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clear_Codes</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Dispatched_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Dispatched_Timestamp__c</fullName>
    <label>Dispatched Timestamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Enroute_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Enroute_Timestamp__c</fullName>
    <label>En Route Timestamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <formula>ServiceTerritory.Facility_Number__c</formula>
    <label>Facility Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/In_Tow_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>In_Tow_Timestamp__c</fullName>
    <label>In Tow Timestamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Member_Account__c.field-meta.xml
<CustomField>
    <fullName>Member_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Members)</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/On_Location_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>On_Location_Timestamp__c</fullName>
    <label>On Location Timestamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/RAP_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>RAP_Case_Number__c</fullName>
    <label>RAP Case Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Spotted_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Spotted_Timestamp__c</fullName>
    <description>Captures the timestamp when the WorkOrder enters the spotted</description>
    <label>Spotted Timestamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Tow.recordType-meta.xml
<RecordType>
    <fullName>Tow</fullName>
    <active>true</active>
    <label>Tow</label>
</RecordType>

unpackaged/main/default/globalValueSets/Case_ERS_Event_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accident Assist</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial</fullName>
    </customValue>
    <customValue>
        <fullName>Member</fullName>
    </customValue>
    <customValue>
        <fullName>RAP</fullName>
    </customValue>
    <customValue>
        <fullName>Tow To Go</fullName>
    </customValue>
    <customValue>
        <fullName>Dealership</fullName>
    </customValue>
    <customValue>
        <fullName>Motor Club</fullName>
    </customValue>
    <customValue>
        <fullName>Private</fullName>
    </customValue>
    <customValue>
        <fullName>CALL_MOVE</fullName>
        <label>Call Move</label>
    </customValue>
    <customValue>
        <fullName>DRR</fullName>
    </customValue>
    <customValue>
        <fullName>AAA Member - Technical Issue</fullName>
    </customValue>
    <customValue>
        <fullName>AAA PROMise</fullName>
    </customValue>
    <customValue>
        <fullName>CAA RAP</fullName>
    </customValue>
    <customValue>
        <fullName>Courtesy International</fullName>
    </customValue>
    <customValue>
        <fullName>Essential Workers</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>RAP Manual</fullName>
    </customValue>
    <customValue>
        <fullName>SAIVR</fullName>
    </customValue>
    <description>To be assigned as Picklist values for Case.ACG_ERS_Event_Type and WorkOrder.Call_Type__c</description>
    <masterLabel>Case_ERS Event Types</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Clear_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>8X</fullName>
    </customValue>
    <customValue>
        <fullName>BK</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
    </customValue>
    <customValue>
        <fullName>M8</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <customValue>
        <fullName>MX</fullName>
    </customValue>
    <customValue>
        <fullName>N1</fullName>
    </customValue>
    <customValue>
        <fullName>N2</fullName>
    </customValue>
    <customValue>
        <fullName>N3</fullName>
    </customValue>
    <customValue>
        <fullName>N4</fullName>
    </customValue>
    <customValue>
        <fullName>N5</fullName>
    </customValue>
    <customValue>
        <fullName>N9</fullName>
    </customValue>
    <customValue>
        <fullName>NX</fullName>
    </customValue>
    <customValue>
        <fullName>RR</fullName>
    </customValue>
    <customValue>
        <fullName>XX</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>2A</fullName>
        <isActive>false</isActive>
        <label>2A</label>
    </customValue>
    <customValue>
        <fullName>XE</fullName>
        <isActive>false</isActive>
        <label>XE</label>
    </customValue>
    <customValue>
        <fullName>SF</fullName>
        <isActive>false</isActive>
        <label>SF</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <isActive>false</isActive>
        <label>SD</label>
    </customValue>
    <customValue>
        <fullName>PR</fullName>
        <isActive>false</isActive>
        <label>PR</label>
    </customValue>
    <customValue>
        <fullName>NG</fullName>
        <isActive>false</isActive>
        <label>NG</label>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
        <isActive>false</isActive>
        <label>NE</label>
    </customValue>
    <customValue>
        <fullName>M9</fullName>
        <isActive>false</isActive>
        <label>M9</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <isActive>false</isActive>
        <label>CA</label>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
        <isActive>false</isActive>
        <label>BN</label>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
        <isActive>false</isActive>
        <label>BM</label>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
        <isActive>false</isActive>
        <label>AD</label>
    </customValue>
    <customValue>
        <fullName>2T</fullName>
        <isActive>false</isActive>
        <label>2T</label>
    </customValue>
    <masterLabel>Clear Codes</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/INTNationalRBPAPI_Test.cls
/**** Apex Class Name    :    INTNationalRBPAPI_Test
    * Description        :    Test class for INTNatioanlRBPAPI class  
    * Modification Log   :    
    * ---------------------------------------------------------------------------
    * Developer                   Date                   Description
    * ---------------------------------------------------------------------------
    * Dhruv               		Aug 16 2021             Created
*********************************************************************************/
@isTest
public class INTNationalRBPAPI_Test {
    @testSetup 
    static void setup() {
        insert new Integration_Settings__c(
            Name = 'NationalRBP_API',
            Method__c = 'POST',
            Enpoint_URL__c = 'https://api-qa.national.aaa.com/automotive/services/sf/v1/requests/close',
            Header_Value__c = '[{"key":"Content-Type","value":"application/json"}]'
        );
        
        Integration_Settings__c integrationSetting = ACG_TestDataFactory.createIntegrationSetting(
            'NatioanlRBP_API', 
            'POST', 
            'callout:NatioanlRBP_API', 
            '/callClear', 
            'http://acg-ers-ulra-rbpcallclear-api-dev.us-e1.cloudhub.io/callClear', 
            true
        );

        System.assertEquals(true, integrationSetting.Id != null, 'Error While Creating Record');
        
        insert new Execute_Trigger__c(
            Name = 'Work Order'
        );
        
        Id accountMemberId = 
            Schema.SObjectType.Account
                .getRecordTypeInfosByName()
                .get('ERS Member')
                .getRecordTypeId();
        Id accountfacilityId = 
            Schema.SObjectType.Account
                .getRecordTypeInfosByName()
                .get('Facility')
                .getRecordTypeId();
        Id MEMBER_ACCOUNT_RECORDTYPEID = ACG_UtilityClass.MEMBER_RECORDTYPE_ID;
        Account FacilityAcc = ACG_TestDataFactory.createAccount(
            accountfacilityId,'FacilityUser', true
        );

        List<Account> lstMemberAcc = ACG_TestDataFactory.createAccounts(MEMBER_ACCOUNT_RECORDTYPEID, 1 , false, true);
        lstMemberAcc[0].ACG_AAA_Membership__c='123';
        lstMemberAcc[0].Email_Type__pc='PERSONAL';
        lstMemberAcc[0].Fax='2222222222';
        lstMemberAcc[0].Phone='2222222222';
        lstMemberAcc[0].PersonHomePhone='2222222222';
        lstMemberAcc[0].PersonMobilePhone='2222222222';
        lstMemberAcc[0].Member_Club_Code__c='006';
        insert lstMemberAcc;
        
        Id towID = 
            Schema.SObjectType.WorkOrder
                .getRecordTypeInfosByName()
                .get('Tow')
                .getRecordTypeId();

        WorkOrder wo = ACG_TestDataFactory.createWorkOrder(FacilityAcc.Id, lstMemberAcc[0].Id, towID, false);
        wo.Accountid = FacilityAcc.Id;
        wo.member_account__c = lstMemberAcc[0].Id;
        wo.RAP_Case_Number__c = '123456';
        insert wo;

        Product2 twProd = new Product2(
            Family = 'Service Item',
            IsActive = true,
            Name = 'TW-Tow',
            ProductCode = 'TW',
            QuantityUnitOfMeasure = 'Each'
        );
        insert twProd;
        
        insert new FSL_Service_Line_Item__c(
            Work_Order__c = wo.Id,
            Product__c = twProd.Id,
            Unit__c = 23.23,
            Cost__c = 23.23,
            Override_Pricing__c = false
        );

        Id facilityRecordTypeId  = EP.getRecordTypeId(Account.SObjectType, 'Facility');
        Id callAdjustmentRecTypeId  = EP.getRecordTypeId(Case.SObjectType, 'ACG_Call_Adjustment');
        
        List<Account> lstAccounts = new List<Account>();
        Account objFacility = ACG_TestDataFactory.createAccounts(facilityRecordTypeId, 1, false, false)[0];
        objFacility.Facility_ID__c = '9131';
        lstAccounts.add(objFacility);
        Account objFacility1 = ACG_TestDataFactory.createAccounts(facilityRecordTypeId, 1, false, false)[0];
        objFacility1.Facility_ID__c = 'CR567';
        lstAccounts.add(objFacility1);
        insert lstAccounts;
        
        List<Case> callAdjustments = new List<Case>();
        Case objCallAdjustment = ACG_TestDataFactory.createcase(callAdjustmentRecTypeId, 'Pending', 'Chat', false);
        objCallAdjustment.ACG_Provider_Comments__c = 'Test';
        objCallAdjustment.Facility__c = objFacility1.Id;
        callAdjustments.add(objCallAdjustment);
        Case objCallAdjustment1 = ACG_TestDataFactory.createcase(callAdjustmentRecTypeId, 'Pending', 'Chat', false);
        objCallAdjustment1.ERS_Event_Type__c = 'Accident Assist';
        objCallAdjustment1.ACG_Provider_Comments__c = 'Test';
        objCallAdjustment1.Facility__c = objFacility1.Id;
        callAdjustments.add(objCallAdjustment1);
        insert callAdjustments;
        
        Id EPRecordType = 
            Schema.SObjectType.ERS_Payment__c
                .getRecordTypeInfosByName()
                .get('Call')
                .getRecordTypeId();

        ERS_Payment__c ObjEP = ACG_TestDataFactory.createERSPayment(EPRecordType, false);
        ObjEP.Work_Order__c = wo.Id;
        ObjEP.Case__c = objCallAdjustment.Id;
        ObjEP.Facility__c = objFacility.Id;
        insert ObjEP;
        
        Product2 product= ACG_TestDataFactory.createProduct('Test', 'P1', true, true);
        ERS_Payment_Line_Item__c objEPLI= ACG_TestDataFactory.createERSPaymentLineItem(ObjEP.Id, product.Id, 10, true);
        
        insert new FeedItem(
            parentId = wo.Id,
            Body = 'test'
        );
        
        insert new WorkOrderHistory(
            WorkOrderId = wo.Id,
            Field = 'Status'
        );
    }
    
    @isTest 
    static void getRBPCallout() {
        String res = '{"responseHeaders": {"tranId": "8f03b3b0-4918-11ec-aeac-0a8918c0875d","tranCode": 200,"tranStatus": "E","timeStamp": "2021-11-19T04:10:42.1-05:00","tranStatusDescription": "Invalid callKey and try again."}}';

        Test.setMock(HttpCalloutMock.class, new RestServiceMock_TEST(res)); 

        INTNationalRBPAPIRequest_Wrapper req = new INTNationalRBPAPIRequest_Wrapper();
        req.comments = new List<INTNationalRBPAPIRequest_Wrapper.Comment>();
        INTNationalRBPAPIRequest_Wrapper.Comment comment = new INTNationalRBPAPIRequest_Wrapper.Comment();
        comment.Contact = new INTNationalRBPAPIRequest_Wrapper.Contact();
        comment.Contact.phones=new List<INTNationalRBPAPIRequest_Wrapper.Phone>();
        comment.Contact.phones.add(new INTNationalRBPAPIRequest_Wrapper.Phone());
        comment.Contact.Emails = new List<INTNationalRBPAPIRequest_Wrapper.Email>();
        comment.Contact.Emails.add(new INTNationalRBPAPIRequest_Wrapper.Email());
        req.comments.add(comment);
        req.callKey = '1223';

        Test.startTest(); 
        Map<String, Object> respMap = (Map<String, Object>) INTNationalRBPAPI.sendToStatusToRBP(req, null);

        HttpResponse resp = (HttpResponse) respMap.get('resp');

        System.assertEquals(200, resp.getStatusCode(), 'Success');
        Test.stopTest();
    }

    @isTest 
    static void getErrorLog() {
        String res = '{"responseHeaders": {"tranId": "8f03b3b0-4918-11ec-aeac-0a8918c0875d","tranCode": 400,"tranStatus": "E","timeStamp": "2021-11-19T04:10:42.1-05:00","tranStatusDescription": "Invalid callKey and try again."}}';
        
        Test.setMock(HttpCalloutMock.class, new RestServiceMock_TEST(res,500,'Internal Server Error')); 

        INTNationalRBPAPIRequest_Wrapper req=new INTNationalRBPAPIRequest_Wrapper();
        req.callKey='006-20220311-0-123456';

        Test.startTest();
        Map<String, Object> respMap = (Map<String, Object>) INTNationalRBPAPI.sendToStatusToRBP(req, null);

        HttpResponse resp = (HttpResponse) respMap.get('resp');
        Test.stopTest();
        
        System.assertEquals(500, resp.getStatusCode(), 'Internal Server Error Occured');
    }

    @isTest 
    static void getExceptionLog() {
        String res = '';

        Test.setMock(HttpCalloutMock.class, new RestServiceMock_TEST(res, 500, 'Internal Server Error')); 

        Test.startTest();
        INTNationalRBPAPIRequest_Wrapper req = new INTNationalRBPAPIRequest_Wrapper();
        req.callKey='006-20220311-0-123456';
        Map<String, Object> respMap = (Map<String, Object>) INTNationalRBPAPI.sendToStatusToRBP(req, null);
        HttpResponse resp = (HttpResponse) respMap.get('resp');

        System.assertEquals(500, resp.getStatusCode(), 'Internal Server Error Occured');
        Test.stopTest();
    }
    
    @isTest 
    static void getCatchException() {
        String res = '[{"responseHeaders": {"tranId": "8f03b3b0-4918-11ec-aeac-0a8918c0875d","tranCode": 200,"tranStatus": "E","timeStamp": "2021-11-19T04:10:42.1-05:00","tranStatusDescription": "Invalid callKey and try again."}}]';
        
        Test.setMock(HttpCalloutMock.class, new RestServiceMock_TEST(res, 500, 'Internal Server Error')); 
        
        Test.startTest(); 
        INTNationalRBPAPIRequest_Wrapper req = new INTNationalRBPAPIRequest_Wrapper();
        req.callKey='006-20220311-0-123456';
        Map<String, Object> respMap = (Map<String, Object>) INTNationalRBPAPI.sendToStatusToRBP(req, null);
        HttpResponse resp = (HttpResponse) respMap.get('resp');

        System.assertEquals(500, resp.getStatusCode(), 'Internal Server Error Occured');
        Test.stopTest();
    }
    
    @isTest 
    static void getRBPRequest() {
        Set<Id> woIdSet = new Map<Id, WorkOrder>([SELECT Id FROM WorkOrder LIMIT 1]).keySet();

        Test.startTest(); 
        Map<String, Object> resMap = (Map<String, Object>) INTNationalRBPAPI.createrbprquest(woIdSet);
        List<INTNationalRBPAPIRequest_Wrapper> requestWrapper = (List<INTNationalRBPAPIRequest_Wrapper>) resMap.get('lstRBPReq');
        Test.stopTest();

        System.assertEquals(1, requestWrapper.size(), 'Expected request to be created');
    }

    @isTest
    static void rbpReqStatusTest() {
        RecordType facTerritoryType = [
            SELECT Id 
            FROM RecordType 
            WHERE DeveloperName = 'Facility_Territory' 
            AND SobjectType = 'ServiceTerritory' 
            LIMIT 1
        ];

        OperatingHours opHrs = new OperatingHours(
            TimeZone = 'America/New_York',
            Name = 'Apex Test Time Zone'
        );
        insert opHrs;

        ServiceTerritory fac = new ServiceTerritory(
            Name = 'Apex Test Service Territory',
            RecordTypeId = facTerritoryType.Id,
            OperatingHoursId = opHrs.Id,
            Enable_Calculate_Mileage__c = 'From Service Territory',
            isActive = true,
            Facility_Number__c = 'APEXFAC22',
            City = 'FLUSHING',
            Country = 'United States',
            CountryCode = 'US',
            PostalCode = '01301',
            State = 'NY',
            StateCode = 'NY',
            Street = '86 RIVER ST'
        );
        insert fac;

        WorkOrder wo = [
            SELECT 
                Id,
                ServiceTerritoryId,
                Canceled_Timestamp__c,
                Cleared_Timestamp__c,
                Dispatched_Timestamp__c,
                Enroute_Timestamp__c,
                In_Tow_Timestamp__c,
                On_Location_Timestamp__c,
                Spotted_Timestamp__c
            FROM WorkOrder
            LIMIT 1
        ];
        wo.ServiceTerritoryId = fac.Id;
        wo.Canceled_Timestamp__c = Datetime.now();
        wo.Cleared_Timestamp__c = Datetime.now();
        wo.Dispatched_Timestamp__c = Datetime.now();
        wo.Enroute_Timestamp__c = Datetime.now();
        wo.In_Tow_Timestamp__c = Datetime.now();
        wo.On_Location_Timestamp__c = Datetime.now();
        wo.Spotted_Timestamp__c = Datetime.now();
        update wo;

        Test.startTest(); 
        Map<String, Object> resMap = (Map<String, Object>) INTNationalRBPAPI.createrbprquest(new Set<Id>{wo.Id});
        List<INTNationalRBPAPIRequest_Wrapper> reqWrapList = (List<INTNationalRBPAPIRequest_Wrapper>) resMap.get('lstRBPReq');
        Test.stopTest();

        System.assertEquals(1, reqWrapList.size(), 'Expected request to be created');
        System.assertEquals(7, reqWrapList[0].status.size(), 'Expected status list to be populated');

        Integer statusCount = 0;

        for (INTNationalRBPAPIRequest_Wrapper.Status statusObj : reqWrapList[0].status) {
            String status = statusObj.status;

            if (status == 'SP') {
                statusCount++;
            } else if (status == 'DI') {
                statusCount++;
            } else if (status == 'ER') {
                statusCount++;
            } else if (status == 'OL') {
                statusCount++;
            } else if (status == 'TW') {
                statusCount++;
            } else if (status == 'CL') {
                statusCount++;
            } else if (status == 'CA') {
                statusCount++;
            }
        }

        System.assertEquals(7, statusCount, 'Failed to include Work Order status into request');
    }

    @isTest
    static void gmtConvertTest() {
        Datetime result = INTNationalRBPAPI.convertToGMT(Datetime.now());

        System.assertEquals(true, result != null, 'Failed to convert to GMT.');
    }

    @isTest
    static void prepSLIForRBPTest() {
        Product2 tlProd = new Product2(
            ProductCode = 'TL',
            Name = 'TL',
            Family = 'Service Item'
        );
        insert tlProd;

        WorkOrder wo = new WorkOrder(
            Clearing_Code__c = '01',
            Call_Type__c = 'RAP',
            Resolution_Code__c = 'G201'
        );
        insert wo;
        
        FSL_Service_Line_Item__c tlSLI = new FSL_Service_Line_Item__c(
            Product__c = tlProd.Id,
            Cost__c = 45.45,
            Unit__c = 45.45,
            Charge_to_Account__c = 'B',
            Work_Order__c = wo.Id
        );
        insert tlSLI;

        tlSLI = [
            SELECT
                Id,
                Product_Code__c,
                Total_Price__c,
                Unit__c,
                Charge_to_Account__c
            FROM FSL_Service_Line_Item__c
            WHERE Id = :tlSLI.Id
        ];
        
        INTNationalRBPAPIRequest_Wrapper.providedService result = INTNationalRBPAPI.prepSLIForRBP(
            new Map<String, Object>{
                'unitMap' => new Map<String, String>{
                    'TL' => 'ML'
                },
                'sli' => tlSLI,
                'tCode' => 'T6'
            }
        );

        System.assertEquals(true, result != null, 'Failed to create object');
    }
}