unpackaged/main/default/objects/Account/fields/ACG_Club_Name__c.field-meta.xml
<CustomField>
    <fullName>ACG_Club_Name__c</fullName>
    <label>Club Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ACG_Club__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>AAA Akron Auto Club</fullName>
            </value>
            <value>
                <fullName>AAA Alabama</fullName>
            </value>
            <value>
                <fullName>AAA Alaska</fullName>
            </value>
            <value>
                <fullName>AAA Allegheny</fullName>
            </value>
            <value>
                <fullName>AAA Allied Group, Inc.</fullName>
            </value>
            <value>
                <fullName>AAA Arizona</fullName>
            </value>
            <value>
                <fullName>AAA Auto Club South</fullName>
            </value>
            <value>
                <fullName>AAA Blair County</fullName>
            </value>
            <value>
                <fullName>AAA Blue Grass/Kentucky</fullName>
            </value>
            <value>
                <fullName>AAA Butler County</fullName>
            </value>
            <value>
                <fullName>AAA Carolinas</fullName>
            </value>
            <value>
                <fullName>AAA Central Penn</fullName>
            </value>
            <value>
                <fullName>AAA Central-West Jersey</fullName>
            </value>
            <value>
                <fullName>AAA Cincinnati</fullName>
            </value>
            <value>
                <fullName>AAA Club Partners, Inc.</fullName>
            </value>
            <value>
                <fullName>AAA Colorado</fullName>
            </value>
            <value>
                <fullName>AAA East Central</fullName>
            </value>
            <value>
                <fullName>AAA East Penn</fullName>
            </value>
            <value>
                <fullName>AAA Florida/Louisana/Miss</fullName>
            </value>
            <value>
                <fullName>AAA Hawaii</fullName>
            </value>
            <value>
                <fullName>AAA Hoosier Motor Club</fullName>
            </value>
            <value>
                <fullName>AAA Hudson Valley</fullName>
            </value>
            <value>
                <fullName>AAA Huntingdon County</fullName>
            </value>
            <value>
                <fullName>AAA Iowa</fullName>
            </value>
            <value>
                <fullName>AAA Kansas</fullName>
            </value>
            <value>
                <fullName>AAA Kentucky</fullName>
            </value>
            <value>
                <fullName>AAA Lancaster County</fullName>
            </value>
            <value>
                <fullName>AAA Lehigh Valley</fullName>
            </value>
            <value>
                <fullName>AAA Lewistown</fullName>
            </value>
            <value>
                <fullName>AAA Louisiana</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Club_Code__c</fullName>
    <label>Club Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Club_Name_Mappings__mdt/Club_Name_Mappings__mdt.object-meta.xml
<CustomObject>
    <label>Club Name Mappings</label>
    <pluralLabel>Club Name Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/PersonAccount/recordTypes/ACG_Customer.recordType-meta.xml
<RecordType>
    <fullName>ACG_Customer</fullName>
    <active>true</active>
    <description>A customer can be a member, non-member, past traveler or a prospect.</description>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

unpackaged/main/default/objects/ServiceContract/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/ServiceContract/recordTypes/Member.recordType-meta.xml
<RecordType>
    <fullName>Member</fullName>
    <active>true</active>
    <label>Member</label>
</RecordType>

unpackaged/main/default/classes/ACG_GlobalSearchControllerHelper.cls
/*
``@description: helper class for ACG_GlobalSearchController class
  @date: August 23, 2021
  @author: Deloitte Consulting
*/
public inherited sharing class ACG_GlobalSearchControllerHelper {

    //private static final Id MEMBER_RECORD_TYPE_ID = ACG_UtilityClass.MEMBER_RECORDTYPE_ID;
	//private static final Id Customer_RECORD_TYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ACG_Customer').getRecordTypeId();	//ERS
    private static final Id MEMBERSC_RECORD_TYPE_ID = Schema.SObjectType.ServiceContract.getRecordTypeInfosByDeveloperName().get('Member').getRecordTypeId();	//Member SC
	private static final Id HOUSEHOLDSC_RECORD_TYPE_ID = Schema.SObjectType.ServiceContract.getRecordTypeInfosByDeveloperName().get('Household').getRecordTypeId();	//Household SC
    @testVisible
    private static FSL_Account.IFactory accountFactory = new FSL_Account.Factory();
    
    //ERS-229202, //ERS-230821
    public static ACG_GlobalSearchController.MbrValAPIWrapper performUpsertOnLookupRecord(String sMemberId, INTMembershipLookupResponse_Wrapper response, String guid) {
        ACG_GlobalSearchController.MbrValAPIWrapper mvWrapper = new ACG_GlobalSearchController.MbrValAPIWrapper();

        FSL_Account.MembershipInformationParser parser = accountFactory.createMembershipInformationParser();
        FSL_Account.IAccountService service = accountFactory.createService();
        
        FSL_Account.MembershipInformation info = parser.parse( response.customers.customer[0] );
        INTMembershipLookupResponse_Wrapper.Customer customer = response.customers.customer[0];
        transformCountryCode(info);
        List<Club_Name_Mappings__mdt> records = [SELECT Id,Club_Name__c,Club_Code__c 
                                                FROM Club_Name_Mappings__mdt 
                                                WHERE Club_Code__c = :info.clubCode];
        if( records?.size() > 0 ) {
            string mdtRec = records[0].Club_Name__c;
            for(Schema.PicklistEntry ple1 : Account.ACG_Club_Name__c.getDescribe().getPicklistValues()) {
                if( mdtRec == ple1.getValue() && ple1.isActive() ) {
                    info.clubName = ple1.getValue();
                    break;
                }
            }
        }
        //Find Existing or Create new PersonAccount based on the information received in the lookup response
        List<Account> accounts = service.getOrCreateMemberPersonAccounts( new List<FSL_Account.MembershipInformation>{ info } );
        mvWrapper.recordId = accounts[0].Id;
        System.debug('@@@ Accounts --> ' + accounts[0].Id) ; 
        System.debug('@@@ customer --> ' + customer) ; 
        System.debug('@@@ customer.isLocalClub --> ' + customer.isLocalClub) ; 

        if(accounts.size() > 0 && !customer.isLocalClub){
            AAA_FeedbackIncomingAuthUtil.createOpenFeedback(customer, accounts[0].Id);
        }
        system.debug('@@@@ customer @@@@'+customer);
        //create Service Contract record only if it is Local Club
        if(accounts.size() > 0 && customer.isLocalClub) {
            AAA_ServiceContractUtility.ContractInformationWrapper cWrap = AAA_ServiceContractUtility.getOrCreateMembershipContract( response.customers.customer[0], system.Now(), accounts[0].Id);
            mvWrapper.inMemberContract = cWrap.membershipContract;
            mvWrapper.showImpairment = cWrap.showImpairment;
            mvWrapper.impairmentType = cWrap.impairmentType;
            mvWrapper.isLocalclub = customer.isLocalClub;
            mvWrapper.sameDayService = customer.entitlement.sameDayService;
            mvWrapper.accountId = accounts[0].Id;
            system.debug('@@@@ mvWrapper.inMemberContract'+ mvWrapper.inMemberContract);
            system.debug('@@@@ mvWrapper.showImpairment'+ mvWrapper.showImpairment);
            system.debug('@@@@ mvWrapper.impairmentType'+ mvWrapper.impairmentType);
            if(cWrap.membershipContract != null && mvWrapper.impairmentType == null) {
                mvWrapper.impairmentType = new ImpairmentsHelper.Factory().createService().extractMembershipImpairmentForLocal(customer,cWrap);
            }
            system.debug('@@@@ mvWrapper.impairmentType'+ mvWrapper.impairmentType);
        }else if(!customer.isLocalClub){
            ACG_GlobalSearchController.EntitlementsWrapper ent = new ACG_GlobalSearchController.EntitlementsWrapper();
            mvWrapper.impairmentType = response.impairmentType; 
            if(response.impairmentType != null) {
                mvWrapper.showImpairment = true;
            }
            mvWrapper.isLocalclub = customer.isLocalClub;
            mvWrapper.sameDayService = customer.entitlement.sameDayService;
            ent.authorizationCode = customer.authorize.code;
            ent.authorizationLevel = customer.authorize.level;
            ent.callsRemaining = customer.entitlement.callsRemaining;
            mvWrapper.outMemberContract = ent;
        }
        return mvWrapper;
    }
    /**********
    * @Method Name: transformCountryCode
    * @Parameters: FSL_Account.MembershipInformation
    * @Description: Transforms the country codes to salesforce configured values
    **************/
    private static void transformCountryCode(FSL_Account.MembershipInformation info){
        if(info.homeCountryCode != null){
            switch on info.homeCountryCode {
                when 'USA', 'United States', 'US' {
                    info.homeCountryCode = 'US';
                }
                when 'Canada', 'CA','CAN' {
                    info.homeCountryCode = 'CA';
                }
                when else {
                    info.homeCountryCode = 'US';
                }
            }
        }
    }
}