unpackaged/main/default/objects/Account/fields/Approved_Garage_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Garage_Type__c</fullName>
    <description>AAR = Approved Auto Repair; 
ADR = Approved Dealer Repair; 
AAB = Approved Auto Body; 
AAG = Approved Auto Glass; 
COR = Club Owned Repair; 
DTC = Discount Tire Company; 
MPR = Member Preferred Repair;</description>
    <inlineHelpText>AAR = Approved Auto Repair; 
ADR = Approved Dealer Repair; 
AAB = Approved Auto Body; 
AAG = Approved Auto Glass; 
COR = Club Owned Repair; 
DTC = Discount Tire Company; 
MPR = Member Preferred Repair;</inlineHelpText>
    <label>Approved Garage Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAR</fullName>
            </value>
            <value>
                <fullName>ADR</fullName>
            </value>
            <value>
                <fullName>AAB</fullName>
            </value>
            <value>
                <fullName>AAG</fullName>
            </value>
            <value>
                <fullName>COR</fullName>
            </value>
            <value>
                <fullName>DTC</fullName>
            </value>
            <value>
                <fullName>MPR</fullName>
            </value>
            <value>
                <fullName>ERS</fullName>
                <isActive>false</isActive>
                <label>ERS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Information__c.field-meta.xml
<CustomField>
    <fullName>Information__c</fullName>
    <description>Information regarding approved garage operation details</description>
    <inlineHelpText>Information regarding approved garage operation details</inlineHelpText>
    <label>Information</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Service_Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Service_Vehicle_Make__c</fullName>
    <label>Service Vehicle Make</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Dodge</fullName>
            </value>
            <value>
                <fullName>Jeep</fullName>
            </value>
            <value>
                <fullName>Plymouth</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Lincoln</fullName>
            </value>
            <value>
                <fullName>Mercury</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>GMC</fullName>
            </value>
            <value>
                <fullName>Hummer</fullName>
            </value>
            <value>
                <fullName>Oldsmobile</fullName>
            </value>
            <value>
                <fullName>Pontiac</fullName>
            </value>
            <value>
                <fullName>Saturn</fullName>
            </value>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Daewoo</fullName>
            </value>
            <value>
                <fullName>Datsun</fullName>
            </value>
            <value>
                <fullName>Honda</fullName>
            </value>
            <value>
                <fullName>Hyundai</fullName>
            </value>
            <value>
                <fullName>Infiniti</fullName>
            </value>
            <value>
                <fullName>Isuzu</fullName>
            </value>
            <value>
                <fullName>Kia</fullName>
            </value>
            <value>
                <fullName>Lexus</fullName>
            </value>
            <value>
                <fullName>Mazda</fullName>
            </value>
            <value>
                <fullName>Mitsubishi</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Scion</fullName>
            </value>
            <value>
                <fullName>Subaru</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Approved_Garage_Type_Mapping__c/Approved_Garage_Type_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>For the query of approved garage to RADAR case triage application. Need to make sure that the combination of Service Type, Tow Service Reason, and Vehicle Type are unique.</description>
    <label>Approved Garage Type Mapping</label>
</CustomObject>

unpackaged/main/default/objects/Approved_Garage_Type_Mapping__c/fields/Approved_Garage_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Garage_Type__c</fullName>
    <label>Approved Garage Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Garage_Type_Mapping__c/fields/Ignore_Make__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Make__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignore Make?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Approved_Garage_Type_Mapping__c/fields/Ignore_Type__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Type__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, coding logic will ignore vehicle type</description>
    <label>Ignore Vehicle Type?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Approved_Garage_Type_Mapping__c/fields/Limit_search_result__c.field-meta.xml
<CustomField>
    <fullName>Limit_search_result__c</fullName>
    <label>Limit search result</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Garage_Type_Mapping__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <inlineHelpText>If Service Type is blank, it means this mapping will ignore service types.</inlineHelpText>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Garage_Type_Mapping__c/fields/Tow_Service_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tow_Service_Reason__c</fullName>
    <label>Tow Service Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Approved_Garage_Type_Mapping__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ACG_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Tow</fullName>
            </value>
            <value>
                <fullName>Flat Tire</fullName>
            </value>
            <value>
                <fullName>Vehicle Lockout</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Extrication</fullName>
            </value>
            <value>
                <fullName>Home Lockout</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
            <value>
                <fullName>Extrication Tow Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Vehicle_Location_Address__c.field-meta.xml
<CustomField>
    <fullName>ACG_Vehicle_Location_Address__c</fullName>
    <label>Vehicle Location Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Approved_Garage_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Garage_Type__c</fullName>
    <formula>TEXT(  Approved_Garage__r.Approved_Garage_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approved Garage Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Member_Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2M (2-Wheeled Motorcycle)</fullName>
            </value>
            <value>
                <fullName>3M (3 - Wheeled Motorcycle)</fullName>
            </value>
            <value>
                <fullName>4M (ATV)</fullName>
            </value>
            <value>
                <fullName>BK (Bicycles)</fullName>
            </value>
            <value>
                <fullName>DW (Dual Wheels)</fullName>
            </value>
            <value>
                <fullName>GC (Golf Cart)</fullName>
            </value>
            <value>
                <fullName>PS (Passenger Car/Truck)</fullName>
            </value>
            <value>
                <fullName>R1 (RV &lt; 23 feet)</fullName>
            </value>
            <value>
                <fullName>R2 (RV 24-32 feet)</fullName>
            </value>
            <value>
                <fullName>R3 (RV &gt; 33 feet)</fullName>
            </value>
            <value>
                <fullName>SM (Snowmobile)</fullName>
            </value>
            <value>
                <fullName>TR (Trailer)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Integration_Settings__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>Used to oonfigur with Google API</description>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Location/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vehicle_Type__c/Vehicle_Type__c.object-meta.xml
<CustomObject>
    <label>Vehicle Type</label>
    <nameField>
        <label>Vehicle Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WorkOrder/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <formula>RecordType.Name</formula>
    <label>Service Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Tow.recordType-meta.xml
<RecordType>
    <fullName>Tow</fullName>
    <active>true</active>
    <label>Tow</label>
</RecordType>

unpackaged/main/default/globalValueSets/Vehicle_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Flatbed</fullName>
    </customValue>
    <customValue>
        <fullName>Light_Service</fullName>
        <label>Light Service</label>
    </customValue>
    <customValue>
        <fullName>Wheel_Lift</fullName>
        <label>Wheel Lift</label>
    </customValue>
    <customValue>
        <fullName>Locksmith</fullName>
    </customValue>
    <customValue>
        <fullName>Battery</fullName>
    </customValue>
    <customValue>
        <fullName>Landline</fullName>
        <isActive>false</isActive>
        <label>Landline</label>
    </customValue>
    <description>Available vehicle types driven by technicians</description>
    <masterLabel>Vehicle Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/INTTowTabController_Test.cls
@isTest
global class INTTowTabController_Test{
    
    global class AddressHttpResponseGenerator implements HttpCalloutMock {
        global HTTPResponse respond(HTTPRequest req){
            try{
                if(req.getEndpoint()=='https://maps.googleapis.com/maps/api/distancematrix/json?'){
                    system.debug('if');
                    HttpResponse res= new HttpResponse();
                    //res.getMethod('GET');
                    res.setBody('[{"title":"1313 Disneyland Dr, Anaheim, CA 92802, USA","description":"1313 Disneyland Dr, Anaheim, CA 92802, USA","location":{"Latitude":"33.81539590000001","Longitude":-117.9263991}}]');
                    res.setStatusCode(200);
                    String responseBody = res.getBody(); 
                    return res;
                    
                }else{
                    HttpResponse res= new HttpResponse();
                    res.setBody('INTDistanceMatrixAPIResponseWrapper:[destination_addresses=(28 HI-11, Hilo, HI 96720, USA), origin_addresses=(28 HI-11, Hilo, HI 96720, USA), rows=(Rows:[elements=(Elements:[distance=Distance:[text=1 ft, value=0], duration=Distance:[text=1 min, value=0], status=OK])]), status=OK]');
                    res.setStatusCode(200);
                    String responseBody = res.getBody(); 
                    return res;
                    
                
                }
            }catch(Exception ex){
                    System.debug('ERROR Message>>>'+ex.getMessage()+' Error Line Number>>> '+ex.getLineNumber());
            }
                return null;
             }
        }
    
    @isTest
    public static void testGetAarMprDetails(){
        Integer recordCount = 2;
        /*List<Account> accounts = FSL_DataFactory.createAccounts( recordCount );
        insert accounts;*/
        List<Account> accList = new List<Account>();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Approved Garage').getRecordTypeId();
        Account acc1 = new Account();
        acc1.recordTypeId = recordTypeId;
        acc1.Name = 'test1';
        acc1.Approved_Garage_Type__c = 'AAR';
        acc1.Information__c = 'Mon: 9AM-5PM;Tue: 8AM-6PM';
        accList.add(acc1);
        
        Account acc2 = new Account();
        acc2.recordTypeId = recordTypeId;
        acc2.Name = 'test2';
        acc2.Approved_Garage_Type__c = 'MPR';
        acc2.Service_Vehicle_Make__c = 'BMW';
        acc2.Information__c = 'Mon: 9AM-5PM;Tue: 8AM-6PM';
        accList.add(acc2);
        
        insert accList;
        
         List<Contact> contacts = FSL_DataFactory.createContacts( recordCount );
        for( Integer i = 0; i < recordCount; ++i ) {
            contacts[i].AccountId = accList[i].Id;
        }
        insert contacts;

        List<WorkOrder> workOrders = new List<WorkOrder>();
        for( Integer i = 0; i < recordCount; ++i ) {
            workOrders.add( FSL_DataFactory.createWorkOrderShell( 'Light Service', contacts[i] ) );
            workOrders[i].External_Id__c = 'ERS-' + i;
        }
        insert workOrders;
        
         List<Case> cases = new List<Case>();
        for( WorkOrder workOrder : workOrders ) {
            Case c1 = FSL_DataFactory.createCase( 'ERS Case' );
            c1.ACG_Service_Type__c = 'Tow';
            c1.ACG_Vehicle_Location_Address__c = '3333 Fairview Rd, Costa Mesa, CA 92626, USA';
            c1.Member_Vehicle_Type__c = 'PS (Passenger Car/Truck)';
            c1.Status = 'In Progress';
            cases.add( c1 );
            
            Case c2 = FSL_DataFactory.createCase( 'ERS Case' );
            c2.ACG_Vehicle_Location_Address__c = '3333 Fairview Rd, Costa Mesa, CA 92626, USA';
            c2.ACG_Service_Type__c = 'Tow';
            c2.Member_Vehicle_Type__c = 'R1 (RV < 23 feet)';
            c1.Status = 'In Progress';
            cases.add( c2 );

        }
        insert cases;
        
        List<Approved_Garage_Type_Mapping__c> lstApprovedGarageSetting = new List<Approved_Garage_Type_Mapping__c>();
        
        lstApprovedGarageSetting.add(new Approved_Garage_Type_Mapping__c(
            Name = 'Scenario1',
            Approved_Garage_Type__c = 'AAR;ADR;AAG;COR',
            Ignore_Make__c =true,
            Service_Type__c ='Flat Tire or Tow',
            Ignore_Type__c = true,
            Tow_Service_Reason__c = 'Accident; Alternator; Belt; Brakes Broken Windshield; Fuel Pump; Fuel Type of Diesel; Fuel Type of Electric; Hose; No Spare Tires; Overheat; Stalled While Driving; Starter; Transmission',
            Vehicle_Type__c = 'R1 (RV < 23 feet);R2 (RV 24-32 feet);R3 (RV > 33 feet)',
             Limit_search_result__c = '15'
        ));
        lstApprovedGarageSetting.add(new Approved_Garage_Type_Mapping__c(
            Name = 'Scenario2',
            Approved_Garage_Type__c = 'MPR;AAB',
            Ignore_Make__c =true,
            Ignore_Type__c = true,
            Service_Type__c ='Flat Tire or Tow',
            Tow_Service_Reason__c = 'Collison',
            Vehicle_Type__c = 'ALL',
             Limit_search_result__c = '15'
        ));
        insert lstApprovedGarageSetting;
        
        List<Integration_Settings__c> lstIntegrationSetting = new List<Integration_Settings__c>();
        
        lstIntegrationSetting.add(new Integration_Settings__c(
            name = 'GETDistance_Matrix_API',
            Method__c='GET',
            Enpoint_URL__c='htt',
            API_Key__c = 'AIzaSyDrqDOs4dvUGh74BkgI2DLz1_QWzrnXEcc'
        ));
        insert lstIntegrationSetting;
        
        System.assertEquals('MPR', accList[1].Approved_Garage_Type__c);
        INTTowTabController.getAarMprDetails(cases[1].Id,'36.7642024','-108.2395278','No Spare Tires');
        //INTTowTabController.getAarMprDetails(cases[2].Id,'36.7642024','-108.2395278','No Spare Tires');
        
        INTTowTabController.getAARBasedOnSelectedAddress(accList[0].Id);
        System.assertEquals('test1', accList[0].Name);
        
        INTTowTabController.updateCaseTowData(cases[1].Id, accList[0].Id);
        
        INTTowTabController.getCaseDetails(cases[1].Id);
        
        //INTTowTabController.getDistanceInMilesUsingAPI('19.72235304','-155.0643886','19.72235304','-155.0643886');
        INTTowTabController.updateCaseBasedonTowAddressValue(cases[0].Id,'13933 Poway Rd, Poway, CA 92064, USA','13933 Poway Rd','Poway','CA','92064','USA','19.72235304','-155.0643886','Poway');
        
    }
}