unpackaged/main/default/objects/Account/fields/Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Club_Code__c</fullName>
    <label>Club Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/ACG_AAR.recordType-meta.xml
<RecordType>
    <fullName>ACG_AAR</fullName>
    <active>true</active>
    <label>Repair Shops</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Club_Code__c</fullName>
    <label>Club Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>001</fullName>
            </value>
            <value>
                <fullName>002</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>007</fullName>
            </value>
            <value>
                <fullName>010</fullName>
            </value>
            <value>
                <fullName>012</fullName>
                <isActive>false</isActive>
                <label>012</label>
            </value>
            <value>
                <fullName>014</fullName>
            </value>
            <value>
                <fullName>017</fullName>
            </value>
            <value>
                <fullName>018</fullName>
            </value>
            <value>
                <fullName>019</fullName>
            </value>
            <value>
                <fullName>020</fullName>
            </value>
            <value>
                <fullName>022</fullName>
            </value>
            <value>
                <fullName>023</fullName>
            </value>
            <value>
                <fullName>028</fullName>
            </value>
            <value>
                <fullName>032</fullName>
                <isActive>false</isActive>
                <label>032</label>
            </value>
            <value>
                <fullName>033</fullName>
                <isActive>false</isActive>
                <label>033</label>
            </value>
            <value>
                <fullName>034</fullName>
                <isActive>false</isActive>
                <label>034</label>
            </value>
            <value>
                <fullName>035</fullName>
            </value>
            <value>
                <fullName>036</fullName>
            </value>
            <value>
                <fullName>037</fullName>
            </value>
            <value>
                <fullName>039</fullName>
            </value>
            <value>
                <fullName>042</fullName>
                <isActive>false</isActive>
                <label>042</label>
            </value>
            <value>
                <fullName>044</fullName>
            </value>
            <value>
                <fullName>045</fullName>
                <isActive>false</isActive>
                <label>045</label>
            </value>
            <value>
                <fullName>047</fullName>
            </value>
            <value>
                <fullName>049</fullName>
            </value>
            <value>
                <fullName>057</fullName>
            </value>
            <value>
                <fullName>063</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Club_Name__c.field-meta.xml
<CustomField>
    <fullName>Club_Name__c</fullName>
    <label>Club Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Club_Code__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AAA Akron Auto Club</fullName>
            </value>
            <value>
                <fullName>AAA Alabama</fullName>
            </value>
            <value>
                <fullName>AAA Alaska</fullName>
            </value>
            <value>
                <fullName>AAA Allegheny</fullName>
            </value>
            <value>
                <fullName>AAA Allied Group, Inc.</fullName>
            </value>
            <value>
                <fullName>AAA Allied Group - KS</fullName>
            </value>
            <value>
                <fullName>AAA Arizona</fullName>
            </value>
            <value>
                <fullName>AAA Auto Club South</fullName>
            </value>
            <value>
                <fullName>AAA Blair County</fullName>
            </value>
            <value>
                <fullName>AAA Blue Grass/Kentucky</fullName>
            </value>
            <value>
                <fullName>AAA Blue Grass/Kentucky//Merge w/007</fullName>
            </value>
            <value>
                <fullName>AAA Butler County</fullName>
            </value>
            <value>
                <fullName>AAA Carolinas</fullName>
            </value>
            <value>
                <fullName>AAA Central Penn</fullName>
            </value>
            <value>
                <fullName>AAA Central Penn Automobile Club</fullName>
            </value>
            <value>
                <fullName>AAA Central-West Jersey</fullName>
            </value>
            <value>
                <fullName>AAA Chicago Motor Club</fullName>
            </value>
            <value>
                <fullName>AAA Cincinnati</fullName>
            </value>
            <value>
                <fullName>AAA Club Partners, Inc.</fullName>
            </value>
            <value>
                <fullName>AAA Colorado</fullName>
            </value>
            <value>
                <fullName>AAA Columbiana County</fullName>
            </value>
            <value>
                <fullName>AAA East Central</fullName>
            </value>
            <value>
                <fullName>AAA East Penn</fullName>
            </value>
            <value>
                <fullName>AAA Florida/Louisana/Miss</fullName>
            </value>
            <value>
                <fullName>AAA Hawaii</fullName>
            </value>
            <value>
                <fullName>AAA Hawaii//Merge w/004</fullName>
            </value>
            <value>
                <fullName>AAA Hoosier Motor Club</fullName>
            </value>
            <value>
                <fullName>AAA Hudson Valley</fullName>
            </value>
            <value>
                <fullName>AAA Huntingdon County</fullName>
            </value>
            <value>
                <fullName>AAA Iowa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ERS_Club_Mapping__mdt/ERS_Club_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>ERS Club Mapping</label>
    <pluralLabel>ERS Club Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ERS_Club_Mapping__mdt/fields/Club_Name__c.field-meta.xml
<CustomField>
    <fullName>Club_Name__c</fullName>
    <label>Club Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ERS_Club_Mapping__mdt/fields/Comm_Center__c.field-meta.xml
<CustomField>
    <fullName>Comm_Center__c</fullName>
    <label>Comm Center</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ERS_Club_Mapping__mdt/fields/Dispatcher_Code__c.field-meta.xml
<CustomField>
    <fullName>Dispatcher_Code__c</fullName>
    <label>Dispatcher Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ERS_Payment__c/ERS_Payment__c.object-meta.xml
<CustomObject>
    <label>ERS Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERS Payments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ERS_Payment__c/fields/Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Club_Code__c</fullName>
    <label>Club Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ERS_Payment__c/fields/Club_Name__c.field-meta.xml
<CustomField>
    <fullName>Club_Name__c</fullName>
    <label>Club Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ERS_Payment__c/fields/Comm_Center__c.field-meta.xml
<CustomField>
    <fullName>Comm_Center__c</fullName>
    <label>Comm Center</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>TN</fullName>
            </value>
            <value>
                <fullName>WI</fullName>
            </value>
            <value>
                <fullName>111</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ERS_Payment__c/fields/Reciprocal__c.field-meta.xml
<CustomField>
    <fullName>Reciprocal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reciprocal</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ERS_Payment__c/recordTypes/Call_Adjustment.recordType-meta.xml
<RecordType>
    <fullName>Call_Adjustment</fullName>
    <active>true</active>
    <label>Call Adjustment</label>
</RecordType>

unpackaged/main/default/objects/ERS_Payment__c/recordTypes/Call_Payment.recordType-meta.xml
<RecordType>
    <fullName>Call_Payment</fullName>
    <active>true</active>
    <label>Call</label>
</RecordType>

unpackaged/main/default/objects/ERS_Payment__c/recordTypes/Facility_Adjustment.recordType-meta.xml
<RecordType>
    <fullName>Facility_Adjustment</fullName>
    <active>true</active>
    <label>Facility Adjustment</label>
</RecordType>

unpackaged/main/default/objects/ERS_Payment__c/recordTypes/Reimbursement_Payment.recordType-meta.xml
<RecordType>
    <fullName>Reimbursement_Payment</fullName>
    <active>true</active>
    <label>Reimbursement Payment</label>
</RecordType>

unpackaged/main/default/objects/mapFieldNamebyProductId__mdt/mapFieldNamebyProductId__mdt.object-meta.xml
<CustomObject>
    <label>Product Id and Field Name Mapping</label>
    <pluralLabel>mapFieldNamebyProductIds</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/mapFieldNamebyProductId__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Original_Tow_Amount__c</fullName>
                <default>true</default>
                <label>Original_Tow_Amount__c</label>
            </value>
            <value>
                <fullName>Storage_Fees__c</fullName>
            </value>
            <value>
                <fullName>Clean_up_an_labour__c</fullName>
            </value>
            <value>
                <fullName>Mileage__c</fullName>
            </value>
            <value>
                <fullName>Special_Equipment__c</fullName>
            </value>
            <value>
                <fullName>Advance_Charge_fees__c</fullName>
            </value>
            <value>
                <fullName>Advance_Charge_Fees_Miscellaneous__c</fullName>
            </value>
            <value>
                <fullName>Advance_Charge_Fees_Storage__c</fullName>
            </value>
            <value>
                <fullName>Advance_Charge_Fees_Towing_and_Mileage__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/mapFieldNamebyProductId__mdt/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <label>Product Id</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BA</fullName>
                <default>true</default>
                <label>BA</label>
            </value>
            <value>
                <fullName>Y1</fullName>
            </value>
            <value>
                <fullName>Y2</fullName>
            </value>
            <value>
                <fullName>Y3</fullName>
            </value>
            <value>
                <fullName>Y4</fullName>
            </value>
            <value>
                <fullName>Y5</fullName>
            </value>
            <value>
                <fullName>OM</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>ZM</fullName>
            </value>
            <value>
                <fullName>ZS</fullName>
            </value>
            <value>
                <fullName>ZT</fullName>
            </value>
            <value>
                <fullName>ZF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ACG_UtilityClass.cls
public inherited sharing class ACG_UtilityClass {
    
    public static final Id CUSTOMER_RECORDTYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ACG_Customer').getRecordTypeId();
    public static final Id MEMBER_RECORDTYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ACG_Member').getRecordTypeId();
    //public static final Id HOUSEHOLD_ACCOUNT_RECORDTYPEID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
    public static final Id FACILITY_RECORDTYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Facility').getRecordTypeId();
	public static final Id REPAIRSHOP_RECORDTYPE_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ACG_AAR').getRecordTypeId();
    
    
    /*public static final Id CASE_CALL_ADJUSTMENT_RECORDTYPE_ID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ACG_Call_Adjustment').getRecordTypeId();
    public static final Id ERS_PAYMENT_CALL_RECORDTYPE_ID = Schema.SObjectType.ERS_Payment__c.getRecordTypeInfosByDeveloperName().get('Call_Payment').getRecordTypeId();
    public static final Id ERS_PAYMENT_CALL_ADJUSTMENT_RECORDTYPE_ID = Schema.SObjectType.ERS_Payment__c.getRecordTypeInfosByDeveloperName().get('Call_Adjustment').getRecordTypeId();
	public static final Id ERS_PAYMENT_FACILITY_ADJUSTMENT_RECORDTYPE_ID = Schema.SObjectType.ERS_Payment__c.getRecordTypeInfosByDeveloperName().get('Facility_Adjustment').getRecordTypeId();
    public static final Id ERS_PAYMENT_REIMBURSEMENT_RECORDTYPE_ID = Schema.SObjectType.ERS_Payment__c.getRecordTypeInfosByDeveloperName().get('Reimbursement_Payment').getRecordTypeId();*/
    
    public static final Id RECIPROCAL_FEEDBACK_RECORDTYPE_ID = Schema.SObjectType.Reciprocal__c.getRecordTypeInfosByDeveloperName().get('Feedback').getRecordTypeId();
    public static final Id RECIPROCAL_INBOUND_RECORDTYPE_ID = Schema.SObjectType.Reciprocal__c.getRecordTypeInfosByDeveloperName().get('Inbound_Payment_Requests').getRecordTypeId();
    public static final Id RECIPROCAL_OUTBOUND_RECORDTYPE_ID = Schema.SObjectType.Reciprocal__c.getRecordTypeInfosByDeveloperName().get('Outbound_Payment_Requests').getRecordTypeId();
    
    public static Map<String, ERS_Club_Mapping__mdt> getClubMappingByCommcenter(){
        Map<String, ERS_Club_Mapping__mdt> mapClubMapping = new Map<String, ERS_Club_Mapping__mdt>();
        for(ERS_Club_Mapping__mdt cm : [SELECT Comm_Center__c, 
                                        Club_Code__c, 
                                        Club_Name__c,
                                        Dispatcher_Code__c
                                        FROM ERS_Club_Mapping__mdt where Comm_Center__c != null]){
                                            mapClubMapping.put(cm.Comm_Center__c, cm);
                                        }
        return mapClubMapping;
    }
    
    public static Map<String, String> getClubMappingByCode(){
        Map<String, String> mapClubNameByCode = new Map<String, String>();
        for(ERS_Club_Mapping__mdt cm : [SELECT Club_Code__c, 
                                        Club_Name__c
                                        FROM ERS_Club_Mapping__mdt where Club_Code__c != null  ]){
                                            mapClubNameByCode.put(cm.Club_Code__c, cm.Club_Name__c);
                                        }
        return mapClubNameByCode;
    }
    
    public static Map<String, String> getFieldNameByProductID(){
        Map<String, String> mapFieldNameByProductID = new Map<String, String>();
        for(mapFieldNamebyProductId__mdt cm : [SELECT  Product_Id__c,
                                               Field_Name__c
                                               FROM mapFieldNamebyProductId__mdt where Product_Id__c != null]){
                                                   mapFieldNameByProductID.put(cm.Product_Id__c, cm.Field_Name__c);
                                               }
        return mapFieldNameByProductID;
    }
    
    public static Map<String, String> getCodeByState(){
        Map<String, String> mapCodeByState = new Map<String, String>();
        for(State_Code_Mapping__mdt sc : [SELECT State__c,
                                          Code__c
                                          FROM State_Code_Mapping__mdt where State__c != null]){
                                              mapCodeByState.put(sc.State__c.toLowerCase(), sc.Code__c);
                                          }
        return mapCodeByState;
    }
    
    public static String getTimeBand(DateTime dispatchedDateTime){
        String timeBandLabel = '';
        for(Time_Of_Day_Mapping__mdt timeBand : [SELECT Id, 
                                                 MasterLabel, 
                                                 Start_Time__c, 
                                                 End_Time__c 
                                                 FROM Time_Of_Day_Mapping__mdt where MasterLabel != null]){
                                                     Time startTime = time.newInstance(Integer.valueOf(timeBand.Start_Time__c.split(':')[0]),Integer.valueOf(timeBand.Start_Time__c.split(':')[1]),0,0);
                                                     Time endTime = time.newInstance(Integer.valueOf(timeBand.End_Time__c.split(':')[0]),Integer.valueOf(timeBand.End_Time__c.split(':')[1]),0,0);
                                                     if(startTime <= dispatchedDateTime.time() && endTime > dispatchedDateTime.time()){
                                                         timeBandLabel = timeBand.MasterLabel;
                                                         break;
                                                     }
                                                 }
        return timeBandLabel;
    }
}