unpackaged/main/default/objects/Account/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/ACG_Facility_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment</label>
    <nameField>
        <displayFormat>FA-{000}</displayFormat>
        <label>Facility Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Deprecate?) Facility Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>ACG_Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Status__c.field-meta.xml
<CustomField>
    <fullName>ACG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Facility_Adjustment_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment_Name__c</fullName>
    <label>Facility Adjustment Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/ACG_Facility_Adjustment_Payment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment Payment</label>
    <nameField>
        <displayFormat>FAP-{000}</displayFormat>
        <label>Facility Adjustment Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustment Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/ACG_Adjustment_ID__c.field-meta.xml
<CustomField>
    <fullName>ACG_Adjustment_ID__c</fullName>
    <label>Facility Adjustment ID</label>
    <referenceTo>ACG_Facility_Adjustment__c</referenceTo>
    <relationshipLabel>Facility Adjustment Payments</relationshipLabel>
    <relationshipName>Facility_Adjustment_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/ACG_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>ACG_Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Facility Adjustment Payments</relationshipLabel>
    <relationshipName>Facility_Adjustment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>System Admin only field. Helps differentiate which FAP belongs to which Invoice in ACG_CreateFacilityAdjustments Apex class.</description>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Facility Adjustment Payments</relationshipLabel>
    <relationshipName>Facility_Adjustment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Adjustment</label>
    <referenceTo>ACG_Facility_Adjustment__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment_Category__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment_Category__c</fullName>
    <label>Facility Adjustment Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERS Calls</fullName>
            </value>
            <value>
                <fullName>Call Adjustments</fullName>
            </value>
            <value>
                <fullName>Facility Adjustments</fullName>
            </value>
            <value>
                <fullName>Reciprocals</fullName>
            </value>
            <value>
                <fullName>Reciprocal Adjustments</fullName>
            </value>
            <value>
                <fullName>Facility Adjustment</fullName>
                <isActive>false</isActive>
                <label>Facility Adjustment</label>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
            <value>
                <fullName>Service Adjustment</fullName>
                <isActive>false</isActive>
                <label>Service Adjustment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/recordTypes/Facility_Adjustment.recordType-meta.xml
<RecordType>
    <fullName>Facility_Adjustment</fullName>
    <active>true</active>
    <label>Facility Adjustment</label>
</RecordType>

unpackaged/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>SI#{00000000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice_Line_Item__c/fields/Charge_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Charge_to_Account__c</fullName>
    <label>Charge to Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice_Line_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Invoice_Line_Item__c/fields/Facility_Adjustment_Payment__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Adjustment Payment</label>
    <referenceTo>ACG_Facility_Adjustment_Payment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice_Line_Item__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Invoice_Line_Item__c/recordTypes/Facility_Adjustment.recordType-meta.xml
<RecordType>
    <fullName>Facility_Adjustment</fullName>
    <active>true</active>
    <label>Facility Adjustment</label>
</RecordType>

unpackaged/main/default/objects/ServiceTerritory/fields/Non_Payment_Facility__c.field-meta.xml
<CustomField>
    <fullName>Non_Payment_Facility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies a Facility that will not have payment file created for itself during its payment cycles</description>
    <label>Non Payment Facility</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSL</fullName>
            </value>
            <value>
                <fullName>Lightning Scheduler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/recordTypes/Facility_Territory.recordType-meta.xml
<RecordType>
    <fullName>Facility_Territory</fullName>
    <active>true</active>
    <description>Territory that handles all types of services</description>
    <label>Facility Territory</label>
</RecordType>

unpackaged/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST#{00000000}</displayFormat>
        <label>Statement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Statement__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When a statement has been reconciled and processed for payment</description>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Unreconciled</fullName>
                <default>true</default>
                <label>Unreconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Reimbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AAAUpdateFAPWithInvoiceStatusBatchTest.cls
@isTest
class AAAUpdateFAPWithInvoiceStatusBatchTest {
    private static String readyForProcessing = 'Ready for Processing';
    private static String readyForPayment = 'Ready for Payment';

    @TestSetup
    static void makeData() {
        RecordType facTerritoryType = [
            SELECT Id 
            FROM RecordType 
            WHERE DeveloperName = 'Facility_Territory' 
            AND SobjectType = 'ServiceTerritory' 
            LIMIT 1
        ];
        RecordType facAdjType = [
            SELECT Id 
            FROM RecordType 
            WHERE DeveloperName = 'Facility_Adjustment' 
            AND SobjectType = 'Invoice__c' 
            LIMIT 1
        ];

        OperatingHours opHrs = new OperatingHours(
            TimeZone = 'America/New_York',
            Name = 'Apex Test Time Zone'
        );
        insert opHrs;

        ServiceTerritory svcTerritory = new ServiceTerritory(
            Name = 'Apex Test Service Territory',
            RecordTypeId = facTerritoryType.Id,
            OperatingHoursId = opHrs.Id,
            IsActive = true,
            Non_Payment_Facility__c = false
        );
        insert svcTerritory;

        Statement__c stmt = new Statement__c(
            Service_Territory__c = svcTerritory.Id,
            Start_Date__c = System.today(),
            End_Date__c = System.today(),
            Statement_Name__c = 'Apex Test Statement 1',
            Status__c = 'Reconciled',
            Processed__c = false
        );
        insert stmt;

        Id facilityRecordTypeId  = EP.getRecordTypeId(Account.SObjectType, 'Facility');
        Account objFacility1 = ACG_TestDataFactory.createAccounts(facilityRecordTypeId, 1, false, false)[0];
        insert objFacility1 ;

        ACG_Facility_Adjustment__c facAdj = new ACG_Facility_Adjustment__c(
            Facility_Adjustment_Name__c = 'Apex Test Facility Adjustment',
            Service_Territory__c = svcTerritory.Id,
            Account__c = objFacility1.Id
        );
        insert facAdj;

        Invoice__c invc = new Invoice__c(
            Status__c = readyForPayment,
            Facility_Adjustment__c = facAdj.Id,
            Service_Territory__c = svcTerritory.Id,
            Statement__c = stmt.Id,
            Facility_Adjustment_Category__c = 'Hardware',
            RecordTypeId = facAdjType.Id,
            Type__c = 'Facility Adjustments'
        );
        insert invc;

        ACG_Facility_Adjustment_Payment__c facAdjPmt = new ACG_Facility_Adjustment_Payment__c(
            ACG_Adjustment_ID__c = facAdj.Id,
            ACG_Payment_Amount__c = 0.0
        );
        insert facAdjPmt;

        insert new Invoice_Line_Item__c(
            Invoice__c = invc.Id,
            Facility_Adjustment_Payment__c = facAdjPmt.Id,
            Charge_to_Account__c = 'B',
            Cost__c = 10.0,
            Tax__c = 0.0
        );
    }

    @isTest
    static void runUpdateFAPWithInvoiceStatusBatchTest1() {
        Test.startTest();
        Database.executeBatch(new AAAUpdateFAPWithInvoiceStatusBatch());
        Test.stopTest();

        List<ACG_Facility_Adjustment_Payment__c> fapList = [
            SELECT Id, ACG_Status__c
            FROM ACG_Facility_Adjustment_Payment__c
        ];

        for (ACG_Facility_Adjustment_Payment__c fap : fapList) {
            System.assertEquals(fap.ACG_Status__c, readyForPayment, 'Failed to update FAP status.');
        }
    }

    @isTest
    static void runUpdateFAPWithInvoiceStatusBatchTest2() {
        List<String> invcIdList = new List<String>();
        List<Invoice__c> invcList = [
            SELECT Id, Status__c
            FROM Invoice__c
        ];
        for (Invoice__c invc : invcList) {
            invc.Status__c = readyForProcessing;
            invcIdList.add(invc.Id);
        }
        update invcList;

        List<ACG_Facility_Adjustment_Payment__c> fapList = [
            SELECT Id, ACG_Status__c
            FROM ACG_Facility_Adjustment_Payment__c
        ];
        for (ACG_Facility_Adjustment_Payment__c fap : fapList) {
            fap.ACG_Status__c = readyForPayment;
        }
        update fapList;

        Test.startTest();
        Database.executeBatch(new AAAUpdateFAPWithInvoiceStatusBatch(invcIdList));
        Test.stopTest();

        List<ACG_Facility_Adjustment_Payment__c> fapResList = [
            SELECT Id, ACG_Status__c
            FROM ACG_Facility_Adjustment_Payment__c
        ];

        for (ACG_Facility_Adjustment_Payment__c fap : fapResList) {
            System.assertEquals(fap.ACG_Status__c, readyForProcessing, 'Failed to update FAP status.');
        }
    }
}