unpackaged/main/default/objects/Account/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/ACG_Facility_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment</label>
    <nameField>
        <displayFormat>FA-{000}</displayFormat>
        <label>Facility Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Deprecate?) Facility Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Facility_Adjustment_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment_Name__c</fullName>
    <label>Facility Adjustment Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Adjustment</label>
    <referenceTo>ACG_Facility_Adjustment__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment_Category__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment_Category__c</fullName>
    <label>Facility Adjustment Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERS Calls</fullName>
            </value>
            <value>
                <fullName>Call Adjustments</fullName>
            </value>
            <value>
                <fullName>Facility Adjustments</fullName>
            </value>
            <value>
                <fullName>Reciprocals</fullName>
            </value>
            <value>
                <fullName>Reciprocal Adjustments</fullName>
            </value>
            <value>
                <fullName>Facility Adjustment</fullName>
                <isActive>false</isActive>
                <label>Facility Adjustment</label>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
            <value>
                <fullName>Service Adjustment</fullName>
                <isActive>false</isActive>
                <label>Service Adjustment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/recordTypes/Facility_Adjustment.recordType-meta.xml
<RecordType>
    <fullName>Facility_Adjustment</fullName>
    <active>true</active>
    <label>Facility Adjustment</label>
</RecordType>

unpackaged/main/default/objects/ServiceTerritory/fields/Non_Payment_Facility__c.field-meta.xml
<CustomField>
    <fullName>Non_Payment_Facility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies a Facility that will not have payment file created for itself during its payment cycles</description>
    <label>Non Payment Facility</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSL</fullName>
            </value>
            <value>
                <fullName>Lightning Scheduler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/recordTypes/Facility_Territory.recordType-meta.xml
<RecordType>
    <fullName>Facility_Territory</fullName>
    <active>true</active>
    <description>Territory that handles all types of services</description>
    <label>Facility Territory</label>
</RecordType>

unpackaged/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST#{00000000}</displayFormat>
        <label>Statement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Statement__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When a statement has been reconciled and processed for payment</description>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Unreconciled</fullName>
                <default>true</default>
                <label>Unreconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Reimbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FSL_StatementTriggerHandlerTest.cls
@isTest
class FSL_StatementTriggerHandlerTest {
    static List<Statement__c> createData(Integer amt) {
        RecordType facTerritoryType = [
            SELECT Id 
            FROM RecordType 
            WHERE DeveloperName = 'Facility_Territory' 
            AND SobjectType = 'ServiceTerritory' 
            LIMIT 1
        ];
        RecordType facAdjType = [
            SELECT Id 
            FROM RecordType 
            WHERE DeveloperName = 'Facility_Adjustment' 
            AND SobjectType = 'Invoice__c' 
            LIMIT 1
        ];

        OperatingHours opHrs = new OperatingHours(
            TimeZone = 'America/New_York',
            Name = 'Apex Test Time Zone'
        );
        insert opHrs;

        ServiceTerritory svcTerritory = new ServiceTerritory(
            Name = 'Apex Test Service Territory',
            RecordTypeId = facTerritoryType.Id,
            OperatingHoursId = opHrs.Id,
            IsActive = true,
            Non_Payment_Facility__c = false
        );
        insert svcTerritory;

        Id facilityRecordTypeId  = EP.getRecordTypeId(Account.SObjectType, 'Facility');
        Account objFacility1 = ACG_TestDataFactory.createAccounts(facilityRecordTypeId,1,false,false)[0];
        insert objFacility1 ;

        ACG_Facility_Adjustment__c facAdj = new ACG_Facility_Adjustment__c(
            Facility_Adjustment_Name__c = 'Apex Test Facility Adjustment',
            Service_Territory__c = svcTerritory.Id,
            Account__c = objFacility1.Id
        );
        insert facAdj;

        List<Statement__c> stmtList = new List<Statement__c>();
        for (Integer i = 0; i < amt; i++) {
            stmtList.add(
                new Statement__c(
                    Service_Territory__c = svcTerritory.Id,
                    Start_Date__c = System.today(),
                    End_Date__c = System.today(),
                    Statement_Name__c = 'Apex Test Statement' + (i + 1),
                    Status__c = 'Unreconciled',
                    Processed__c = false
                )
            );
        }
        insert stmtList;

        List<Invoice__c> invcList = new List<Invoice__c>();
        for (Statement__c stmt : stmtList) {
            invcList.add(
                new Invoice__c(
                    Status__c = 'Ready for Processing',
                    Facility_Adjustment__c = facAdj.Id,
                    Service_Territory__c = svcTerritory.Id,
                    Statement__c = stmt.Id,
                    Facility_Adjustment_Category__c = 'Hardware',
                    RecordTypeId = facAdjType.Id,
                    Type__c = 'Facility Adjustments'
                )
            );
        }
        insert invcList;

        return stmtList;
    }

    @isTest
    static void markInvcsReadyForPaymentTest1() {
        String expectedResult = 'Ready for Payment';
        List<Statement__c> stmtList = createData(1);
        List<Statement__c> stmtUpdateList = new List<Statement__c>();

        for (Statement__c stmt : stmtList) {
            stmt.Status__c = 'Reconciled';
            stmtUpdateList.add(stmt);
        }

        update stmtUpdateList;

        List<Invoice__c> invcList = [
            SELECT Id, Status__c
            FROM Invoice__c
        ];

        for (Invoice__c invc : invcList) {
            System.assertEquals(expectedResult, invc.Status__c, 'Failed to update Invoices.');
        }
    }

    @isTest
    static void markInvcsReadyForPaymentTest2() {
        String expectedResult = 'Ready for Payment';
        List<Statement__c> stmtList = createData(3);
        List<Statement__c> stmtUpdateList = new List<Statement__c>();

        for (Statement__c stmt : stmtList) {
            stmt.Status__c = 'Reconciled';
            stmtUpdateList.add(stmt);
        }

        // for asynchronous batch process
        Test.startTest();
        update stmtUpdateList;
        Test.stopTest();

        List<Invoice__c> invcList = [
            SELECT Id, Status__c
            FROM Invoice__c
        ];

        for (Invoice__c invc : invcList) {
            System.assertEquals(expectedResult, invc.Status__c, 'Failed to update Invoices.');
        }
    }
}