unpackaged/main/default/objects/Account/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/ACG_Facility_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment</label>
    <nameField>
        <displayFormat>FA-{000}</displayFormat>
        <label>Facility Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Deprecate?) Facility Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_No_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>ACG_No_of_Payments__c</fullName>
    <defaultValue>1</defaultValue>
    <label>No. of Payments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>ACG_Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ACG_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Status__c.field-meta.xml
<CustomField>
    <fullName>ACG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Facility_Adjustment_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment_Name__c</fullName>
    <label>Facility Adjustment Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Adjustment</label>
    <referenceTo>ACG_Facility_Adjustment__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AAA</fullName>
                <isActive>false</isActive>
                <label>AAA</label>
            </value>
            <value>
                <fullName>AAR</fullName>
                <isActive>false</isActive>
                <label>AAR</label>
            </value>
            <value>
                <fullName>AFFCL</fullName>
                <isActive>false</isActive>
                <label>AFFCL</label>
            </value>
            <value>
                <fullName>ALLIED</fullName>
                <isActive>false</isActive>
                <label>ALLIED</label>
            </value>
            <value>
                <fullName>CCIT</fullName>
                <isActive>false</isActive>
                <label>CCIT</label>
            </value>
            <value>
                <fullName>CMCFLEET</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DA</fullName>
                <isActive>false</isActive>
                <label>DA</label>
            </value>
            <value>
                <fullName>DM</fullName>
                <isActive>false</isActive>
                <label>DM</label>
            </value>
            <value>
                <fullName>EMAIL</fullName>
                <isActive>false</isActive>
                <label>EMAIL</label>
            </value>
            <value>
                <fullName>ERURL</fullName>
                <isActive>false</isActive>
                <label>ERURL</label>
            </value>
            <value>
                <fullName>FLEET</fullName>
                <isActive>false</isActive>
                <label>FLEET</label>
            </value>
            <value>
                <fullName>FLTAGI</fullName>
                <isActive>false</isActive>
                <label>FLTAGI</label>
            </value>
            <value>
                <fullName>FLTGP</fullName>
                <isActive>false</isActive>
                <label>FLTGP</label>
            </value>
            <value>
                <fullName>GPCOMM</fullName>
                <isActive>false</isActive>
                <label>GPCOMM</label>
            </value>
            <value>
                <fullName>GPEMAIL</fullName>
                <isActive>false</isActive>
                <label>GPEMAIL</label>
            </value>
            <value>
                <fullName>HARTFORD</fullName>
                <isActive>false</isActive>
                <label>HARTFORD</label>
            </value>
            <value>
                <fullName>JUNK</fullName>
                <isActive>false</isActive>
                <label>JUNK</label>
            </value>
            <value>
                <fullName>KAN</fullName>
                <isActive>false</isActive>
                <label>KAN</label>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MAFLEET</fullName>
            </value>
            <value>
                <fullName>MAIL</fullName>
                <isActive>false</isActive>
                <label>MAIL</label>
            </value>
            <value>
                <fullName>MONTHLY</fullName>
                <isActive>false</isActive>
                <label>MONTHLY</label>
            </value>
            <value>
                <fullName>MVMO</fullName>
                <isActive>false</isActive>
                <label>MVMO</label>
            </value>
            <value>
                <fullName>NJFLEET</fullName>
            </value>
            <value>
                <fullName>NWJERSEY</fullName>
            </value>
            <value>
                <fullName>NYFLEET</fullName>
            </value>
            <value>
                <fullName>OAC</fullName>
                <isActive>false</isActive>
                <label>OAC</label>
            </value>
            <value>
                <fullName>OKFLT</fullName>
                <isActive>false</isActive>
                <label>OKFLT</label>
            </value>
            <value>
                <fullName>OKMETDD</fullName>
                <isActive>false</isActive>
                <label>OKMETDD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bi-monthly</fullName>
                <default>true</default>
                <label>Bi-monthly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/recordTypes/Facility_Territory.recordType-meta.xml
<RecordType>
    <fullName>Facility_Territory</fullName>
    <active>true</active>
    <description>Territory that handles all types of services</description>
    <label>Facility Territory</label>
</RecordType>

unpackaged/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST#{00000000}</displayFormat>
        <label>Statement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Statement__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Unreconciled</fullName>
                <default>true</default>
                <label>Unreconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AAAStatementCreationBatchTest.cls
@isTest
class AAAStatementCreationBatchTest {
    @TestSetup
    static void createTestData() {
        RecordType facTerritoryType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Facility_Territory' AND SobjectType = 'ServiceTerritory' LIMIT 1];
        RecordType facAcctType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Facility' AND SobjectType = 'Account' LIMIT 1];
        List<ACG_Facility_Adjustment__c> facAdjList = new List<ACG_Facility_Adjustment__c>();
        Date dateToday = Date.today();
        Integer year = dateToday.year();
        Integer month = dateToday.month();
        Integer day = dateToday.day();
        
        Date monthlyStartDate = Date.newInstance(year, month, 1);
        Date biMonthlyStartDate = day > 16 ? Date.newInstance(year, month, 16) : monthlyStartDate;

        OperatingHours opHrs = new OperatingHours(
            TimeZone = 'America/New_York',
            Name = 'Apex Test Time Zone'
        );
        insert opHrs;

        List<ServiceTerritory> svcTerritoryList = new List<ServiceTerritory>{
            new ServiceTerritory(
                Name = 'Apex Test Service Territory 1',
                RecordTypeId = facTerritoryType.Id,
                OperatingHoursId = opHrs.Id,
                isActive = true,
                Payment_Schedule__c = 'Bi-monthly'
            ),
            new ServiceTerritory(
                Name = 'Apex Test Service Territory 2',
                RecordTypeId = facTerritoryType.Id,
                OperatingHoursId = opHrs.Id,
                isActive = true,
                Payment_Schedule__c = 'Monthly'
            ),
            new ServiceTerritory(
                Name = 'Apex Test Service Territory 3',
                RecordTypeId = facTerritoryType.Id,
                OperatingHoursId = opHrs.Id,
                isActive = true,
                Payment_Schedule__c = 'Bi-monthly'
            ),
            new ServiceTerritory(
                Name = 'Apex Test Service Territory 4',
                RecordTypeId = facTerritoryType.Id,
                OperatingHoursId = opHrs.Id,
                isActive = true,
                Payment_Schedule__c = 'Monthly'
            )
        };
        insert svcTerritoryList;

        Account acct = new Account(
            Name = 'Apex Test Facility Account',
            Phone = '1234567890',
            RecordTypeId = facAcctType.Id
        );
        insert acct;

        for(Integer i = 0; i < 4; i++) {
            ACG_Facility_Adjustment__c facAdj = new ACG_Facility_Adjustment__c(
                Facility_Adjustment_Name__c = 'Apex Test Facility Adjustment ' + i + '-a',
                Service_Territory__c = svcTerritoryList[0].Id,
                ACG_Status__c = 'Active',
                ACG_No_of_Payments__c = 1,
                Account__c = acct.Id,
                ACG_Start_Date__c = biMonthlyStartDate,
                ACG_Payment_Amount__c = 100
            );
            facAdjList.add(facAdj);
        }

        for(Integer i = 0; i < 4; i++) {
            ACG_Facility_Adjustment__c facAdj = new ACG_Facility_Adjustment__c(
                Facility_Adjustment_Name__c = 'Apex Test Facility Adjustment ' + i + '-b',
                Service_Territory__c = svcTerritoryList[1].Id,
                ACG_Status__c = 'Active',
                ACG_No_of_Payments__c = 1, 
                Account__c = acct.Id,
                ACG_Start_Date__c = monthlyStartDate,
                ACG_Payment_Amount__c = 100
            );
            facAdjList.add(facAdj);
        }
        insert facAdjList;
    }

    @isTest
    static void createStatementBatchTest() {
        Test.startTest();
        Database.executeBatch(new AAAStatementCreationBatch(), 200);
        Test.stopTest();

        List<Statement__c> stmtList = [SELECT Id, Service_Territory__c, Start_Date__c, End_Date__c, Statement_Name__c, Status__c, Group__c FROM Statement__c WHERE Service_Territory__c IN (SELECT Id FROM ServiceTerritory WHERE Name LIKE 'Apex Test Service Territory%') order by Statement_Name__c];
        Date startDate = Date.Today();
        Integer currentMonth = startDate.Month();
        Integer currentYear = startDate.Year();
        Date endDate;
        Date monthlyEndDate;
        Date nextMonthStartDate;

        if(startDate.day() <= 15){
           endDate = Date.newInstance(currentYear, currentMonth, 15); 
        } else {
            if(currentMonth == 12){
                endDate = Date.newInstance(currentYear, 12, 31);
            } else {
                nextMonthStartDate = Date.newInstance(currentYear, currentMonth + 1, 1);
                endDate = nextMonthStartDate.addDays(-1);
            }
        }

        if(currentMonth == 12){
            monthlyEndDate = Date.newInstance(currentYear, 12, 31);
        } else {
            nextMonthStartDate = Date.newInstance(currentYear, currentMonth + 1, 1);
            monthlyEndDate = nextMonthStartDate.addDays(-1);
        }

        System.assertEquals(4, stmtList.size(), 'Expected 4 Statements to be created.');
    }

    @isTest
    static void lateReconcileTest() {
        ServiceTerritory fac = [
            SELECT Id 
            FROM ServiceTerritory 
            WHERE Name = 'Apex Test Service Territory 4'
        ];
        Date today = Date.today();

        ACG_Facility_Adjustment__c fa = new ACG_Facility_Adjustment__c(
            Facility_Adjustment_Name__c = 'Late FA',
            Service_Territory__c = fac.Id,
            ACG_Status__c = 'Active',
            ACG_No_of_Payments__c = 1,
            ACG_Start_Date__c = Date.newInstance(today.year(), today.month() - 1, 1),
            ACG_Payment_Amount__c = 100
        );
        insert fa;

        Test.startTest();
        Database.executeBatch(new AAAStatementCreationBatch(), 200);
        Test.stopTest();

        List<Invoice__c> invcList = [
            SELECT Id
            FROM Invoice__c
            WHERE Facility_Adjustment__c = :fa.Id
        ];

        System.assertEquals(1, invcList.size(), 'Expected 1 Invoice to be created.');
    }
}