unpackaged/main/default/objects/Account/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Facility.recordType-meta.xml
<RecordType>
    <fullName>Facility</fullName>
    <active>true</active>
    <label>Facility</label>
</RecordType>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/ACG_Facility_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment</label>
    <nameField>
        <displayFormat>FA-{000}</displayFormat>
        <label>Facility Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Deprecate?) Facility Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Adjustment_Category__c.field-meta.xml
<CustomField>
    <fullName>ACG_Adjustment_Category__c</fullName>
    <label>Adjustment Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAR</fullName>
            </value>
            <value>
                <fullName>Advances</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Basic Reciprocal</fullName>
            </value>
            <value>
                <fullName>Battery and Battery Charger Costs</fullName>
            </value>
            <value>
                <fullName>Battery Warranty Reserve-Club Assist</fullName>
            </value>
            <value>
                <fullName>Battery Warranty Reserve-Interstate</fullName>
            </value>
            <value>
                <fullName>BKGRND</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Damage</fullName>
            </value>
            <value>
                <fullName>Fuel Subsidy</fullName>
            </value>
            <value>
                <fullName>GOODYEAR</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Interstate Battery</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Reciprocal</fullName>
            </value>
            <value>
                <fullName>Overdrawn</fullName>
            </value>
            <value>
                <fullName>Plus</fullName>
            </value>
            <value>
                <fullName>Plus Reciprocal</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Premier Reciprocal</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>RV Reciprocal</fullName>
            </value>
            <value>
                <fullName>Sign On Bonus</fullName>
            </value>
            <value>
                <fullName>Sonsio</fullName>
            </value>
            <value>
                <fullName>Tablets</fullName>
            </value>
            <value>
                <fullName>Truck Lease</fullName>
            </value>
            <value>
                <fullName>Truck Purchase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>ACG_Adjustment_Type__c</fullName>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Adjustments_Remaining__c.field-meta.xml
<CustomField>
    <fullName>ACG_Adjustments_Remaining__c</fullName>
    <formula>ACG_No_of_Payments__c  -  ACG_Adjustments_Made__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adjustments Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>ACG_Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Status__c.field-meta.xml
<CustomField>
    <fullName>ACG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Facility_Adjustment_Name__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment_Name__c</fullName>
    <label>Facility Adjustment Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST#{00000000}</displayFormat>
        <label>Statement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Statement__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AAAFacilityAdjustmentInvoicingBatch_Test.cls
@IsTest
public class AAAFacilityAdjustmentInvoicingBatch_Test {

    private static Integer NUM_FA = 10;
    private static Integer NUM_STMT = 5;
    //          query = 'SELECT Id,Service_Territory__c,ACG_Adjustment_Category__c, ACG_Adjustment_Type__c,ACG_Payment_Amount__c FROM ACG_Facility_Adjustment__c WHERE ACG_Status__c = \'Active\' AND ACG_Adjustments_Remaining__c > 0';
//SELECT Id,Service_Territory__c,Start_Date__c FROM Statement__c WHERE Service_Territory__c IN: setFacilityId AND Start_Date__c =: Date.Today()
//
    @TestSetup
    static void setup() {
        OperatingHours hours = new OperatingHours();
        hours.Name = 'Test Hours';
        hours.TimeZone = 'America/New_York';
        insert hours;
        
        ServiceTerritory testTerritory = new ServiceTerritory();
        testTerritory.Name = 'Test Territory';
        testTerritory.OperatingHoursId = hours.Id;
        insert testTerritory;
        
        Id facilityRecordTypeId  = EP.getRecordTypeId(Account.SObjectType, 'Facility');
        Account objFacility1 = ACG_TestDataFactory.createAccounts(facilityRecordTypeId,1,false,false)[0];
        insert objFacility1 ;
        
		// create some ACG_Facility_Adjustment__c records
        List<ACG_Facility_Adjustment__c> records = new List<ACG_Facility_Adjustment__c>();
        for(Integer i=0; i<NUM_FA; i++) {
            ACG_Facility_Adjustment__c rec = new ACG_Facility_Adjustment__c();
            rec.ACG_Status__c = 'Active';
            rec.Facility_Adjustment_Name__c = 'Test FA Name ' + i;
            rec.Service_Territory__c = testTerritory.Id;
            rec.ACG_Adjustment_Category__c='BATTERY';
            rec.ACG_Adjustment_Type__c='Debit';
            rec.ACG_Payment_Amount__c=4734.00;
            rec.Account__c = objFacility1.Id ; 
            records.add(rec);
        }
        insert records;
        
        // create some statements
        List<Statement__c> statements = new List<Statement__c>();
        for(Integer i=0; i<NUM_STMT; i++) {
            Statement__c stmt = new Statement__c();
            stmt.Service_Territory__c = testTerritory.Id;
            stmt.Start_Date__c = Date.Today();
            statements.add(stmt);
        }
        insert statements;
    }
    
    @IsTest
    static void testBatch() {
        Test.startTest();
        // Instantiate your batch class and call the start method
        AAAFacilityAdjustmentInvoicingBatch batchInstance = new AAAFacilityAdjustmentInvoicingBatch();
        Id batchProcessId = Database.executeBatch(batchInstance);
        // Assert that the returned QueryLocator is not null and contains expected data
        Test.stopTest();
        List<Invoice__c> invoices = [SELECT Id,Name FROM Invoice__c];
        Assert.areEqual(NUM_FA, invoices.size(), 'Expected invoices for each ACG_Facility_Adjustment__c');
    }
    
}