unpackaged/main/default/objects/Account/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACURA</fullName>
            </value>
            <value>
                <fullName>ADVANCE MIXER</fullName>
            </value>
            <value>
                <fullName>ALFA ROMEO</fullName>
            </value>
            <value>
                <fullName>ALLSTATE</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMERICAN AUSTIN</fullName>
            </value>
            <value>
                <fullName>AMERICAN BANTAM</fullName>
            </value>
            <value>
                <fullName>AMERICAN COACH</fullName>
            </value>
            <value>
                <fullName>AMERICAN EAGLE</fullName>
            </value>
            <value>
                <fullName>AMERICAN HERITAGE</fullName>
            </value>
            <value>
                <fullName>AMERICAN IRONHORSE</fullName>
            </value>
            <value>
                <fullName>AMERICAN LAFRANCE</fullName>
            </value>
            <value>
                <fullName>AMERICAN QUANTUM</fullName>
            </value>
            <value>
                <fullName>AMERICAN SUNDIRO</fullName>
            </value>
            <value>
                <fullName>ANTHEM</fullName>
            </value>
            <value>
                <fullName>APEX</fullName>
            </value>
            <value>
                <fullName>APOLLO</fullName>
            </value>
            <value>
                <fullName>APRILIA</fullName>
            </value>
            <value>
                <fullName>ARNOLT-MG</fullName>
            </value>
            <value>
                <fullName>ARROWHEAD</fullName>
            </value>
            <value>
                <fullName>ASPEN</fullName>
            </value>
            <value>
                <fullName>ASTON MARTIN</fullName>
            </value>
            <value>
                <fullName>ATK</fullName>
            </value>
            <value>
                <fullName>AUBURN</fullName>
            </value>
            <value>
                <fullName>AUDI</fullName>
            </value>
            <value>
                <fullName>AUSTIN HEALEY</fullName>
            </value>
            <value>
                <fullName>AUSTIN ROVER</fullName>
            </value>
            <value>
                <fullName>AUTOCAR</fullName>
            </value>
            <value>
                <fullName>AUTOCAR LLC.</fullName>
            </value>
            <value>
                <fullName>AVALANCHE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Master_Vehicle__c/ACG_Master_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Master Vehicle</label>
    <nameField>
        <label>Master Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Vehicle</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Master_Vehicle__c/fields/ACG_Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>ACG_Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACG_Master_Vehicle__c/fields/ACG_Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>ACG_Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ERS_Case_VehicleType_Mapping__mdt/ERS_Case_VehicleType_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>ERS_Case VehicleType Mapping</label>
    <pluralLabel>ERS_Case VehicleType Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ERS_Case_VehicleType_Mapping__mdt/fields/Vehicle_Type_Case__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type_Case__c</fullName>
    <label>Vehicle Type (Case)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2M (2-Wheeled Motorcycle)</fullName>
                <default>true</default>
                <label>2M (2-Wheeled Motorcycle)</label>
            </value>
            <value>
                <fullName>3M (3 - Wheeled Motorcycle)</fullName>
            </value>
            <value>
                <fullName>4M (ATV)</fullName>
            </value>
            <value>
                <fullName>BK (Bicycles)</fullName>
            </value>
            <value>
                <fullName>DW (Dual Wheels)</fullName>
            </value>
            <value>
                <fullName>GC (Golf Cart)</fullName>
            </value>
            <value>
                <fullName>PS (Passenger Car/Truck)</fullName>
            </value>
            <value>
                <fullName>R1 (RV &lt; 23 feet)</fullName>
            </value>
            <value>
                <fullName>R2 (RV 24-32 feet)</fullName>
            </value>
            <value>
                <fullName>R3 (RV &gt; 33 feet)</fullName>
            </value>
            <value>
                <fullName>SM (Snowmobile)</fullName>
            </value>
            <value>
                <fullName>TR (Trailer)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ERS_Case_VehicleType_Mapping__mdt/fields/Vehicle_Type_Master_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type_Master_Vehicle__c</fullName>
    <label>Vehicle Type (Master Vehicle)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/FSL_Member_Vehicle__c.object-meta.xml
<CustomObject>
    <label>Member Vehicle</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/ACG_Member__c.field-meta.xml
<CustomField>
    <fullName>ACG_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Member Vehicles</relationshipLabel>
    <relationshipName>Member_Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/ACG_Member_Household__c.field-meta.xml
<CustomField>
    <fullName>ACG_Member_Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Member_Vehicles1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/Vehicle_Color__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Color__c</fullName>
    <label>Vehicle Color</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/Vehicle_Plate__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Plate__c</fullName>
    <description>Copied from Case//EMI</description>
    <label>Vehicle Plate</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/Vehicle_State__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_State__c</fullName>
    <label>Vehicle State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Member_Vehicle__c/fields/Vehicle_Year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Year__c</fullName>
    <label>Vehicle Year</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Type__c/Vehicle_Type__c.object-meta.xml
<CustomObject>
    <label>Vehicle Type</label>
    <nameField>
        <label>Vehicle Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ACG_GetMemberVehiclesFrom_Vehicles.cls
/************************************************************************************
Apex Class Name     : ACG_GetRecordsFrom_MasterVehicle
Created Date        : 27th Sept 2021
Function            : Get the records from Master Vehicle 
Author              : Deloitte Consulting 
*************************************************************************************/

public class ACG_GetMemberVehiclesFrom_Vehicles {
    @AuraEnabled(cacheable=false)
    Public static List<FSL_Member_Vehicle__c> getMemberVehicles(Id AccountId){
        Id customer_RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ACG_Member').getRecordTypeId();
        if(AccountId != NULL){
            // ----------- Commented out by SF team as ACE and NE doesn't use Financial Service cloud ------------
         	/*Id household_RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
            List<AccountContactRelation> lstHouseholdAccounts = [SELECT AccountId,Contact.AccountId
                                                                FROM AccountContactRelation 
                                                                WHERE ContactId IN (SELECT PersonContactId
                                                                                    FROM Account
                                                                                    WHERE Id =:AccountId) 
                                                                AND Account.RecordTypeId =: household_RecordTypeId LIMIT 1];
            if(!lstHouseholdAccounts.isEmpty()){
                Id householdId = lstHouseholdAccounts[0].AccountId;
                List<FSL_Member_Vehicle__c> lstMemberVehicles=[SELECT Id,Name 
                                                       FROM FSL_Member_Vehicle__c
                                                       WHERE ACG_Member_Household__c= :householdId];
                if(!lstMemberVehicles.isEmpty()) {
                    lstMemberVehicles.sort();
                    return lstMemberVehicles;
                }
            }*/
            //else {
            Account accObj = new Account();
            accObj = [SELECT RecordTypeId  FROM Account WHERE Id =:AccountId];
                if(accObj.RecordTypeId == customer_RecordTypeId){
                List<FSL_Member_Vehicle__c> lstMemberVehicles = [SELECT Id,Name FROM FSL_Member_Vehicle__c
                                                                WHERE ACG_Member__c= : AccountId];
                  if(!lstMemberVehicles.isEmpty()) {
                    lstMemberVehicles.sort();
                    return lstMemberVehicles;
                }
                }
            //}
        }
        return NULL;
    }

    @AuraEnabled(cacheable = true)
    public static String getVehicleType(Id memberVehicle){
        FSL_Member_Vehicle__c vehicleInfo = [SELECT Id, Vehicle_Type__c 
                                             FROM FSL_Member_Vehicle__c 
                                             WHERE Id =:memberVehicle
                                             LIMIT 1];
        
        List<ERS_Case_VehicleType_Mapping__mdt> mdtRec = new List<ERS_Case_VehicleType_Mapping__mdt>();
        if( String.isNotBlank(vehicleInfo.Vehicle_Type__c)){
           mdtRec.add([SELECT Id, Vehicle_Type_Case__c, Vehicle_Type_Master_Vehicle__c
                                                          FROM ERS_Case_VehicleType_Mapping__mdt
                                                          WHERE Vehicle_Type_Master_Vehicle__c = :vehicleInfo.Vehicle_Type__c LIMIT 1]);
        }
            
        String retVal = '';
        if(!mdtRec.isEmpty()){
            retVal = mdtRec[0].Vehicle_Type_Case__c;
        }
            return retVal;
        
    }

    @AuraEnabled(cacheable = true)
    public static String getVehicleDetails(Id vehicleId){
        ACG_Master_Vehicle__c vehicleInfo = new ACG_Master_Vehicle__c();
        try{
            vehicleInfo = [SELECT Id
                                                , Vehicle_Type__c 
                                                , ACG_Vehicle_Make__c
                                                , ACG_Vehicle_Model__c
                                                , ACG_Vehicle_Year__c
                                                FROM ACG_Master_Vehicle__c 
                                                WHERE Id =:vehicleId
                                                LIMIT 1];
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return JSON.serialize(vehicleInfo);
    }

    @AuraEnabled(cacheable=false)
    public static FSL_Member_Vehicle__c getMemberVehicleDetail(Id memberVehicleId){
        List<FSL_Member_Vehicle__c> results = [
                                            SELECT Id,
                                            Vehicle_Year__c,
                                            Vehicle_Make__c,
                                            Vehicle_Model__c,
                                            Vehicle_Color__c,
                                            Vehicle_Type__c,
            								Vehicle_Plate__c, //added for plate2vin AGB 6/3/2025 SSFI-245
            								Vehicle_State__c //added for plate2vin AGB 6/3/2025 SSFI-245
                                            FROM FSL_Member_Vehicle__c 
                                            WHERE Id =:memberVehicleId
                                            LIMIT 1];
        

        return !results.isEmpty() ? results[0] : null;
        
    }

    @AuraEnabled(cacheable = true)
    public static String mapVehicleType(String masterVehicleType){
        List<ERS_Case_VehicleType_Mapping__mdt> mdtRec = [SELECT Vehicle_Type_Case__c
                                                          FROM ERS_Case_VehicleType_Mapping__mdt
                                                          WHERE Vehicle_Type_Master_Vehicle__c = :masterVehicleType LIMIT 1];
                                                                     
        String retVal = '';
        if(!mdtRec.isEmpty()){
            retVal = mdtRec[0].Vehicle_Type_Case__c;
        }
        return retVal;
        
    }
}