unpackaged/main/default/objects/Reciprocal__c/Reciprocal__c.object-meta.xml
<CustomObject>
    <label>Reciprocal</label>
    <nameField>
        <displayFormat>REC-{000}</displayFormat>
        <label>Reciprocal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reciprocals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reciprocal__c/fields/CDX_Authorization_Code__c.field-meta.xml
<CustomField>
    <fullName>CDX_Authorization_Code__c</fullName>
    <label>CDX Authorization Code</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Cost_Buffer__c.field-meta.xml
<CustomField>
    <fullName>Cost_Buffer__c</fullName>
    <label>Cost Buffer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Is_Duplicate__c.field-meta.xml
<CustomField>
    <fullName>Is_Duplicate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Duplicate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Member_ClubCode__c.field-meta.xml
<CustomField>
    <fullName>Member_ClubCode__c</fullName>
    <label>Member Club Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_First_Name__c</fullName>
    <label>Member First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <label>Member ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Member_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Last_Name__c</fullName>
    <label>Member Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Membership_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiration_Date__c</fullName>
    <label>Membership Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Call_Date__c</fullName>
    <label>Service Call Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Call_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Call_ID__c</fullName>
    <label>Service Call ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Call_Tow_Miles__c.field-meta.xml
<CustomField>
    <fullName>Service_Call_Tow_Miles__c</fullName>
    <label>Service Call Tow Miles</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Call_Trouble_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Call_Trouble_Code__c</fullName>
    <label>Service Call Trouble Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T0</fullName>
                <label>T0 - GOA/Canceled Call</label>
            </value>
            <value>
                <fullName>T1</fullName>
                <label>T1 - Flat tire with a spare</label>
            </value>
            <value>
                <fullName>T2</fullName>
                <label>T2 - Flat with no spare</label>
            </value>
            <value>
                <fullName>T3</fullName>
                <label>T3 - Battery related service</label>
            </value>
            <value>
                <fullName>T4</fullName>
                <label>T4 - Cannot start</label>
            </value>
            <value>
                <fullName>T5</fullName>
                <label>T5 - Fuel delivery</label>
            </value>
            <value>
                <fullName>T6</fullName>
                <label>T6 - Tow</label>
            </value>
            <value>
                <fullName>T7</fullName>
                <label>T7 - Lockout</label>
            </value>
            <value>
                <fullName>T8</fullName>
                <label>T8 - Extrication (Winch out)</label>
            </value>
            <value>
                <fullName>T9</fullName>
                <label>T9 - Miscellaneous</label>
            </value>
            <value>
                <fullName>3B</fullName>
                <label>3B - Battery Replacement</label>
            </value>
            <value>
                <fullName>7A</fullName>
                <label>7A - Key delivery</label>
            </value>
            <value>
                <fullName>7B</fullName>
                <label>7B - Locksmith service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Club_Code__c</fullName>
    <label>Service Club Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Facility_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Facility_ID__c</fullName>
    <label>Service Facility ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
            <value>
                <fullName>Write-Off</fullName>
            </value>
            <value>
                <fullName>Rebilled</fullName>
            </value>
            <value>
                <fullName>Manually Billed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Overturned Dispute</fullName>
            </value>
            <value>
                <fullName>Waiting on Club</fullName>
            </value>
            <value>
                <fullName>Hold For Next File</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <isActive>false</isActive>
                <label>Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Submitting_Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Submitting_Club_Code__c</fullName>
    <label>Submitting Club Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Total_Dollar_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Dollar_Amount__c</fullName>
    <label>Total Dollar Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PAY</fullName>
            </value>
            <value>
                <fullName>ACP</fullName>
            </value>
            <value>
                <fullName>ERR</fullName>
            </value>
            <value>
                <fullName>DSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/recordTypes/Inbound_Payment_Requests.recordType-meta.xml
<RecordType>
    <fullName>Inbound_Payment_Requests</fullName>
    <active>true</active>
    <label>Inbound Payment Requests</label>
</RecordType>

unpackaged/main/default/objects/Reciprocal__c/recordTypes/Outbound_Payment_Requests.recordType-meta.xml
<RecordType>
    <fullName>Outbound_Payment_Requests</fullName>
    <active>true</active>
    <label>Outbound Payment Requests</label>
</RecordType>

unpackaged/main/default/classes/FSL_ReciprocalApexClassTest.cls
@isTest
public class FSL_ReciprocalApexClassTest {
    private static Id obRecRT = Schema.SObjectType.Reciprocal__c
        .getRecordTypeInfosByDeveloperName()
        .get('Outbound_Payment_Requests')
        .getRecordTypeId();
    private static Id ibRecRT = Schema.SObjectType.Reciprocal__c
        .getRecordTypeInfosByDeveloperName()
        .get('Inbound_Payment_Requests')
        .getRecordTypeId();

    @isTest
    public static void reciprocalTests() {
        Reciprocal__c rec = new Reciprocal__c(
            CDX_Authorization_Code__c = '19268307',
            Service_Call_Date__c = Date.parse('01/31/2024'),
            Membership_Expiration_Date__c = Date.parse('07/07/2024'),
            Member_ClubCode__c = '212',
            Total_Dollar_Amount__c = 224.71,
            Member_ID__c = '236360602',
            Service_Club_Code__c = '240',
            Submitting_Club_Code__c = '240',
            Service_Facility_ID__c = '33',
            Service_Call_Tow_Miles__c = 42,
            Service_Call_ID__c = '49463',
            Member_Last_Name__c = 'Bedard',
            Member_First_Name__c = 'Olivia',
            recordTypeId = obRecRT,
            Cost_Buffer__c = 'TEST/REC/BON/12345',
            Service_Call_Trouble_Code__c = 'T5'
        );

        Test.startTest();
        insert rec;

        Reciprocal__c recold = [
            SELECT Id, Total_Dollar_Amount__c 
            FROM Reciprocal__c
        ];
        
        recold.Cost_Buffer__c = 'TEST/REC/BON/12445';
        update recold;

        Reciprocal__c recnew = [
            SELECT Id, Cost_Buffer__c, Total_Dollar_Amount__c 
            FROM Reciprocal__c
        ];
        Test.stopTest();

        System.assertEquals(225.71, recnew.Total_Dollar_Amount__c, 'Failed test.');
    }

    @isTest
    public static void checkIBDuplicatesTest() {
        Boolean hasError = true;
        Reciprocal__c ogRec = new Reciprocal__c(
            CDX_Authorization_Code__c = '19268307',
            Service_Call_Date__c = Date.parse('01/31/2024'),
            Membership_Expiration_Date__c = Date.parse('07/07/2024'),
            Member_ClubCode__c = '212',
            Total_Dollar_Amount__c = 224.71,
            Member_ID__c = '236360602',
            Service_Club_Code__c = '240',
            Submitting_Club_Code__c = '240',
            Service_Facility_ID__c = '33',
            Service_Call_Tow_Miles__c = 42,
            Service_Call_ID__c = '49463',
            Member_Last_Name__c = 'Bedard',
            Member_First_Name__c = 'Olivia',
            recordTypeId = ibRecRT,
            Cost_Buffer__c = 'TEST/REC/BON/12345',
            Service_Call_Trouble_Code__c = 'T5'
        );
        insert ogRec;

        Reciprocal__c dupeRec = new Reciprocal__c(
            CDX_Authorization_Code__c = '19268307',
            Service_Call_Date__c = Date.parse('01/31/2024'),
            Membership_Expiration_Date__c = Date.parse('07/07/2024'),
            Member_ClubCode__c = '212',
            Total_Dollar_Amount__c = 224.71,
            Member_ID__c = '236360602',
            Service_Club_Code__c = '240',
            Submitting_Club_Code__c = '240',
            Service_Facility_ID__c = '33',
            Service_Call_Tow_Miles__c = 42,
            Service_Call_ID__c = '49463',
            Member_Last_Name__c = 'Bedard',
            Member_First_Name__c = 'Olivia',
            recordTypeId = ibRecRT,
            Cost_Buffer__c = 'TEST/REC/BON/12345',
            Service_Call_Trouble_Code__c = 'T5'
        );

        try {
            insert dupeRec;
            hasError = false;
        } catch (Exception e) {
            System.debug(e.getMessage());
        }

        List<Reciprocal__c> resRecList = [
            SELECT
                Id,
                is_Duplicate__c
            FROM Reciprocal__c
            WHERE Id IN :new List<String>{ogRec.Id, dupeRec.Id}
        ];

        for (Reciprocal__c rec : resRecList) {
            System.assertEquals(true, rec.is_Duplicate__c, 'Failed to mark duplicate for Reciprocal.');
        }
    }
    
    /**EMI - SSFI-380**/
     // create test data for the Reciprocal__c object
    private static Reciprocal__c createReciprocalRecord(String status, String transactionType) {
        Reciprocal__c rec = new Reciprocal__c();
        rec.Status__c = status;
        rec.Transaction__c = transactionType;
        insert rec;
        return rec;
    }

    // Test case for when the status is changed to 'Approved' and the transaction is 'PAY'
    @isTest
    static void testTransactionTypeUpdatedToPay() {
        // Create old record
        Reciprocal__c oldRec = createReciprocalRecord('New', 'PAY');
        
        // Create a new record and simulate a status change
        Reciprocal__c newRec = [SELECT Id, Status__c, Transaction__c FROM Reciprocal__c WHERE Id = :oldRec.Id];
        newRec.Status__c = 'Approved';

        // Simulate the old and new map
        Map<Id, Reciprocal__c> oldMap = new Map<Id, Reciprocal__c>{oldRec.Id => oldRec};
        Map<Id, Reciprocal__c> newMap = new Map<Id, Reciprocal__c>{newRec.Id => newRec};

        // Call the method 
        Test.startTest();
        FSL_ReciprocalApexClass.updateTransactionTypeOnStatusChange(oldMap, newMap);
        Test.stopTest();

        // Verify the transaction type is updated to 'PAY'
        newRec = [SELECT Id, Transaction__c FROM Reciprocal__c WHERE Id = :oldRec.Id];
        System.assertEquals('PAY', newRec.Transaction__c);
    }
    
    // Test case for when the status is changed to 'Rebilled' and the transaction is 'PAY'
    @isTest
    static void testTransactionTypeUpdatedToDSP() {
        // Create old record
        Reciprocal__c oldRec = createReciprocalRecord('New', 'DSP');
        
        // Create a new record and simulate a status change
        Reciprocal__c newRec = [SELECT Id, Status__c, Transaction__c FROM Reciprocal__c WHERE Id = :oldRec.Id];
        newRec.Status__c = 'Rebilled';

        // Simulate the old and new map
        Map<Id, Reciprocal__c> oldMap = new Map<Id, Reciprocal__c>{oldRec.Id => oldRec};
        Map<Id, Reciprocal__c> newMap = new Map<Id, Reciprocal__c>{newRec.Id => newRec};

        // Call the method being tested
        Test.startTest();
        FSL_ReciprocalApexClass.updateTransactionTypeOnStatusChange(oldMap, newMap);
        Test.stopTest();

        // Verify the transaction type is updated to 'DSP'
        newRec = [SELECT Id, Transaction__c FROM Reciprocal__c WHERE Id = :oldRec.Id];
        System.assertEquals('DSP', newRec.Transaction__c);
    }
    
    // Test case for when the status is changed to 'Rebilled' and the transaction is 'ACP'
    @isTest
    static void testTransactionTypeUpdatedToERR() {
        // Create old record
        Reciprocal__c oldRec = createReciprocalRecord('New', 'ERR');
        
        // Create a new record and simulate a status change
        Reciprocal__c newRec = [SELECT Id, Status__c, Transaction__c FROM Reciprocal__c WHERE Id = :oldRec.Id];
        newRec.Status__c = 'Rebilled';

        // Simulate the old and new map
        Map<Id, Reciprocal__c> oldMap = new Map<Id, Reciprocal__c>{oldRec.Id => oldRec};
        Map<Id, Reciprocal__c> newMap = new Map<Id, Reciprocal__c>{newRec.Id => newRec};

        // Call the method being tested
        Test.startTest();
        FSL_ReciprocalApexClass.updateTransactionTypeOnStatusChange(oldMap, newMap);
        Test.stopTest();

        // Verify the transaction type is updated to 'ERR'
        newRec = [SELECT Id, Transaction__c FROM Reciprocal__c WHERE Id = :oldRec.Id];
        System.assertEquals('ERR', newRec.Transaction__c);
    }

    // Test case for when the status remains the same (no update expected)
    @isTest
    static void testNoStatusChange() {
        // Create old record
        Reciprocal__c oldRec = createReciprocalRecord('New', 'PAY');
        
        // No status change
        Reciprocal__c newRec = [SELECT Id, Status__c, Transaction__c FROM Reciprocal__c WHERE Id = :oldRec.Id];
        
        // Simulate the old and new map
        Map<Id, Reciprocal__c> oldMap = new Map<Id, Reciprocal__c>{oldRec.Id => oldRec};
        Map<Id, Reciprocal__c> newMap = new Map<Id, Reciprocal__c>{newRec.Id => newRec};

        // Call the method being tested
        Test.startTest();
        FSL_ReciprocalApexClass.updateTransactionTypeOnStatusChange(oldMap, newMap);
        Test.stopTest();

        // Verify the transaction type has not changed
        newRec = [SELECT Id, Transaction__c FROM Reciprocal__c WHERE Id = :oldRec.Id];
        System.assertEquals('PAY', newRec.Transaction__c);
    }
	/**EMI - SSFI-380**/
}