unpackaged/main/default/objects/Reciprocal__c/Reciprocal__c.object-meta.xml
<CustomObject>
    <label>Reciprocal</label>
    <nameField>
        <displayFormat>REC-{000}</displayFormat>
        <label>Reciprocal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reciprocals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reciprocal__c/fields/Cost_Buffer__c.field-meta.xml
<CustomField>
    <fullName>Cost_Buffer__c</fullName>
    <label>Cost Buffer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Is_Duplicate__c.field-meta.xml
<CustomField>
    <fullName>Is_Duplicate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Duplicate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Long_Tow_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Long_Tow_Indicator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Long Tow Indicator</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Member_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_First_Name__c</fullName>
    <label>Member First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Member_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Last_Name__c</fullName>
    <label>Member Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Call_Date__c</fullName>
    <label>Service Call Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Call_Trouble_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Call_Trouble_Code__c</fullName>
    <label>Service Call Trouble Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T0</fullName>
                <label>T0 - GOA/Canceled Call</label>
            </value>
            <value>
                <fullName>T1</fullName>
                <label>T1 - Flat tire with a spare</label>
            </value>
            <value>
                <fullName>T2</fullName>
                <label>T2 - Flat with no spare</label>
            </value>
            <value>
                <fullName>T3</fullName>
                <label>T3 - Battery related service</label>
            </value>
            <value>
                <fullName>T4</fullName>
                <label>T4 - Cannot start</label>
            </value>
            <value>
                <fullName>T5</fullName>
                <label>T5 - Fuel delivery</label>
            </value>
            <value>
                <fullName>T6</fullName>
                <label>T6 - Tow</label>
            </value>
            <value>
                <fullName>T7</fullName>
                <label>T7 - Lockout</label>
            </value>
            <value>
                <fullName>T8</fullName>
                <label>T8 - Extrication (Winch out)</label>
            </value>
            <value>
                <fullName>T9</fullName>
                <label>T9 - Miscellaneous</label>
            </value>
            <value>
                <fullName>3B</fullName>
                <label>3B - Battery Replacement</label>
            </value>
            <value>
                <fullName>7A</fullName>
                <label>7A - Key delivery</label>
            </value>
            <value>
                <fullName>7B</fullName>
                <label>7B - Locksmith service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Total_Dollar_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Dollar_Amount__c</fullName>
    <label>Total Dollar Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/recordTypes/Inbound_Payment_Requests.recordType-meta.xml
<RecordType>
    <fullName>Inbound_Payment_Requests</fullName>
    <active>true</active>
    <label>Inbound Payment Requests</label>
</RecordType>

unpackaged/main/default/objects/Reciprocal__c/recordTypes/Outbound_Payment_Requests.recordType-meta.xml
<RecordType>
    <fullName>Outbound_Payment_Requests</fullName>
    <active>true</active>
    <label>Outbound Payment Requests</label>
</RecordType>

unpackaged/main/default/classes/ReciprocalTriggerHandlerTest.cls
@isTest
private class ReciprocalTriggerHandlerTest {
    @TestSetup
    static void createTestData() {
                Id recordTypeId = Schema.SObjectType.Reciprocal__c.getRecordTypeInfosByDeveloperName().get('Inbound_Payment_Requests').getRecordTypeId();

        Reciprocal__c r = new Reciprocal__c();
            r.Member_First_Name__c = 'Wanda';
            r.Member_Last_Name__c = 'Doe';
            r.Service_Call_Date__c = System.today();
            r.Service_Call_Trouble_Code__c = 'T1';
            r.RecordTypeId = recordTypeId;
            r.Cost_Buffer__c = 'PLS/02100/:BAS/07250/:BON/0';
            insert r;
    }

    @isTest 
    static void test_CostBufferChange(){
        List<Reciprocal__c> rs = [Select Id, is_Duplicate__c from Reciprocal__c where Member_First_Name__c='Wanda'];
        rs[0].Cost_Buffer__c = 'PLS/02100/:BAS/07250/:BON/1248' ; 
        rs[0].Total_Dollar_Amount__c = 0 ; 

        update rs[0]; 

        List<Reciprocal__c> rs_afterChange = [Select Id, is_Duplicate__c,Total_Dollar_Amount__c from Reciprocal__c where Member_First_Name__c='Wanda'];
        System.assertEquals(12.00, rs_afterChange[0].Total_Dollar_Amount__c);
    }
    
    
    @isTest
    static void insertDupe(){
      Id recordTypeId = Schema.SObjectType.Reciprocal__c.getRecordTypeInfosByDeveloperName().get('Inbound_Payment_Requests').getRecordTypeId();

       Reciprocal__c r = new Reciprocal__c();
        r.Member_First_Name__c = 'Wanda';
        r.Member_Last_Name__c = 'Doe';
        r.Service_Call_Date__c = System.today();
        r.Service_Call_Trouble_Code__c = 'T1';
        r.RecordTypeId = recordTypeId;
        insert r;
        
        List<Reciprocal__c> rs = [Select Id, is_Duplicate__c from Reciprocal__c where Is_Duplicate__c=true];
        
        System.assertEquals(rs.size(),2, 'Should be both marked as duplicate');        
        
    }
    
        @isTest
    static void insertDifferentRt(){
      Id recordTypeId = Schema.SObjectType.Reciprocal__c.getRecordTypeInfosByDeveloperName().get('Outbound_Payment_Requests').getRecordTypeId();

       Reciprocal__c r = new Reciprocal__c();
        r.Member_First_Name__c = 'Wanda';
        r.Member_Last_Name__c = 'Doe';
        r.Service_Call_Trouble_Code__c = 'T1';
        r.RecordTypeId = recordTypeId;
        r.Service_Call_Date__c = System.today();
        insert r;
        
        List<Reciprocal__c> rs = [Select Id, is_Duplicate__c from Reciprocal__c where Is_Duplicate__c=true];
        
        System.assertEquals(rs.size(),0, 'Should be  no duplicate');        
        
    }
    
        @isTest
    static void insertDupeWithCaseDiffernce(){
      Id recordTypeId = Schema.SObjectType.Reciprocal__c.getRecordTypeInfosByDeveloperName().get('Inbound_Payment_Requests').getRecordTypeId();

       Reciprocal__c r = new Reciprocal__c();
        r.Member_First_Name__c = 'WanDa';
        r.Member_Last_Name__c = 'DoE';
        r.Service_Call_Date__c = System.today();
        r.Service_Call_Trouble_Code__c = 'T1';
        r.RecordTypeId = recordTypeId;
        insert r;
        
        List<Reciprocal__c> rs = [Select Id, is_Duplicate__c from Reciprocal__c where Is_Duplicate__c=true];
        
        System.assertEquals(rs.size(),2, 'Should be both marked as duplicate');        
        
    }
    
    
        @isTest
    static void insertNoDupe(){
      Id recordTypeId = Schema.SObjectType.Reciprocal__c.getRecordTypeInfosByDeveloperName().get('Inbound_Payment_Requests').getRecordTypeId();

       Reciprocal__c r = new Reciprocal__c();
        r.Member_First_Name__c = 'Wendy';
        r.Member_Last_Name__c = 'Doe';
        r.Service_Call_Date__c = System.today();
        r.Service_Call_Trouble_Code__c = 'T1';
        r.RecordTypeId = recordTypeId;
        insert r;
        
        List<Reciprocal__c> rs = [Select Id, is_Duplicate__c from Reciprocal__c where Is_Duplicate__c=true];
        
        System.assertEquals(rs.size(),0, 'Should be no duplicates');        
        
    }
    
    @isTest
    static void insertTwoDupes(){
        Id recordTypeId = Schema.SObjectType.Reciprocal__c.getRecordTypeInfosByDeveloperName().get('Inbound_Payment_Requests').getRecordTypeId();

        List <Reciprocal__c> rs = new List<Reciprocal__c>();
       Reciprocal__c r = new Reciprocal__c();
        r.Member_First_Name__c = 'Mandy';
        r.Member_Last_Name__c = 'Doe';
        r.Service_Call_Date__c = System.today();
        r.Service_Call_Trouble_Code__c = 'T1';
        r.RecordTypeId = recordTypeId;

       rs.add(r);
              Reciprocal__c r2 = new Reciprocal__c();
        r2.Member_First_Name__c = 'Mandy';
        r2.Member_Last_Name__c = 'Doe';
        r2.Service_Call_Date__c = System.today();
        r2.Service_Call_Trouble_Code__c = 'T1';
        r2.Long_Tow_Indicator__c = true;
        r2.RecordTypeId = recordTypeId;

       rs.add(r2);
        insert rs;
        
        rs = [Select Id, is_Duplicate__c from Reciprocal__c where Is_Duplicate__c=true and Member_First_Name__c='Mandy'];
        
        System.assertEquals(rs.size(),2, 'Should be two duplicates');        
        
    }
    
    
}