unpackaged/main/default/objects/Case/fields/ACG_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ACG_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Tow</fullName>
            </value>
            <value>
                <fullName>Flat Tire</fullName>
            </value>
            <value>
                <fullName>Vehicle Lockout</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Extrication</fullName>
            </value>
            <value>
                <fullName>Home Lockout</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
            <value>
                <fullName>Extrication Tow Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Allotted_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Allotted_Mileage__c</fullName>
    <label>Allotted Mileage</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Over_Miles__c.field-meta.xml
<CustomField>
    <fullName>Over_Miles__c</fullName>
    <label>Over Miles</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Total_Mileage__c.field-meta.xml
<CustomField>
    <fullName>Total_Mileage__c</fullName>
    <label>Total Mileage</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vehicle_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Fuel_Type__c</fullName>
    <label>Vehicle Fuel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gas</fullName>
                <label>Gasoline</label>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>FLEX</fullName>
            </value>
            <value>
                <fullName>FULL HYBRID EV-FLEX (FHEV)</fullName>
            </value>
            <value>
                <fullName>FULL HYBRID EV-GAS (FHEV)</fullName>
            </value>
            <value>
                <fullName>BATTERY EV (EV/BEV)</fullName>
            </value>
            <value>
                <fullName>FUEL CELL EV (FCEV)</fullName>
            </value>
            <value>
                <fullName>PLUG-IN HYBRID EV-GAS (PHEV)</fullName>
            </value>
            <value>
                <fullName>MILD HYBRID EV-GAS (MHEV)</fullName>
            </value>
            <value>
                <fullName>BI-FUEL</fullName>
            </value>
            <value>
                <fullName>BIODIESEL</fullName>
            </value>
            <value>
                <fullName>ELECTRIC/GAS</fullName>
            </value>
            <value>
                <fullName>U/K</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>BATTERY W/RANGE EXT (BEV REX)</fullName>
                <isActive>false</isActive>
                <label>BATTERY W/RANGE EXT (BEV REX)</label>
            </value>
            <value>
                <fullName>CNG</fullName>
                <isActive>false</isActive>
                <label>CNG</label>
            </value>
            <value>
                <fullName>ELECTRIC/DIESEL</fullName>
                <isActive>false</isActive>
                <label>ELECTRIC/DIESEL</label>
            </value>
            <value>
                <fullName>LPG</fullName>
                <isActive>false</isActive>
                <label>LPG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ERS_Case_Guidance_Success_Mapping__mdt/ERS_Case_Guidance_Success_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>ERS Case Guidance Success Mapping</label>
    <pluralLabel>ERS Case Guidance Success Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ERS_Case_Guidance_Success_Mapping__mdt/fields/Case_Guidance_Success_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Guidance_Success_Status__c</fullName>
    <label>Case Guidance Success Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ERS_Case_Guidance_Success_Mapping__mdt/fields/Guidance_Success__c.field-meta.xml
<CustomField>
    <fullName>Guidance_Success__c</fullName>
    <label>Guidance Success</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ERS_Case_Guidance_Success_Mapping__mdt/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Plus</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Plus RV</fullName>
            </value>
            <value>
                <fullName>Premier RV</fullName>
            </value>
            <value>
                <fullName>Classic</fullName>
                <isActive>false</isActive>
                <label>Classic</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ERS_Case_Guidance_Success_Mapping__mdt/fields/Name_of_Triage_Tab__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Triage_Tab__c</fullName>
    <inlineHelpText>Triage tab on which the script needs to be displayed.</inlineHelpText>
    <label>Name of Triage Tab</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Home Lockout</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
            <value>
                <fullName>Member/Contact</fullName>
            </value>
            <value>
                <fullName>Tow</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Flat Tire</fullName>
            </value>
            <value>
                <fullName>Extrication</fullName>
            </value>
            <value>
                <fullName>Vehicle Lockout</fullName>
            </value>
            <value>
                <fullName>Accident</fullName>
                <isActive>false</isActive>
                <label>Accident</label>
            </value>
            <value>
                <fullName>Bicycle</fullName>
                <isActive>false</isActive>
                <label>Bicycle</label>
            </value>
            <value>
                <fullName>Lockout</fullName>
                <isActive>false</isActive>
                <label>Lockout</label>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
                <isActive>false</isActive>
                <label>Motorcycle</label>
            </value>
            <value>
                <fullName>RV</fullName>
                <isActive>false</isActive>
                <label>RV</label>
            </value>
            <value>
                <fullName>Submit</fullName>
                <isActive>false</isActive>
                <label>Submit</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ERS_Case_Guidance_Success_Mapping__mdt/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accident</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Bicycle</fullName>
                <isActive>false</isActive>
                <label>Bicycle</label>
            </value>
            <value>
                <fullName>Extrication</fullName>
            </value>
            <value>
                <fullName>Flat Tire</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Home Lockout</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
            <value>
                <fullName>Tow</fullName>
            </value>
            <value>
                <fullName>Vehicle Lockout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ERS_Case_Guidance_Success_Mapping__mdt/fields/Vehicle_Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Fuel_Type__c</fullName>
    <label>Vehicle Fuel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gasoline</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>EV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ERS_Case_GuidanceSuccessMappingTest.cls
@isTest
public class ERS_Case_GuidanceSuccessMappingTest {
    //@testSetup
    public static void testSetup(){
        Id ERS_RecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ACG_ERS').getRecordTypeId();
        Case caseRec = new Case();
        caseRec.RecordTypeId = ERS_RecTypeId;
        caseRec.ACG_Service_Type__c = 'Fuel';
        caseRec.Vehicle_Fuel_Type__c = 'Gas';
        caseRec.Subject = '@Test GuidanceSuccess Rec#';
        insert caseRec;
    }
    @isTest
    public static void getGuidanceTest_DefaultMsg(){
        String CurrentTab = 'Tow';
        List<ERS_Case_Guidance_Success_Mapping__mdt> mdtList = [SELECT  Case_Guidance_Success_Status__c,
                                                                        Guidance_Success__c,
                                                                        Name_of_Triage_Tab__c
                                                                FROM ERS_Case_Guidance_Success_Mapping__mdt
                                                                WHERE Name_of_Triage_Tab__c =:CurrentTab
                                                                AND Case_Guidance_Success_Status__c = 'Active'
                                                               LIMIT 1];
         List<String> GS_MSgs = ERS_Case_GuidanceSuccessMapping.getGuidance(NULL, NULL,NULL,NULL,NULL, NULL, CurrentTab, NULL, NULL);
        
        if( !mdtList.isEmpty() && !GS_MSgs.isEmpty()){
            system.assertEquals(true,GS_MSgs.contains(mdtList[0].Guidance_Success__c), 'Error getting the GS message;;;'+GS_MSgs+';;;'+mdtList[0].Guidance_Success__c);
        }
    }
    @isTest
    public static void getGuidanceTest(){
        Id ERS_RecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ACG_ERS').getRecordTypeId();
        Case caseRec = new Case();
        caseRec.RecordTypeId = ERS_RecTypeId;
        caseRec.ACG_Service_Type__c = 'Fuel';
        caseRec.Vehicle_Fuel_Type__c = 'Gas';
        caseRec.Subject = '@Test GuidanceSuccess Rec#';
        insert caseRec;
        System.debug(caseRec);
        
        String CurrentTab = 'Fuel';
        List<ERS_Case_Guidance_Success_Mapping__mdt> mdtList = [SELECT  Case_Guidance_Success_Status__c,
                                                                        Guidance_Success__c,
                                                                        Service_Type__c,
                                                                        Vehicle_Fuel_Type__c,
                                                                        Name_of_Triage_Tab__c
                                                                FROM ERS_Case_Guidance_Success_Mapping__mdt
                                                                WHERE Name_of_Triage_Tab__c =:CurrentTab
                                                                    AND Case_Guidance_Success_Status__c = 'Active'
                                                                    AND Service_Type__c = 'Fuel'
                                                                    AND Vehicle_Fuel_Type__c = 'Gas'
                                                                LIMIT 1];
        
        //Case caseRec = [SELECT Id,ACG_Service_Type__c,Vehicle_Fuel_Type__c FROM Case WHERE Subject='@Test GuidanceSuccess Rec#' LIMIT 1];
                                                                            //String ServType, Id AccountId, String FuelType, String VehicleType,String BSPAvailable, String FlatTireStatus,String CurrentTab)
        List<String> GS_MSgs = ERS_Case_GuidanceSuccessMapping.getGuidance(caseRec.ACG_Service_Type__c, NULL,caseRec.Vehicle_Fuel_Type__c,NULL,NULL, NULL, CurrentTab, NULL, NULL);
        if( !mdtList.isEmpty() && !GS_MSgs.isEmpty()){
            system.assertEquals(true,GS_MSgs.contains(mdtList[0].Guidance_Success__c), 'Error getting the GS message');
        }
    }
    
    @isTest
    public static void parseGuidanceMessage_Test(){
        Id ERS_RecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ACG_ERS').getRecordTypeId();
        Case caseRec = new Case();
        caseRec.RecordTypeId = ERS_RecTypeId;
        caseRec.ACG_Service_Type__c = 'Tow';
        caseRec.Allotted_Mileage__c = 50;
        caseRec.Subject = '#Test ERSCase Rec#';
        insert caseRec;
        
        ERS_Case_Guidance_Success_Mapping__mdt mdtRec = [SELECT Id,Guidance_Success__c,DeveloperName FROM ERS_Case_Guidance_Success_Mapping__mdt WHERE DeveloperName = 'BR_Tow_Tab_3' LIMIT 1];
        String parsedMsg ;

        Test.startTest();
        //Test Scenario 1 (towMiles > Allotted Mileage)
        parsedMsg = ERS_Case_GuidanceSuccessMapping.parseGuidanceMessage('Test_Membership_Level','75', caseRec.Id, mdtRec);
        String expectedMsg = mdtRec.Guidance_Success__c;
        expectedMsg = expectedMsg.replace('{Membership_Level__c}','Test_Membership_Level');
        expectedMsg = expectedMsg.replace('{Allotted_Mileage__c}','25');
        expectedMsg = expectedMsg.replace('{Over_Miles__c}','25');
        expectedMsg = expectedMsg.replace('{Total_Mileage__c}','25');

        System.assertEquals(expectedMsg, parsedMsg, 'ERROR');

        //Test Scenario 2 (towMiles < Allotted Mileage)
        parsedMsg = ERS_Case_GuidanceSuccessMapping.parseGuidanceMessage('Test_Membership_Level','25', caseRec.Id, mdtRec);
        expectedMsg = '<p style="color:red">You are using '+'25'+' miles out of your allotted '+'50'+' miles.</p>';
        System.assertEquals(expectedMsg, parsedMsg, 'ERROR');

        Test.stopTest();

        //Test Scenario 3 (towMiles = 0 / NULL)
        parsedMsg = ERS_Case_GuidanceSuccessMapping.parseGuidanceMessage('Test_Membership_Level','0', caseRec.Id, mdtRec);
        System.assertEquals(NULL, parsedMsg, 'ERROR');
        
        parsedMsg = ERS_Case_GuidanceSuccessMapping.parseGuidanceMessage('Test_Membership_Level',NULL, caseRec.Id, mdtRec);
        System.assertEquals(NULL, parsedMsg, 'ERROR');
        
        //Test Scenario 4 (Allotted Mileage = NULL)
        caseRec.Allotted_Mileage__c = NULL;
        update caseRec;
        
        parsedMsg = ERS_Case_GuidanceSuccessMapping.parseGuidanceMessage('Test_Membership_Level','75', caseRec.Id, mdtRec);
        System.assertEquals(NULL,parsedMsg , 'ERROR');
    }
}