unpackaged/main/default/objects/Case/fields/ACG_Make__c.field-meta.xml
<CustomField>
    <fullName>ACG_Make__c</fullName>
    <label>Vehicle Make</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Model__c.field-meta.xml
<CustomField>
    <fullName>ACG_Model__c</fullName>
    <label>Vehicle Model</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Vehicle_Location_Address__c.field-meta.xml
<CustomField>
    <fullName>ACG_Vehicle_Location_Address__c</fullName>
    <label>Vehicle Location Address</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Year__c.field-meta.xml
<CustomField>
    <fullName>ACG_Year__c</fullName>
    <description>Vehicle manufacturing year. Populated via Car Care Appointment Page</description>
    <label>Vehicle Year</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vehicle_Location_City__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Location_City__c</fullName>
    <label>Vehicle Location City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vehicle_Location_Country__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Location_Country__c</fullName>
    <label>Vehicle Location Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vehicle_Location_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Location_Postal_Code__c</fullName>
    <label>Vehicle Location Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Vehicle_Location_Street__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Location_Street__c</fullName>
    <label>Vehicle Location Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Application_Log__c/FSL_Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>AN-{00000000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Unscheduling</fullName>
            </value>
            <value>
                <fullName>Glympse</fullName>
            </value>
            <value>
                <fullName>CallCreate</fullName>
            </value>
            <value>
                <fullName>GlympseOut</fullName>
            </value>
            <value>
                <fullName>GlympseIn</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>AddressChange</fullName>
            </value>
            <value>
                <fullName>RoutingChange</fullName>
            </value>
            <value>
                <fullName>LKL</fullName>
            </value>
            <value>
                <fullName>Call Clear</fullName>
            </value>
            <value>
                <fullName>ETALog</fullName>
            </value>
            <value>
                <fullName>IVRLookup</fullName>
            </value>
            <value>
                <fullName>ServiceTrackingLog</fullName>
            </value>
            <value>
                <fullName>WOCreateEventLog</fullName>
            </value>
            <value>
                <fullName>WOStatusUpdateLog</fullName>
            </value>
            <value>
                <fullName>RetrieveWorkOrders</fullName>
            </value>
            <value>
                <fullName>Update Facility</fullName>
            </value>
            <value>
                <fullName>Delayed Copy to Clear Queue</fullName>
            </value>
            <value>
                <fullName>CalculateDistanceInMiles</fullName>
            </value>
            <value>
                <fullName>ServiceLineItemFailed</fullName>
            </value>
            <value>
                <fullName>ValidateWaitTime</fullName>
            </value>
            <value>
                <fullName>CalculatedMileage</fullName>
            </value>
            <value>
                <fullName>Clear Queue</fullName>
            </value>
            <value>
                <fullName>UpsertResourceAbsence</fullName>
            </value>
            <value>
                <fullName>WOJeopardyAPI</fullName>
            </value>
            <value>
                <fullName>National Repair Shop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Success_Message__c.field-meta.xml
<CustomField>
    <fullName>Success_Message__c</fullName>
    <label>Success Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Success_Record_Count__c.field-meta.xml
<CustomField>
    <fullName>Success_Record_Count__c</fullName>
    <label>Success Record Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(Optimization_Request__r.FSL__Type__c)</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Integration_Settings__c/fields/Extra_Header_Value__c.field-meta.xml
<CustomField>
    <fullName>Extra_Header_Value__c</fullName>
    <label>Extra Header Value</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Settings__c/fields/Header_Value__c.field-meta.xml
<CustomField>
    <fullName>Header_Value__c</fullName>
    <label>Header Value</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CMC</fullName>
            </value>
            <value>
                <fullName>CORE</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FSL_INTRepairShopOutboundTest.cls
@isTest
public class FSL_INTRepairShopOutboundTest {
    
    private class RestMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req){
            String fullJson = '{"access_token":"1234","data":{"statusCode":200,"code":"E200","message":"success"}}';  
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            res.setStatus('OK');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    
    @testSetup
    public static void testSetup(){
        
        Integration_Settings__c nationalOAuthAPI = new Integration_Settings__c();
        nationalOAuthAPI.Name = 'National_OAuth_API';
        nationalOAuthAPI.Method__c = 'POST';
        nationalOAuthAPI.Enpoint_URL__c = 'https://api-qa.national.aaa.com/common/oauth2/token';        
        nationalOAuthAPI.Extra_Header_Value__c = 'grant_type=client_credentials&client_id=1234&client_secret=4565';
        nationalOAuthAPI.Request_Timeout__c = 120000;
        nationalOAuthAPI.Header_Value__c = '[{"key":"Content-Type","value":"application/x-www-form-urlencoded"}]';
        insert nationalOAuthAPI;
        
        Integration_Settings__c repairShopOutboundAPI = new Integration_Settings__c();
        repairShopOutboundAPI.Name = 'RepairShop_Outbound_API';
        repairShopOutboundAPI.Method__c = 'POST';
        repairShopOutboundAPI.Enpoint_URL__c = 'https://api-qa.national.aaa.com/automotive/services/ci/v1/rsp/orders';        
        repairShopOutboundAPI.Request_Timeout__c = 120000;
        repairShopOutboundAPI.Header_Value__c = '[{"key":"Content-Type","value":"application/json"}]';
        insert repairShopOutboundAPI;
        
        Integration_Settings__c testSetting = new Integration_Settings__c();
        testSetting.Name = 'Test Setting';
        testSetting.Method__c = 'GET';
        testSetting.Enpoint_URL__c = 'www.test.com';
        testSetting.Path__c = '/test';
        testSetting.Extra_Header_Value__c = '[{"key":"Authorization","value":"Bearer:kj93lkjlksfj"}]';
        testSetting.Named_Credential__c = 'Test_Cred';
        testSetting.Request_Timeout__c = 12;
        testSetting.Path__c = 'Test_Path';
        testSetting.Header_Value__c = '[{"key":"Content-Type","value":"application/json"}]';
        insert testSetting;
        
        Account testAcct = new Account();
        testAcct.Name = 'Test Acct';
        insert testAcct;
        
        Case testCase = new Case();
        testCase.ACG_Vehicle_Location_Address__c = '153 Midland Ave, East Orange, NJ 07017, USA';
        testCase.Tow_Geolocation__Longitude__s = -74.0919171;
        testCase.Tow_Geolocation__Latitude__s = 40.885276;
        testCase.Source__c = 'Salesforce';
        testCase.ACG_Year__c = '2024';
        testCase.ACG_Model__c = 'Sierra 1500';
        testCase.ACG_Make__c = 'GMC';
        testCase.Vehicle_Location_Street__c = '6455 W Archer Ave';
        testCase.Vehicle_Location_City__c = 'Chicago';
        testCase.Vehicle_Location_Postal_Code__c = '60638';
        testCase.Vehicle_Location_Country__c = 'USA';
        insert testCase;
        
        WorkOrder testWO = new WorkOrder();
        testWO.CaseId = testCase.Id;
        testWO.AccountId = testAcct.Id;
        insert testWO;
    }
    
    @isTest
    public static void testFetchCase(){
        Id caseId = [SELECT Id FROM Case WHERE Source__c = 'Salesforce'].Id;
        
        Test.startTest();
            
            Case response = FSL_INTRepairShopOutbound.fetchCase(caseId);
        
        Test.stopTest();
        
        System.assertNotEquals(null, response);
    }
    
    @isTest
    public static void testGenerateRepairShopRequest(){
        Id caseId = [SELECT Id FROM Case WHERE Source__c = 'Salesforce'].Id;
        Id workOrderId = [SELECT Id FROM WorkOrder WHERE Case.Source__c = 'Salesforce'].Id;
        
        Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
        
            FSL_INTRepairShopOutbound.generateRepairShopRequest(CaseId, workOrderId);
        
        Test.stopTest();
        
        List<FSL_Application_Log__c> logs = [SELECT Id, Name, API_Name__c, Operation__c, Response_Body__c, 
                                             Request_Body__c, Success_Message__c, Success_Record_Count__c, 
                                             Type__c, Work_Order__c 
                                             FROM FSL_Application_Log__c
                                             WHERE Operation__c = 'National Repair Shop'];
        system.debug('logs >> ' + logs);
        system.assertEquals('National Repair Shop Outbound API - Success', logs[0].API_Name__c);
    }
    
}