unpackaged/main/default/objects/Case/fields/FSL_Alias__c.field-meta.xml
<CustomField>
    <fullName>FSL_Alias__c</fullName>
    <label>Alias</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>FSL_Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Contractor__c.field-meta.xml
<CustomField>
    <fullName>FSL_Contractor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contractor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Email__c.field-meta.xml
<CustomField>
    <fullName>FSL_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_First_Name__c.field-meta.xml
<CustomField>
    <fullName>FSL_First_Name__c</fullName>
    <label>First Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>FSL_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Nickname__c.field-meta.xml
<CustomField>
    <fullName>FSL_Nickname__c</fullName>
    <label>Nickname</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Primary_Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>FSL_Primary_Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>User Provisioning Requests</relationshipLabel>
    <relationshipName>User_Provisioning_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Profile__c.field-meta.xml
<CustomField>
    <fullName>FSL_Profile__c</fullName>
    <inlineHelpText>Technician = Driver.Dispatcher = Dispatcher.Combo: Driver &amp; dispatch access.</inlineHelpText>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FSL_Contractor__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Club Dispatcher</fullName>
            </value>
            <value>
                <fullName>Facility Dispatcher</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Dispatcher</fullName>
            </value>
            <value>
                <fullName>Technician &amp; Dispatcher Combo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Re_Activate__c.field-meta.xml
<CustomField>
    <fullName>FSL_Re_Activate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re Activate</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>FSL_Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_User__c.field-meta.xml
<CustomField>
    <fullName>FSL_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserCases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/FSL_Username__c.field-meta.xml
<CustomField>
    <fullName>FSL_Username__c</fullName>
    <label>Username</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/classes/FSL_CaseTriggerHandler_Test.cls
@isTest
private without sharing class FSL_CaseTriggerHandler_Test {
    
                               
    static testmethod void handleUserDeProvisioningRequestTest() {
    
    Test.starttest();
        List<User> userList = [SELECT id, firstName, lastName 
                               FROM USER WHERE alias IN ('T_Fleet','D_Fleet')];
        list<ServiceTerritory> serterlist = [select id from ServiceTerritory LIMIT 1]; 
        map<string, string> userResourcesMap = new map<string, string>();
        for(ServiceResource sr : [select id,RelatedRecordId from ServiceResource where RelatedRecordId IN :userList]){
	        userResourcesMap.put(sr.RelatedRecordId, sr.id);
    	}
    
        list<Case> cases = new list<Case>();
        for(User u : [Select id, Name, IsActive, LastLoginDate, EmployeeNumber, 
                                                    profile.Name, IsPortalEnabled, email 
                                               from User 
                                               where IsActive=true and 
                                                    ID IN :userResourcesMap.keySet()])
        {
            Case cs = new case(fsl_user__c = u.id, 
                               recordtypeId=Schema.SObjectType.Case.getRecordTypeInfosByName().get('User De-Provisioning Request').getRecordTypeId(), 
                               origin='OnDemand',
                               FSL_Service_Resource__c = userResourcesMap.get(u.id)
                              ); 
            cases.add(cs);
           
        }
        insert cases;
        for(case cs : cases){
            cs.fsl_approval_status__c = 'Approved';
            cs.Origin='Automation';
        }
        update cases;
        Test.stoptest();
        list<User> updated_users = [Select id, Name, IsActive, lastname, alias, LastLoginDate, EmployeeNumber, username, 
                                                    profile.Name, IsPortalEnabled, email 
                                               from User 
                                               where ID IN :userResourcesMap.keySet()];
        system.debug('updated_users: '+updated_users);
        system.assertequals(false, updated_users[0].isactive); 
    }
        
    static testmethod void handleUserReactivation() {
        User user = [SELECT id, Name, IsActive, lastname, alias, LastLoginDate, EmployeeNumber, username, 
                                                    profile.Name, IsPortalEnabled, email
                               FROM USER WHERE alias = 'D_Fleet'];
        user.isactive=false;
        update user;
        
        list<ServiceTerritory> serterlist = [select id from ServiceTerritory LIMIT 1];         
       	User admin = [select id from user where alias = 'C_Admin'];
        //reactivate the user
        system.runas(admin){
            Case cs = new Case();
            cs.Status = 'New';
            cs.FSL_User__c = user.id;
            cs.FSL_Email__c = user.email;
            cs.FSL_Primary_Service_Territory__c = serterlist[0].id;
            cs.FSL_First_Name__c = 'Test First Name3';
            cs.FSL_Username__c  = user.username;
            cs.FSL_Last_Name__c = user.lastname;
            cs.FSL_Email__c = user.email;
            cs.FSL_Alias__c  = user.alias;  
            cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('User Provisioning Request').getRecordTypeId();
            cs.FSL_Nickname__c = user.alias;
            cs.FSL_Re_Activate__c = true;
            cs.FSL_Contractor__c = true;
            cs.FSL_Profile__c = 'Facility Dispatcher'; 
            try{
                Test.startTest();
            	insert cs;
                Test.stopTest();
            }catch(exception e){
                system.debug('exception');
            }
        }
    }
    
    static testmethod void handleUserProvisioningRequestTest(){
      Test.starttest();
        list<ServiceTerritory> serterlist = [select id from ServiceTerritory LIMIT 1];    
        List<Case> CreateCs = FSL_DataFactory.CreateUserProvisionCase(serterlist[0].id);
        
      Test.stoptest();
    }
    
    static testmethod void PortalTesting (){
        
        List<User> userlist= [Select id from user where alias = 'C_Admin'];
       
                 ServiceResource sr = [select id from ServiceResource where ResourceType ='T' LIMIT 1];
        list<ServiceTerritory> serterlist = [select id from ServiceTerritory LIMIT 1];
         List<ServiceTerritoryMember> newSTMList = new List<ServiceTerritoryMember>();
            ServiceTerritoryMember serTerMem = FSL_DataFactory.createServiceTerritoryMember(sr.Id, serterlist[0].Id);
        newSTMList.add(serTerMem);
    }

   @testSetup
    public static void dataSetup() {
        FSL_DataFactoryUtility.userdataSetup();
    } 
    
    
}