unpackaged/main/default/objects/ACG_Facility_Adjustment__c/ACG_Facility_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment</label>
    <nameField>
        <displayFormat>FA-{000}</displayFormat>
        <label>Facility Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Adjustment_Category__c.field-meta.xml
<CustomField>
    <fullName>ACG_Adjustment_Category__c</fullName>
    <label>Adjustment Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAR</fullName>
            </value>
            <value>
                <fullName>Advances</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Basic Reciprocal</fullName>
            </value>
            <value>
                <fullName>Battery and Battery Charger Costs</fullName>
            </value>
            <value>
                <fullName>Battery Warranty Reserve-Club Assist</fullName>
            </value>
            <value>
                <fullName>Battery Warranty Reserve-Interstate</fullName>
            </value>
            <value>
                <fullName>BKGRND</fullName>
            </value>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Damage</fullName>
            </value>
            <value>
                <fullName>Fuel Subsidy</fullName>
            </value>
            <value>
                <fullName>GOODYEAR</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Interstate Battery</fullName>
            </value>
            <value>
                <fullName>NSF</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other Reciprocal</fullName>
            </value>
            <value>
                <fullName>Overdrawn</fullName>
            </value>
            <value>
                <fullName>Plus</fullName>
            </value>
            <value>
                <fullName>Plus Reciprocal</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Premier Reciprocal</fullName>
            </value>
            <value>
                <fullName>Rent</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>RV Reciprocal</fullName>
            </value>
            <value>
                <fullName>Sign On Bonus</fullName>
            </value>
            <value>
                <fullName>Sonsio</fullName>
            </value>
            <value>
                <fullName>Tablets</fullName>
            </value>
            <value>
                <fullName>Truck Lease</fullName>
            </value>
            <value>
                <fullName>Truck Purchase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>ACG_Adjustment_Type__c</fullName>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Adjustments_Remaining__c.field-meta.xml
<CustomField>
    <fullName>ACG_Adjustments_Remaining__c</fullName>
    <formula>ACG_No_of_Payments__c  -  ACG_Adjustments_Made__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adjustments Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ACG_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_No_of_Payments__c.field-meta.xml
<CustomField>
    <fullName>ACG_No_of_Payments__c</fullName>
    <defaultValue>1</defaultValue>
    <label>No. of Payments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>ACG_Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ACG_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Status__c.field-meta.xml
<CustomField>
    <fullName>ACG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Reactivation_Date__c.field-meta.xml
<CustomField>
    <fullName>Reactivation_Date__c</fullName>
    <description>Users must populate this field upon reactivation from &#39;Deferred&#39; status. This date will then create Invoices starting on an unreconciled Statement with the same start date as this field.</description>
    <inlineHelpText>Users must populate this field upon reactivation from &#39;Deferred&#39; status. This date will then create Invoices starting on an unreconciled Statement with the same start date as this field.</inlineHelpText>
    <label>Reactivation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/ACG_Facility_Adjustment_Payment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment Payment</label>
    <nameField>
        <displayFormat>FAP-{000}</displayFormat>
        <label>Facility Adjustment Payment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustment Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/ACG_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>ACG_Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/ACG_Status__c.field-meta.xml
<CustomField>
    <fullName>ACG_Status__c</fullName>
    <description>Visible to System Admin only, read-only for all other users. Gets updated when Invoice.Status__c is updated. 

Implemented this way for Facility Adjustment object to reference as filter criteria for roll-up summary fields.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Facility Adjustment Payments</relationshipLabel>
    <relationshipName>Facility_Adjustment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment_Payment__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>System Admin only field. Helps differentiate which FAP belongs to which Invoice in ACG_CreateFacilityAdjustments Apex class.</description>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Facility Adjustment Payments</relationshipLabel>
    <relationshipName>Facility_Adjustment_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Adjustment</label>
    <referenceTo>ACG_Facility_Adjustment__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bi-monthly</fullName>
                <default>true</default>
                <label>Bi-monthly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/recordTypes/Facility_Territory.recordType-meta.xml
<RecordType>
    <fullName>Facility_Territory</fullName>
    <active>true</active>
    <description>Territory that handles all types of services</description>
    <label>Facility Territory</label>
</RecordType>

unpackaged/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST#{00000000}</displayFormat>
        <label>Statement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Statement__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Unreconciled</fullName>
                <default>true</default>
                <label>Unreconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ACG_CreateFacilityAdjustmentsTest.cls
@isTest
public class ACG_CreateFacilityAdjustmentsTest {
    private static Organization orgData = [SELECT Id, Name FROM Organization LIMIT 1];
    private static Boolean isNEOrg = orgData.Name == 'AAA Northeast';
    private static RecordType facType = [
        SELECT Id 
        FROM RecordType 
        WHERE DeveloperName = 'Facility_Territory' 
        AND SobjectType = 'ServiceTerritory' 
        LIMIT 1
    ];

    static void setup() {
        OperatingHours opHrs = new OperatingHours(
            Name = 'Daytime',
            TimeZone = 'America/New_York'
        );
        insert opHrs;
        
        ServiceTerritory fac = new ServiceTerritory(
            Name = 'Test Service Territory',
            RecordTypeId = facType.Id,
            OperatingHoursId = opHrs.Id, 
            Payment_Schedule__c = 'Monthly',
            IsActive = true
        );
        insert fac;
        
        insert new Statement__c(
            Start_Date__c = Date.newInstance(2024, 2, 1),
            End_Date__c = Date.newInstance(2024, 2, 29),
            Service_Territory__c = fac.Id,
            Status__c = 'Unreconciled'
        );
        
        insert new ACG_Facility_Adjustment__c(
            ACG_Start_Date__c = Date.newinstance(2024, 2, 1),
            Service_Territory__c = fac.Id,
            ACG_Adjustment_Category__c = isNEOrg ? 'Interstate Battery' : 'BATTERY',
            ACG_Adjustment_Type__c = 'Debit',
            ACG_Status__c = 'Active',
            ACG_No_of_Payments__c = 1,
            ACG_Payment_Amount__c = 100            
        );
    }

    @isTest
    static void checkForDupeStmtsTest() {
        setup();

        ServiceTerritory fac = [SELECT Id FROM ServiceTerritory];
        Statement__c createdStmt = [
            SELECT Id, Status__c
            FROM Statement__c
            WHERE Service_Territory__c = :fac.Id
        ];

        insert new List<Statement__c> { 
            new Statement__c(
                Start_Date__c = Date.newInstance(2024, 3, 1),
                End_Date__c = Date.newInstance(2024, 3, 31),
                Service_Territory__c = fac.Id,
                Status__c = 'Unreconciled'
            ),
            new Statement__c(
                Start_Date__c = Date.newInstance(2024, 4, 1),
                End_Date__c = Date.newInstance(2024, 4, 30),
                Service_Territory__c = fac.Id,
                Status__c = 'Unreconciled'
            )
        };

        createdStmt.Status__c = 'Reconciled';
        update createdStmt;

        ACG_Facility_Adjustment__c fa = new ACG_Facility_Adjustment__c(
            ACG_Start_Date__c = Date.newinstance(2024, 2, 1),
            Service_Territory__c = fac.Id,
            ACG_Adjustment_Category__c = isNEOrg ? 'Interstate Battery' : 'BATTERY',
            ACG_Adjustment_Type__c = 'Debit',
            ACG_Status__c = 'Active',
            ACG_No_of_Payments__c = 2,
            ACG_Payment_Amount__c = 100            
        );
        insert fa;

        List<Invoice__c> invcList = [
            SELECT Id, Statement__r.Start_Date__c 
            FROM Invoice__c
            WHERE Facility_Adjustment__c = :fa.Id
        ];

        System.assertEquals(2, invcList.size(), 'Failed to create the correct number of Invoices.');

        List<Statement__c> stmtList = [
            SELECT Id, Start_Date__c
            FROM Statement__c
            WHERE Service_Territory__c = :fac.Id
        ];
        Set<Date> stmtDateSet = new Set<Date>();
        Boolean hasDuplicateStartDate = false;

        for (Statement__c stmt : stmtList) {
            Date stmtStartDate = stmt.Start_Date__c;

            if (!stmtDateSet.contains(stmtStartDate)) {
                stmtDateSet.add(stmtStartDate);
            } else {
                hasDuplicateStartDate = true;
                break;
            }
        }

        System.assertEquals(false, hasDuplicateStartDate, 'Created duplicate Statements.');
    }
    
    @isTest
    static void afterInsertTest() {
        // FA gets created in setup method which invokes class being tested
        setup();

        List<ACG_Facility_Adjustment__c> facAdj = [SELECT Id FROM ACG_Facility_Adjustment__c];
        List<Invoice__c> invoices = [SELECT Id FROM Invoice__c];

        System.assertEquals(facAdj.size(), invoices.size(), 'One invoice should be created');

        ServiceTerritory fac = [SELECT Id FROM ServiceTerritory];

        ACG_Facility_Adjustment__c fa = new ACG_Facility_Adjustment__c(
            ACG_Start_Date__c = Date.newinstance(2024, 1, 1),
            Service_Territory__c = fac.Id,
            ACG_Adjustment_Category__c = isNEOrg ? 'Interstate Battery' : 'BATTERY',
            ACG_Adjustment_Type__c = 'Debit',
            ACG_Status__c = 'Active',
            ACG_No_of_Payments__c = 2,
            ACG_Payment_Amount__c = 100            
        );
        insert fa;

        List<Invoice__c> invcList = [
            SELECT Id, Statement__r.Start_Date__c 
            FROM Invoice__c
            WHERE Facility_Adjustment__c = :fa.Id
        ];

        System.assertEquals(2, invcList.size(), 'Failed to create the correct number of Invoices.');

        Set<Date> stmtDateSet = new Set<Date>();
        Boolean hasDuplicateStartDate = false;

        for (Invoice__c invc : invcList) {
            Date stmtStartDate = invc.Statement__r.Start_Date__c;

            if (!stmtDateSet.contains(stmtStartDate)) {
                stmtDateSet.add(stmtStartDate);
            } else {
                hasDuplicateStartDate = true;
                break;
            }
        }

        System.assertEquals(false, hasDuplicateStartDate, 'Created duplicate Statements.');
    }
    
    @isTest
    static void futureMethodTest() {
        setup();
        
        String STATUS_ACTIVE = 'Active';
        List<ACG_Facility_Adjustment__c> lstFacAdj = [
            SELECT 
                Id, 
                ACG_Start_Date__c, 
                ACG_End_Date__c, 
                Service_Territory__c, 
                ACG_Adjustment_Category__c, 
                ACG_Adjustment_Type__c, 
                ACG_Payment_Amount__c, 
                ACG_Adjustments_Remaining__c, 
                ACG_Status__c,
                ACG_No_of_Payments__c,
                Reactivation_Date__c,
                Service_Territory__r.Payment_Schedule__c
            FROM ACG_Facility_Adjustment__c 
            WHERE ACG_Adjustments_Remaining__c > 0
            AND ACG_Status__c = :STATUS_ACTIVE
        ]; 
        
        Test.startTest();
        // Call the future method
        ACG_Facility_Adj_TriggerHandler.createFacAdjInvoices(lstFacAdj);
        Test.stopTest();
        
        // Assertions to verify the future method's effects
        List<Invoice__c> invcList = [SELECT Id FROM Invoice__c];
        System.assertEquals(1, invcList.size(), 'Expected 1 Invoice.');
    }

    @isTest
    static void newStatementTest() {
        setup();
        
        // Test for future date processing.
        Date validStartDate = Date.newinstance(2024, 3, 14); // create a Fac Adj with a date in the future
        Date validEndDate = Date.newinstance(2024, 3, 14);
        Date statementFutureStartDate = Date.newinstance(2024,3,01);
        ServiceTerritory serviceTerr = [SELECT Id FROM ServiceTerritory WHERE Name = 'Test Service Territory'];
        
        // Create Facility Adjustment record
        insert new ACG_Facility_Adjustment__c(
            ACG_Start_Date__c = validStartDate,
            Service_Territory__c = serviceTerr.Id,
            ACG_Adjustment_Category__c = isNEOrg ? 'Bonus': 'BASIC',
            ACG_Adjustment_Type__c = 'Debit',
            ACG_Status__c = 'Active',
            ACG_No_of_Payments__c = 1,
            ACG_Payment_Amount__c = 100            
        );
        
        // Assertions to verify that no new Statements were created
        List<Statement__c> stmt = [
            SELECT Id 
            FROM Statement__c 
            WHERE Start_Date__c =:statementFutureStartDate
        ];

        System.assertEquals(0, stmt.size(), 'No statement should be created');   
    }

    @isTest
    static void backdatedFATest() {
        Integer numPayments = 3;

        OperatingHours opHrs = new OperatingHours(
            Name = 'Daytime',
            TimeZone = 'America/New_York'
        );
        insert opHrs;
        
        ServiceTerritory fac = new ServiceTerritory(
            Name = 'Test Service Territory',
            RecordTypeId = facType.Id,
            OperatingHoursId = opHrs.Id, 
            Payment_Schedule__c = 'Bi-monthly',
            IsActive = true
        );
        insert fac;
        
        List<Statement__c> stmtList = new List<Statement__c>{
            new Statement__c(
                Start_Date__c 		 = Date.newInstance(2024, 2, 1),
                End_Date__c   		 = Date.newInstance(2024, 2, 15),
                Service_Territory__c = fac.Id,
                Status__c 		     = 'Unreconciled'
            ),
            new Statement__c(
                Start_Date__c 		 = Date.newInstance(2024, 2, 16),
                End_Date__c   		 = Date.newInstance(2024, 2, 29),
                Service_Territory__c = fac.Id,
                Status__c 		     = 'Unreconciled'
            ),
            new Statement__c(
                Start_Date__c 		 = Date.newInstance(2024, 3, 1),
                End_Date__c   		 = Date.newInstance(2024, 3, 15),
                Service_Territory__c = fac.Id,
                Status__c 		     = 'Unreconciled'
            ),
            new Statement__c(
                Start_Date__c 		 = Date.newInstance(2024, 3, 16),
                End_Date__c   		 = Date.newInstance(2024, 3, 31),
                Service_Territory__c = fac.Id,
                Status__c 		     = 'Unreconciled'
            )
        };
        insert stmtList;

        ACG_Facility_Adjustment__c fa = new ACG_Facility_Adjustment__c(
            ACG_Start_Date__c = Date.newinstance(2024, 1, 1),
            Service_Territory__c = fac.Id,
            ACG_Adjustment_Category__c = isNEOrg ? 'Interstate Battery' : 'BATTERY',
            ACG_Adjustment_Type__c = 'Debit',
            ACG_Status__c = 'Active',
            ACG_No_of_Payments__c = numPayments,
            ACG_Payment_Amount__c = 1000.0            
        );
        insert fa;

        // ACG_CreateFacilityAdjustments.processFacilityAdjustments(
        //     new List<ACG_Facility_Adjustment__c>{fa}
        // );

        List<Invoice__c> invcList = [
            SELECT Id, Statement_Date__c, Statement__c
            FROM Invoice__c 
            WHERE Facility_Adjustment__c = :fa.Id
            ORDER BY Statement_Date__c DESC
        ];
        List <ACG_Facility_Adjustment_Payment__c> fapList = [
            SELECT Id 
            FROM ACG_Facility_Adjustment_Payment__c
            WHERE ACG_Adjustment_ID__c = :fa.Id
        ];
        stmtList = [
            SELECT Id, Start_Date__c
            FROM Statement__c
        ];

        System.assertEquals(numPayments, invcList.size(), 'Failed to create the appropriate number of Invoices.');
        System.assertEquals(numPayments, fapList.size(), 'Failed to create the appropriate number of Facility Adjustment Payments.');

        Map<String, Statement__c> stmtMap = new Map<String, Statement__c>();

        for (Statement__c stmt : stmtList) {
            stmtMap.put(stmt.Id, stmt);
        }

        for (Invoice__c invc : invcList) {
            Statement__c stmt = stmtMap.get(invc.Statement__c);
    
            System.assertEquals(stmt.Start_Date__c, invc.Statement_Date__c, 'Failed to create the appropriate Invoice.');
        }
    }
}