unpackaged/main/default/objects/ACG_Facility_Adjustment__c/ACG_Facility_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment</label>
    <nameField>
        <displayFormat>FA-{000}</displayFormat>
        <label>Facility Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Adjustments_Remaining__c.field-meta.xml
<CustomField>
    <fullName>ACG_Adjustments_Remaining__c</fullName>
    <formula>ACG_No_of_Payments__c  -  ACG_Adjustments_Made__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adjustments Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ACG_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Status__c.field-meta.xml
<CustomField>
    <fullName>ACG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Adjustment</label>
    <referenceTo>ACG_Facility_Adjustment__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Statement_Status__c.field-meta.xml
<CustomField>
    <fullName>Statement_Status__c</fullName>
    <formula>TEXT(Statement__r.Status__c)</formula>
    <label>Statement Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AAACloseProcessedFacilityAdjustments.cls
public class AAACloseProcessedFacilityAdjustments implements Database.Batchable<sObject>, Schedulable {
    public String query;

    public Database.QueryLocator start(Database.BatchableContext BC) {
        query = 
            'SELECT '+
                'Id,'+
                'Facility_Adjustment__c,'+
                'Facility_Adjustment__r.ACG_Status__c,'+
                'Facility_Adjustment__r.ACG_End_Date__c'+
            ' FROM Invoice__c'+
            ' WHERE Statement_Status__c = \'Reconciled\''+
            ' AND Status__c = \'Submitted for Payment\''+
            ' AND Facility_Adjustment__r.ACG_Status__c NOT IN (\'Closed\', \'Deferred\', \'Cancelled\')'+
            ' AND Facility_Adjustment__r.ACG_Adjustments_Remaining__c = 0';
        
        return Database.getQueryLocator(query);         
    }
    
    public void execute(Database.BatchableContext BC, List<Invoice__c> scope) {
        Set<String> faIdSet = new Set<String>();
        List<ACG_Facility_Adjustment__c> faUpdateList = new List<ACG_Facility_Adjustment__c>();

        for (Invoice__c invc : scope) {
            String faId = invc.Facility_Adjustment__c;
            
            if (!faIdSet.contains(faId)) {
                ACG_Facility_Adjustment__c fa = invc.Facility_Adjustment__r;
                fa.ACG_Status__c = 'Closed';
                fa.ACG_End_Date__c = Date.Today();

                faUpdateList.add(fa);
                faIdSet.add(faId);
            }
        }
        
        if (faUpdateList != null && faUpdateList.size() > 0) {
            update faUpdateList;
        }
    }

    public void finish(Database.BatchableContext BC){
        // Finish Logic Here
    }

    public void execute(SchedulableContext ctx){
        AAACloseProcessedFacilityAdjustments batch = new AAACloseProcessedFacilityAdjustments();
        Database.executebatch(batch, 1000);
    }
}