unpackaged/main/default/objects/ACG_Facility_Adjustment__c/ACG_Facility_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Facility Adjustment</label>
    <nameField>
        <displayFormat>FA-{000}</displayFormat>
        <label>Facility Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facility Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Adjustments_Remaining__c.field-meta.xml
<CustomField>
    <fullName>ACG_Adjustments_Remaining__c</fullName>
    <formula>ACG_No_of_Payments__c  -  ACG_Adjustments_Made__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adjustments Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_End_Date__c.field-meta.xml
<CustomField>
    <fullName>ACG_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ACG_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/ACG_Status__c.field-meta.xml
<CustomField>
    <fullName>ACG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Deferred_On__c.field-meta.xml
<CustomField>
    <fullName>Deferred_On__c</fullName>
    <label>Deferred On</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Reactivated_On__c.field-meta.xml
<CustomField>
    <fullName>Reactivated_On__c</fullName>
    <label>Reactivated On</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Reactivation_Date__c.field-meta.xml
<CustomField>
    <fullName>Reactivation_Date__c</fullName>
    <description>Users must populate this field upon reactivation from &#39;Deferred&#39; status. This date will then create Invoices starting on an unreconciled Statement with the same start date as this field.</description>
    <inlineHelpText>Users must populate this field upon reactivation from &#39;Deferred&#39; status. This date will then create Invoices starting on an unreconciled Statement with the same start date as this field.</inlineHelpText>
    <label>Reactivation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACG_Facility_Adjustment__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Facility Adjustments</relationshipLabel>
    <relationshipName>Facility_Adjustments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FSL_Application_Log__c/FSL_Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>AN-{00000000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Unscheduling</fullName>
            </value>
            <value>
                <fullName>Glympse</fullName>
            </value>
            <value>
                <fullName>CallCreate</fullName>
            </value>
            <value>
                <fullName>GlympseOut</fullName>
            </value>
            <value>
                <fullName>GlympseIn</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>AddressChange</fullName>
            </value>
            <value>
                <fullName>RoutingChange</fullName>
            </value>
            <value>
                <fullName>LKL</fullName>
            </value>
            <value>
                <fullName>Call Clear</fullName>
            </value>
            <value>
                <fullName>ETALog</fullName>
            </value>
            <value>
                <fullName>IVRLookup</fullName>
            </value>
            <value>
                <fullName>ServiceTrackingLog</fullName>
            </value>
            <value>
                <fullName>WOCreateEventLog</fullName>
            </value>
            <value>
                <fullName>WOStatusUpdateLog</fullName>
            </value>
            <value>
                <fullName>RetrieveWorkOrders</fullName>
            </value>
            <value>
                <fullName>Update Facility</fullName>
            </value>
            <value>
                <fullName>Delayed Copy to Clear Queue</fullName>
            </value>
            <value>
                <fullName>CalculateDistanceInMiles</fullName>
            </value>
            <value>
                <fullName>ServiceLineItemFailed</fullName>
            </value>
            <value>
                <fullName>ValidateWaitTime</fullName>
            </value>
            <value>
                <fullName>CalculatedMileage</fullName>
            </value>
            <value>
                <fullName>Clear Queue</fullName>
            </value>
            <value>
                <fullName>UpsertResourceAbsence</fullName>
            </value>
            <value>
                <fullName>WOJeopardyAPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <label>Service Territory</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Adjustment</label>
    <referenceTo>ACG_Facility_Adjustment__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bi-monthly</fullName>
                <default>true</default>
                <label>Bi-monthly</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST#{00000000}</displayFormat>
        <label>Statement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Statement__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Unreconciled</fullName>
                <default>true</default>
                <label>Unreconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ACG_Facility_Adj_TriggerHandler.cls
/**
 * @description       : Creates Statements from Service Territories
 * @author            : ksarathy@salesforce.com
 * @group             : 
 * @last modified on  : 06-10-2024
 * @last modified by  : Josh Tupas
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   02-19-2024   ksarathy@salesforce.com
 *       05-24-2024   joshtupas@salesforce.com             Moved logic for deleting associated Invoices from "after delete" to "before delete" trigger
 *       06-05-2024   joshtupas@salesforce.com             Added logic to "backdate" activated FAs from a status of "Deferred"
 *       06-10-2024   joshtupas@salesforce.com             Added validation to require a "Reactivation Date" when activating deferred FAs. Added logic to ignore FA inserts that are future dated.
**/
public class ACG_Facility_Adj_TriggerHandler extends FSL_TriggerDispatcher.TriggerHandlerBase {
    List<ACG_Facility_Adjustment__c> newList = Trigger.new;
    List<ACG_Facility_Adjustment__c> oldList = Trigger.old;
    Map<Id, ACG_Facility_Adjustment__c> newMap = (Map<Id, ACG_Facility_Adjustment__c >) Trigger.newMap;
    Map<Id, ACG_Facility_Adjustment__c> oldMap = (Map<Id, ACG_Facility_Adjustment__c >) Trigger.oldMap;
    private static final String STATUS_ACTIVE = 'Active';
    private static final String STATUS_CANCELLED = 'Cancelled';
    private static final String STATUS_DEFERRED = 'Deferred';
    private static List<PicklistValueInfo> faStatusPicklist = [
        SELECT Label, Value 
        FROM PicklistValueInfo 
        WHERE EntityParticle.EntityDefinition.QualifiedApiName = 'ACG_Facility_Adjustment__c'
        AND EntityParticle.QualifiedApiName = 'ACG_Status__c' 
        AND IsActive = true 
    ];
    private static Id userProfileId = UserInfo.getProfileId();
    private static Id sysAdminProfileId = FSL_OrgCache.sysAdminProfileId();

    public override Boolean isDisabled() {
        return FSL_TriggerUtility.isDisabled('ACG_Facility_Adjustment__c');
    }
    
    public override void beforeInsert() {
        validateBeforeInsertUpdate(newList);
        applyDeferActiveDate(oldMap, oldList, newList);
    }

    public override void afterInsert() {
        createFacAdjInvoices(newList);
    }

    public override void beforeUpdate() {
        validateBeforeInsertUpdate(newList);
        applyDeferActiveDate(oldMap, oldList, newList);
    }

    public override void afterUpdate() {
        handleCancelledFacAdjs(newMap);
        handleDeferredActiveFAs(oldMap, newMap);
    }

    public override void beforeDelete() {
        validateBeforeDelete(oldList);
    }

    public static void validateBeforeInsertUpdate(List<ACG_Facility_Adjustment__c> newList) {
        if (newList != null) {
            List<String> statusLabelList = new List<String>();
            List<String> statusValueList = new List<String>();

            if (faStatusPicklist.size() > 0) {
                for (PicklistValueInfo pvi : faStatusPicklist) {
                    statusLabelList.add(pvi.Label);
                    statusValueList.add(pvi.Value);
                }
            }

            for (ACG_Facility_Adjustment__c newFA : newList) {
                String faStatus = newFA.ACG_Status__c;

                if (
                    userProfileId != sysAdminProfileId
                    && !statusValueList.contains(faStatus)
                ) {
                    String errorMsg = faStatus + ' is not an available value. Please pick from the following values: ';

                    for (Integer i = 0; i < statusLabelList.size(); i++) {
                        String label = statusLabelList[i];

                        errorMsg += '\'' + label + '\'';

                        if (i < statusLabelList.size() - 1) {
                            errorMsg += ',';
                        }
                    }

                    newFA.addError(errorMsg);
                }

                if (faStatus == STATUS_ACTIVE && newFA.ACG_Start_Date__c == null) {
                    newFA.addError('Start Date is required for Active Facility Adjustments.');
                }

                if (faStatus == STATUS_CANCELLED && newFA.ACG_End_Date__c == null) {
                    newFA.addError('End Date is required for Cancelled Facility Adjustments.');
                }
            }
        }
    }

    public static void validateBeforeDelete(List<ACG_Facility_Adjustment__c> oldList) {
        Boolean hasValidationError = false;
        String userProfileId = UserInfo.getProfileId();
        String adminProfileId = FSL_OrgCache.sysAdminProfileId();
        List<String> validStatuses = new List<String>{'Active', 'Deferred'};
        List<String> invcStatuses = new List<String>{
            'Ready for Payment', 'Submitted for Payment', 'Paid'
        };
        List<String> faIdList = new List<String>();
        List<Invoice__c> invcList = new List<Invoice__c>();
        Map<String, List<Invoice__c>> faInvcMap = new Map<String, List<Invoice__c>>();

        for (ACG_Facility_Adjustment__c fa : oldList) {
            String faStatus = fa.ACG_Status__c;
    
            if (
                !validStatuses.contains(faStatus)
                && userProfileId != adminProfileId
            ) {
                String errMsg = 'Cannot delete ' + fa.Name 
                    + ' with a current status of ' + faStatus;

                fa.addError(errMsg);
                hasValidationError = true;
            }

            faIdList.add(fa.Id);
        }

        if (!hasValidationError) {
            invcList = [
                SELECT Id, Facility_Adjustment__c, Status__c
                FROM Invoice__c
                WHERE Facility_Adjustment__c IN :faIdList
            ];
    
            if (invcList.size() > 0) {
                for (Invoice__c invc : invcList) {
                    String faId = invc.Facility_Adjustment__c;
                    Boolean isInvalidStatus = invcStatuses.contains(invc.Status__c);
    
                    if (isInvalidStatus) {
                        if (faInvcMap.get(faId) == null) {
                            faInvcMap.put(faId, new List<Invoice__c>{invc});
                        } else {
                            List<Invoice__c> tempInvcList = faInvcMap.get(faId);
        
                            tempInvcList.add(invc);
                            faInvcMap.put(faId, tempInvcList);
                        }
                    }
                }
    
                for (ACG_Facility_Adjustment__c fa : oldList) {
                    List<Invoice__c> faInvcList = faInvcMap.get(fa.Id);
    
                    if (faInvcList?.size() > 0) {
                        String errMsg = 'Cannot delete ' + fa.Name 
                            + ' because it has ' + faInvcList.size() 
                            + ' Invoice(s) that are under reconciled Statements. Please cancel the Facility Adjustment instead.';
    
                        fa.addError(errMsg);
                        hasValidationError = true;
                    }
                }
            }
    
            if (!hasValidationError && invcList.size() > 0) {
                delete invcList;
            }
        }
    }

    public static void applyDeferActiveDate(
        Map<Id, ACG_Facility_Adjustment__c> oldMap, 
        List<ACG_Facility_Adjustment__c> oldList,
        List<ACG_Facility_Adjustment__c> newList
    ) {
        for (ACG_Facility_Adjustment__c newFA : newList) {
            ACG_Facility_Adjustment__c oldFA = oldMap?.get(newFA.Id);
            String newStatus = newFA.ACG_Status__c;
            Boolean populateDate = true;

            if (newStatus == STATUS_DEFERRED) {
                if (oldFA != null && oldFA.ACG_Status__c == STATUS_DEFERRED) {
                    populateDate = false;
                }

                if (populateDate) {
                    newFA.Reactivated_On__c = null;
                    newFA.Reactivation_Date__c = null;
                    newFA.Deferred_On__c = Datetime.now();
                }
            } else if (newStatus == STATUS_ACTIVE) {
                if (
                    (oldFA != null && oldFA.ACG_Status__c != STATUS_DEFERRED)
                    || oldFA == null
                ) {
                    populateDate = false;
                }

                if (
                    oldFA != null 
                    && oldFA.ACG_Status__c == STATUS_DEFERRED
                    && newFA.Reactivation_Date__c == null
                ) {
                    newFA.addError('"Reactivation Date" must be filled when re-activating a deferred Facility Adjustment.');

                    populateDate = false;
                }

                if (populateDate) {
                    newFA.Reactivated_On__c = Datetime.now();
                    newFA.Deferred_On__c = null;
                }
            }
        }
    }

    public static void createFacAdjInvoices(List<ACG_Facility_Adjustment__c> lstFacAdjInserts) {
        List<ACG_Facility_Adjustment__c> lstFacAdj = new List<ACG_Facility_Adjustment__c>();
        List<ACG_Facility_Adjustment__c> finalFAList = new List<ACG_Facility_Adjustment__c>();
        List<String> facIdList = new List<String>();
      
        for (ACG_Facility_Adjustment__c adj : lstFacAdjInserts) {
            if (adj.ACG_Adjustments_Remaining__c > 0 && adj.ACG_Status__c == STATUS_ACTIVE) {
                lstFacAdj.add(adj);
                facIdList.add(adj.Service_Territory__c );
            }
        }

        Map<Id, ServiceTerritory> facMap = new Map<Id, ServiceTerritory>(
            [
                SELECT Id, Payment_Schedule__c
                FROM ServiceTerritory
                WHERE Id IN :facIdList
            ]
        );
        Date latestBiMoStartDate = Date.today();
        Date latestMoStartDate = latestBiMoStartDate;

        latestMoStartDate = Date.newInstance(
            latestMoStartDate.year(), 
            latestMoStartDate.month() + 1, 
            1
        );
        latestMoStartDate = latestMoStartDate.addDays(-1);

        if (latestBiMoStartDate.day() > 15) {
            latestBiMoStartDate = latestMoStartDate;
        } else {
            latestBiMoStartDate = Date.newInstance(
                latestBiMoStartDate.year(), 
                latestBiMoStartDate.month(), 
                15
            );
        }

        for (ACG_Facility_Adjustment__c fa : lstFacAdj) {
            ServiceTerritory fac = facMap.get(fa.Service_Territory__c);
            Date faStartDate = fa.Reactivation_Date__c != null ?
                fa.Reactivation_Date__c : fa.ACG_Start_Date__c;
            String pmtSchedule = fac.Payment_Schedule__c;

            if (fac != null) {
                if (
                    pmtSchedule == 'Monthly'
                    && faStartDate <= latestMoStartDate
                ) {
                    finalFAList.add(fa);
                } else if (
                    pmtSchedule == 'Bi-monthly'
                    && faStartDate <= latestBiMoStartDate
                ) {
                    finalFAList.add(fa);
                }
            }
        }

        if (!finalFAList.isEmpty()) {
            ACG_CreateFacilityAdjustments.processFacilityAdjustments(finalFAList);
        }
    }

    public static void handleCancelledFacAdjs(Map<Id, ACG_Facility_Adjustment__c> faMap) {
        List<String> faIdList = new List<String>();
        List<String> statusList = new List<String>{
            'Ready for Processing', 'Deferred'
        };
        List<Invoice__c> invcList = new List<Invoice__c>();
        List<Invoice__c> invcDeleteList = new List<Invoice__c>();

        try {
            for (String key : faMap.keySet()) {
                ACG_Facility_Adjustment__c fa = faMap.get(key);

                if (fa.ACG_Status__c == STATUS_CANCELLED) {
                    faIdList.add(fa.Id);
                }
            }

            if (faIdList.size() > 0) {
                invcList = [
                    SELECT 
                        Id, 
                        Status__c, 
                        Facility_Adjustment__c,
                        Statement__r.End_Date__c
                    FROM Invoice__c
                    WHERE Facility_Adjustment__c IN :faIdList
                    AND Status__c IN :statusList
                    AND Statement__r.Status__c = 'Unreconciled'
                ];

                for (Invoice__c invc : invcList) {
                    String faId = invc.Facility_Adjustment__c;
                    ACG_Facility_Adjustment__c fa = faMap.get(faId);
    
                    if (
                        fa.ACG_Status__c == STATUS_CANCELLED
                        && invc.Statement__r.End_Date__c > fa.ACG_End_Date__c
                    ) {
                        invcDeleteList.add(invc);
                    }
                }
    
                if (invcDeleteList.size() > 0) {
                    delete invcDeleteList;
                }
            }
        } catch (Exception e) {
            handleException(e);
        }
    }

    public static void handleDeferredActiveFAs(Map<Id, ACG_Facility_Adjustment__c> oldMap, Map<Id, ACG_Facility_Adjustment__c> newMap) {
        List<String> faIdDeferList = new List<String>();
        List<String> faIdActiveList = new List<String>();
        List<Invoice__c> invcDeferList = new List<Invoice__c>();
        List<Invoice__c> invcActiveList = new List<Invoice__c>();
        List<Invoice__c> invcUpdateList = new List<Invoice__c>();
        List<ACG_Facility_Adjustment__c> activeFAList = new List<ACG_Facility_Adjustment__c>();
        
        try {
            for (String key : newMap.keySet()) {
                ACG_Facility_Adjustment__c newFA = newMap.get(key);
                ACG_Facility_Adjustment__c oldFA = oldMap.get(key);

                if (oldFA != null) {
                    if (
                        oldFA.ACG_Status__c != STATUS_DEFERRED
                        && newFA.ACG_Status__c == STATUS_DEFERRED
                    ) {
                        faIdDeferList.add(newFA.Id);
                    } else if (
                        oldFA.ACG_Status__c == STATUS_DEFERRED
                        && newFA.ACG_Status__c == STATUS_ACTIVE
                    ) {
                        faIdActiveList.add(newFA.Id);
                        activeFAList.add(newFA);
                    }
                }
            }

            if (faIdDeferList.size() > 0) {
                invcDeferList = [
                    SELECT 
                        Id, 
                        Status__c
                    FROM Invoice__c
                    WHERE Facility_Adjustment__c IN :faIdDeferList
                    AND Status__c = 'Ready for Processing'
                    AND Statement__r.Status__c = 'Unreconciled'
                ];

                for (Invoice__c invc : invcDeferList) {
                    invc.Status__c = 'Deferred';
                    invcUpdateList.add(invc);
                }
            }

            if (faIdActiveList.size() > 0) {
                invcActiveList = [
                    SELECT 
                        Id, 
                        Status__c,
                        Facility_Adjustment__c
                    FROM Invoice__c
                    WHERE Facility_Adjustment__c IN :faIdActiveList
                    AND Status__c = 'Deferred'
                    AND Statement__r.Status__c = 'Unreconciled'
                ];

                for (Invoice__c invc : invcActiveList) {
                    invc.Status__c = 'Ready for Processing';
                    invcUpdateList.add(invc);
                }
            }

            if (invcUpdateList.size() > 0) {
                update invcUpdateList;
            }

            if (activeFAList.size() > 0) {
                createFacAdjInvoices(activeFAList);
            }
        } catch (Exception e) {
            handleException(e);
        }
    }

    private static void handleException(Exception e) {
        String errMsg = e.getMessage() + '\n\n' + e.getStackTraceString();

        insert new FSL_Application_Log__c(
            Operation__c = 'ACG_Facility_Adj_TriggerHandler',
            Error_Message__c = errMsg
        );
    }
}