unpackaged/main/default/objects/FSL_Configuration_Setting__mdt/FSL_Configuration_Setting__mdt.object-meta.xml
<CustomObject>
    <label>FSL Configuration Setting</label>
    <pluralLabel>FSL Configuration Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/FSL_Configuration_Setting__mdt/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>Activation Date</description>
    <label>Activation Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/FSL_Configuration_Setting__mdt/fields/No_of_Retries__c.field-meta.xml
<CustomField>
    <fullName>No_of_Retries__c</fullName>
    <defaultValue>1</defaultValue>
    <label>No of Retries</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Configuration_Setting__mdt/fields/Release_Number__c.field-meta.xml
<CustomField>
    <fullName>Release_Number__c</fullName>
    <label>Release Number</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FSL_ConfigurationSetting.cls
/**
 *  @Descrption     -   This class will serve as the helper for creating appointment
 *                      dependencies for tow work types
 *
 * *        06/21/2021   Dylan Truong         ERS-223791 - Create Platform Events for LKL upsertResourceAbsence failure: create configuration settings.
 */

public with sharing class FSL_ConfigurationSetting {

     // *********************************************
    // * Factory
    // *********************************************
    public interface IFactory {
        IConfigurationSettingService createService();
    }

    public class Factory implements IFactory {
        public IConfigurationSettingService createService() {
            IConfigurationSetttingDAO dao = createDAO();
            return new ConfigurationSettingService( dao );
        }

        private IConfigurationSetttingDAO createDAO() {
            return new ConfigurationSetttingDAO();
        }
    }

    // *********************************************
    // * DAO
    // *********************************************
    public interface IConfigurationSetttingDAO extends FSL_DAO.DmlInterface {
        List<FSL_Configuration_Setting__mdt> fetchConfigurationSettings();
        List<FSL_Configuration_Setting__mdt> fetchConfigurationSettingByName(String labelName);
    }

    public class ConfigurationSetttingDAO extends FSL_DAO.DmlBase implements IConfigurationSetttingDAO{
        public List<FSL_Configuration_Setting__mdt> fetchConfigurationSettings(){
            return [SELECT Activation_Date__c,DeveloperName,Enabled__c,
                            Id,Label,Language,MasterLabel,NamespacePrefix,No_of_Retries__c,
                            QualifiedApiName,Release_Number__c 
                    FROM FSL_Configuration_Setting__mdt ];
        }   
        public List<FSL_Configuration_Setting__mdt> fetchConfigurationSettingByName(String labelName){
            return [SELECT Activation_Date__c,DeveloperName,Enabled__c,Id,
                            Label,Language,MasterLabel,NamespacePrefix,No_of_Retries__c,
                            QualifiedApiName,Release_Number__c 
                    FROM FSL_Configuration_Setting__mdt 
                    WHERE Label =: labelName];  
        }   
    }
    // *********************************************
    // * Service
    // *********************************************
    public interface IConfigurationSettingService {
     List<FSL_Configuration_Setting__mdt> getConfigurationSettings();
     List<FSL_Configuration_Setting__mdt> getConfigurationSettingByName(String labelName);
    }

    public class ConfigurationSettingService implements IConfigurationSettingService {
        private IConfigurationSetttingDAO dao;
        public ConfigurationSettingService(IConfigurationSetttingDAO dao) {
            this.dao = dao;
        }
        public List<FSL_Configuration_Setting__mdt> getConfigurationSettings() {
            return dao.fetchConfigurationSettings();
        }

        public List<FSL_Configuration_Setting__mdt> getConfigurationSettingByName(String labelName) {
            return dao.fetchConfigurationSettingByName(labelName);
        }
    }
}