unpackaged/main/default/objects/Announcements__c/Announcements__c.object-meta.xml
<CustomObject>
    <label>Announcements</label>
    <nameField>
        <label>Announcement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Announcements__c/fields/Announcement_Description__c.field-meta.xml
<CustomField>
    <fullName>Announcement_Description__c</fullName>
    <label>Announcement Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Announcements__c/fields/Announcement_Location__c.field-meta.xml
<CustomField>
    <fullName>Announcement_Location__c</fullName>
    <label>Announcement Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
            <value>
                <fullName>Work Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Announcements__c/fields/Announcement_Priority__c.field-meta.xml
<CustomField>
    <fullName>Announcement_Priority__c</fullName>
    <label>Announcement Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Announcements__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Announcements__c/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <label>Case Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Announcements__c/fields/Service_Types__c.field-meta.xml
<CustomField>
    <fullName>Service_Types__c</fullName>
    <label>Service Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accident</fullName>
            </value>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Bicycle</fullName>
                <isActive>false</isActive>
                <label>Bicycle</label>
            </value>
            <value>
                <fullName>Extrication</fullName>
            </value>
            <value>
                <fullName>Flat Tire</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Home Lockout</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
            <value>
                <fullName>Tow</fullName>
            </value>
            <value>
                <fullName>Vehicle Lockout</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/ACG_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>ACG_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Tow</fullName>
            </value>
            <value>
                <fullName>Flat Tire</fullName>
            </value>
            <value>
                <fullName>Vehicle Lockout</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Extrication</fullName>
            </value>
            <value>
                <fullName>Home Lockout</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
            <value>
                <fullName>Extrication Tow Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ACG_GetRecordsFromAnnouncementsTest.cls
/*
* @description: Test class for ACG_GetRecordsFromAnnouncements
* @date: September 28th,2021
* author: Deloitte USI
*/
 @isTest
public class ACG_GetRecordsFromAnnouncementsTest {
    //@testSetup
    public static void testSetup(){
    /* Test data for getRecordsFromAnnouncementTest()*/
        Announcements__c obj = New Announcements__c();
        obj.Name='@Test Announcement Rec#';
        obj.Announcement_Description__c= '*# Announcement Description #*';
        obj.Status__c='Active';
        obj.Approval_Status__c='Approved';
        obj.Effective_Date__c = System.today().addDays(-10);
		obj.Expiration_Date__c = System.today().addDays(10);
		obj.Service_Types__c = 'Battery';
        obj.Announcement_Priority__c = 'High';
      	obj.Announcement_Location__c = 'Case';
        obj.Case_Record_Type__c = 'ERS';
        insert obj;
        
        Id ERS_recType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ACG_ERS').getRecordTypeId();
        Case objCase = new Case(Subject='@Test GetAnnoucement Record@', RecordTypeId = ERS_recType, ACG_Service_Type__c = 'Battery' );
        insert objCase;
        
    }
     @isTest
    Public static void getRecordsFromAnnouncementTest(){
        
        /* Test data for getRecordsFromAnnouncementTest()*/
        Announcements__c announcementRecord = New Announcements__c();
        announcementRecord.Name='@Test Announcement Rec#';
        announcementRecord.Announcement_Description__c= '*# Announcement Description #*';
        announcementRecord.Status__c='Active';
        announcementRecord.Approval_Status__c='Approved';
        announcementRecord.Effective_Date__c = System.today().addDays(-10);
		announcementRecord.Expiration_Date__c = System.today().addDays(10);
		announcementRecord.Service_Types__c = 'Battery';
        announcementRecord.Announcement_Priority__c = 'High';
      	announcementRecord.Announcement_Location__c = 'Case';
        announcementRecord.Case_Record_Type__c = 'ERS';
        insert announcementRecord;
        
        Id ERS_recType = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ACG_ERS').getRecordTypeId();
        Case objCase = new Case(Subject='@Test GetAnnoucement Record@', RecordTypeId = ERS_recType, ACG_Service_Type__c = 'Battery' );
        insert objCase;
        
        //Case objCase = [SELECT Id FROM Case WHERE Subject ='@Test GetAnnoucement Record@' LIMIT 1];
        //Announcements__c announcementRecord=[SELECT Id FROM Announcements__c WHERE Name ='@Test Announcement Rec#' LIMIT 1];
        
       	Map<Id, Announcements__c> mapRecords = new Map<Id, Announcements__c>(ACG_GetRecordsFromAnnouncements.getRecordsFromAnnouncement(objCase.Id));
     	System.assertEquals(true,(mapRecords.keySet()).contains(announcementRecord.Id),'Record Not Found: '+mapRecords);
    }

}