unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Adjustment</label>
    <referenceTo>ACG_Facility_Adjustment__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Facility_Adjustment_Category__c.field-meta.xml
<CustomField>
    <fullName>Facility_Adjustment_Category__c</fullName>
    <label>Facility Adjustment Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Invoice_Line_Item__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERS Calls</fullName>
            </value>
            <value>
                <fullName>Call Adjustments</fullName>
            </value>
            <value>
                <fullName>Facility Adjustments</fullName>
            </value>
            <value>
                <fullName>Reciprocals</fullName>
            </value>
            <value>
                <fullName>Reciprocal Adjustments</fullName>
            </value>
            <value>
                <fullName>Facility Adjustment</fullName>
                <isActive>false</isActive>
                <label>Facility Adjustment</label>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
            <value>
                <fullName>Service Adjustment</fullName>
                <isActive>false</isActive>
                <label>Service Adjustment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment__c/fields/Document_Description__c.field-meta.xml
<CustomField>
    <fullName>Document_Description__c</fullName>
    <label>Document Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Line_Row__c.field-meta.xml
<CustomField>
    <fullName>Line_Row__c</fullName>
    <label>Line Row</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Spend_Category__c.field-meta.xml
<CustomField>
    <fullName>Spend_Category__c</fullName>
    <label>Spend Category</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Vendor_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Id__c</fullName>
    <label>Vendor Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <label>Facility Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Non_Payment_Facility__c.field-meta.xml
<CustomField>
    <fullName>Non_Payment_Facility__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identifies a Facility that will not have payment file created for itself during its payment cycles</description>
    <label>Non Payment Facility</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSL</fullName>
            </value>
            <value>
                <fullName>Lightning Scheduler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Spend_Category__mdt/Spend_Category__mdt.object-meta.xml
<CustomObject>
    <label>Spend Category</label>
    <pluralLabel>Spend Categories</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Spend_Category__mdt/fields/Spend_Category__c.field-meta.xml
<CustomField>
    <fullName>Spend_Category__c</fullName>
    <label>Spend Category #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST#{00000000}</displayFormat>
        <label>Statement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Statement__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When a statement has been reconciled and processed for payment</description>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5500_Basic__c.field-meta.xml
<CustomField>
    <fullName>SC5500_Basic__c</fullName>
    <formula>Basic_Cost__c  +  Basic_Cost_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5500 (Basic)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5500_Basic_Reciprocal__c.field-meta.xml
<CustomField>
    <fullName>SC5500_Basic_Reciprocal__c</fullName>
    <formula>Basic_Cost_Reciprocal__c + Basic_Cost_Reciprocal_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5500 (Basic Reciprocal)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5500_Other__c.field-meta.xml
<CustomField>
    <fullName>SC5500_Other__c</fullName>
    <formula>Other_Cost_ERS__c + Other_Cost_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5500 (Other)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5500_Other_Reciprocal__c.field-meta.xml
<CustomField>
    <fullName>SC5500_Other_Reciprocal__c</fullName>
    <formula>Other_Cost_Reciprocal__c + Other_Cost_Reciprocal_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5500 (Other Reciprocal)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5680_Plus__c.field-meta.xml
<CustomField>
    <fullName>SC5680_Plus__c</fullName>
    <formula>Plus_Cost__c  +  Plus_Cost_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5680 (Plus)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5680_Plus_Reciprocal__c.field-meta.xml
<CustomField>
    <fullName>SC5680_Plus_Reciprocal__c</fullName>
    <formula>Plus_Cost_Reciprocal__c + Plus_Cost_Reciprocal_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5680 (Plus Reciprocal)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5680_RV__c.field-meta.xml
<CustomField>
    <fullName>SC5680_RV__c</fullName>
    <formula>RV_Cost__c + RV_Cost_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5680 (RV)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5680_RV_Reciprocal__c.field-meta.xml
<CustomField>
    <fullName>SC5680_RV_Reciprocal__c</fullName>
    <formula>RV_Cost_Reciprocal__c + RV_Cost_Reciprocal_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5680 (RV Reciprocal)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5760_Premier__c.field-meta.xml
<CustomField>
    <fullName>SC5760_Premier__c</fullName>
    <formula>Premier_Cost__c  +  Premier_Cost_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5760 (Premier)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/SC5760_Premier_Reciprocal__c.field-meta.xml
<CustomField>
    <fullName>SC5760_Premier_Reciprocal__c</fullName>
    <formula>Premier_Cost_Reciprocal__c + Premier_Cost_Reciprocal_Adjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SC5760 (Premier Reciprocal)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Unreconciled</fullName>
                <default>true</default>
                <label>Unreconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <summarizedField>Invoice__c.Total_Amount__c</summarizedField>
    <summaryForeignKey>Invoice__c.Statement__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Reimbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AAAPaymentCreationBatch.cls
public class AAAPaymentCreationBatch implements Database.Batchable<SObject>, Schedulable {
    public String query;

    public Database.QueryLocator start(Database.BatchableContext bc) {
        query = 
            'SELECT ' +
                'Id, ' +
                'Type__c, ' +
                'Status__c, ' +
                'Total_Amount__c, ' +
                'Service_Territory__c, ' +
                'Service_Territory__r.Facility_Number__c, ' +
                'Service_Territory__r.Name, ' +
                'Service_Territory__r.Street, ' +
                'Service_Territory__r.City, ' +
                'Service_Territory__r.State, ' +
                'Service_Territory__r.PostalCode, ' +
                'Facility_Adjustment__c, ' +
                'Facility_Adjustment_Category__c, ' +
                'Statement__c, ' +
                'Statement__r.SC5500_Basic__c, ' +
                'Statement__r.SC5500_Basic_Reciprocal__c, ' +
                'Statement__r.SC5500_Other__c, ' +
                'Statement__r.SC5500_Other_Reciprocal__c, ' +
                'Statement__r.SC5680_Plus__c, ' +
                'Statement__r.SC5680_Plus_Reciprocal__c, ' +
                'Statement__r.SC5680_RV__c, ' +
                'Statement__r.SC5680_RV_Reciprocal__c, ' +
                'Statement__r.SC5760_Premier__c, ' +
                'Statement__r.SC5760_Premier_Reciprocal__c, ' +
                'Statement__r.Status__c, ' +
                'Statement__r.Service_Territory__c, ' +
                'Statement__r.End_Date__c, ' +
                'Statement__r.Name, ' +
                'Statement__r.Processed__c' +
            ' FROM Invoice__c' +
            ' WHERE Status__c = \'Ready for Payment\'' +
                ' OR ' +
                    '(' +
                        'Service_Territory__r.IsActive = true ' +
                        'AND Service_Territory__r.Non_Payment_Facility__c = false ' +
                        'AND Statement__r.Status__c = \'Reconciled\' ' +
                        'AND Statement__r.Processed__c = false' +
                    ')';

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Invoice__c> scope) {
        Map<Id, Map<String, Object>> statementMap = new Map<Id, Map<String, Object>>();
        List<Statement__c> statementUpdateList = new List<Statement__c>();
        List<Invoice__c> invoiceUpdateList = new List<Invoice__c>();
        List<Payment__c> paymentInsertList = new List<Payment__c>();
        Map<String, String> spendCategoryMap = new Map<String, String>();

        // build spend category map
        for(Spend_Category__mdt scMdt : [SELECT Id, Label, Spend_Category__c FROM Spend_Category__mdt]) {
            spendCategoryMap.put(scMdt.Label, scMdt.Spend_Category__c);
        }

        // build statement map so invoices are grouped by statement
        for(Invoice__c invoice : scope) {
            if(statementMap.get(invoice.Statement__c) == null) {
                Map<String, Object> container = new Map<String, Object>{
                    'statement' => invoice.Statement__r,
                    'invoices' => new List<Invoice__c>{
                        invoice
                    }
                };

                statementMap.put(invoice.Statement__c, container);
            } else {
                List<Invoice__c> tempList = (List<Invoice__c>) statementMap.get(invoice.Statement__c).get('invoices');

                tempList.add(invoice);
                statementMap.get(invoice.Statement__c).put('invoices', tempList);
            }
        }

        // iterate over each statement and do logic to create payment records
        for(Id key : statementMap.keySet()) {
            Map<String, Object> facAdjCatInvcMap = new Map<String, Object>();
            Map<String, Object> container = statementMap.get(key);
            Statement__c statement = (Statement__c) container.get('statement');
            List<Invoice__c> invoiceList = (List<Invoice__c>) container.get('invoices');
            String basic = 'Basic';
            String basicRec = 'Basic Reciprocal';
            String other = 'Other';
            String otherRec = 'Other Reciprocal';
            String plus = 'Plus';
            String plusRec = 'Plus Reciprocal';
            String rv = 'RV';
            String rvRec = 'RV Reciprocal';
            String premier = 'Premier';
            String premierRec = 'Premier Reciprocal';
            String paymentDesc = 'FACILITY PAYMENT';
            String pmtAddress = invoiceList[0].Service_Territory__r.Street;
            String pmtCity = invoiceList[0].Service_Territory__r.City;
            String pmtState = invoiceList[0].Service_Territory__r.State;
            String pmtZip = invoiceList[0].Service_Territory__r.PostalCode;
            Integer lineRow = 0;

            if (statement.SC5500_Basic__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = basic,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5500_Basic__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }
    
            if (statement.SC5500_Basic_Reciprocal__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = basicRec,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5500_Basic_Reciprocal__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }
    
            if (statement.SC5500_Other__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = other,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5500_Other__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }
    
            if (statement.SC5500_Other_Reciprocal__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = otherRec,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5500_Other_Reciprocal__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }
    
            if (statement.SC5680_Plus__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = plus,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5680_Plus__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }
    
            if (statement.SC5680_Plus_Reciprocal__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = plusRec,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5680_Plus_Reciprocal__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }
    
            if (statement.SC5680_RV__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = rv,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5680_RV__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }
    
            if (statement.SC5680_RV_Reciprocal__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = rvRec,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5680_RV_Reciprocal__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }
    
            if (statement.SC5760_Premier__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = premier,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5760_Premier__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }
    
            if (statement.SC5760_Premier_Reciprocal__c > 0) {
                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = invoiceList[0].Service_Territory__r.Facility_Number__c,
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = premierRec,
                        Spend_Category__c = spendCategoryMap.get(basic),
                        Amount__c = statement.SC5760_Premier_Reciprocal__c,
                        Vendor_Name__c = invoiceList[0].Service_Territory__r.Name,
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }

            // iterate through invoices and build map for same facility adjustment categories
            for(Invoice__c invoice : invoiceList) {
                if(invoice.Status__c == 'Ready for Payment') {
                    if(invoice.Type__c == 'Facility Adjustments') {
                        Map<String, Object> invcContainer;
                        String spendCategoryCode = spendCategoryMap.get(invoice.Facility_Adjustment_Category__c);
                        String facAdjCat = invoice.Facility_Adjustment_Category__c;

                        if(facAdjCatInvcMap.get(facAdjCat) == null) {
                            invcContainer = new Map<String, Object>{
                                'vendorId' => invoice.Service_Territory__r.Facility_Number__c,
                                'itemDesc' => facAdjCat,
                                'spendCat' => spendCategoryCode,
                                'amount' => invoice.Total_Amount__c,
                                'vendorName' => invoice.Service_Territory__r.Name
                            };
                        } else {
                            invcContainer = (Map<String, Object>) facAdjCatInvcMap.get(facAdjCat);

                            Decimal prevAmt = (Decimal) invcContainer.get('amount');
                            Decimal addAmt = invoice.Total_Amount__c;

                            invcContainer.put('amount', prevAmt + addAmt);
                        }

                        facAdjCatInvcMap.put(facAdjCat, invcContainer);
                    }

                    invoice.Status__c = 'Submitted for Payment';
                    invoiceUpdateList.add(invoice);
                }
            }

            // iterate over mapped facility adjustment categories and generate payment records
            for(String facAdjCatKey : facAdjCatInvcMap.keySet()) {
                Map<String, Object> invcCont = (Map<String, Object>) facAdjCatInvcMap.get(facAdjCatKey);

                paymentInsertList.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = invoiceList[0].Service_Territory__c,
                        Vendor_Id__c = (String) invcCont.get('vendorId'),
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = (String) invcCont.get('itemDesc'),
                        Spend_Category__c = (String) invcCont.get('spendCat'),
                        Amount__c = (Decimal) invcCont.get('amount'),
                        Vendor_Name__c = (String) invcCont.get('vendorName'),
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            }

            statement.Processed__c = true;
            statement.Payment_Date__c = Date.today();
            statementUpdateList.add(statement);
        }

        update statementUpdateList;
        update invoiceUpdateList;
        insert paymentInsertList;
    }

    public void finish(Database.BatchableContext bc) {
        // finished batch logic
        System.debug('Finished payment creation batch');
    }

    public void execute(SchedulableContext ctx) {
        AAAPaymentCreationBatch batch = new AAAPaymentCreationBatch();

        Database.executeBatch(batch, 200);
    }
}