unpackaged/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN#{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready for Processing</fullName>
            </value>
            <value>
                <fullName>Ready for Payment</fullName>
            </value>
            <value>
                <fullName>Submitted for Payment</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERS Calls</fullName>
            </value>
            <value>
                <fullName>Call Adjustments</fullName>
            </value>
            <value>
                <fullName>Facility Adjustments</fullName>
            </value>
            <value>
                <fullName>Reciprocals</fullName>
            </value>
            <value>
                <fullName>Reciprocal Adjustments</fullName>
            </value>
            <value>
                <fullName>Facility Adjustment</fullName>
                <isActive>false</isActive>
                <label>Facility Adjustment</label>
            </value>
            <value>
                <fullName>Service</fullName>
                <isActive>false</isActive>
                <label>Service</label>
            </value>
            <value>
                <fullName>Service Adjustment</fullName>
                <isActive>false</isActive>
                <label>Service Adjustment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000000000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Payment__c/fields/Address_1__c.field-meta.xml
<CustomField>
    <fullName>Address_1__c</fullName>
    <label>Address 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Document_Description__c.field-meta.xml
<CustomField>
    <fullName>Document_Description__c</fullName>
    <label>Document Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Line_Row__c.field-meta.xml
<CustomField>
    <fullName>Line_Row__c</fullName>
    <label>Line Row</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Spend_Category__c.field-meta.xml
<CustomField>
    <fullName>Spend_Category__c</fullName>
    <label>Spend Category</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Statement__c.field-meta.xml
<CustomField>
    <fullName>Statement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Statement</label>
    <referenceTo>Statement__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Vendor_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Id__c</fullName>
    <label>Vendor Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Payment__c/fields/Vendor_Name__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Name__c</fullName>
    <label>Vendor Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Club_Code__c</fullName>
    <label>Club Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
            </value>
            <value>
                <fullName>002</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>014</fullName>
            </value>
            <value>
                <fullName>018</fullName>
            </value>
            <value>
                <fullName>020</fullName>
            </value>
            <value>
                <fullName>023</fullName>
            </value>
            <value>
                <fullName>036</fullName>
            </value>
            <value>
                <fullName>045</fullName>
            </value>
            <value>
                <fullName>047</fullName>
            </value>
            <value>
                <fullName>049</fullName>
            </value>
            <value>
                <fullName>057</fullName>
            </value>
            <value>
                <fullName>065</fullName>
            </value>
            <value>
                <fullName>066</fullName>
            </value>
            <value>
                <fullName>069</fullName>
            </value>
            <value>
                <fullName>071</fullName>
            </value>
            <value>
                <fullName>080</fullName>
            </value>
            <value>
                <fullName>084</fullName>
            </value>
            <value>
                <fullName>104</fullName>
            </value>
            <value>
                <fullName>111</fullName>
            </value>
            <value>
                <fullName>113</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
            <value>
                <fullName>137</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>177</fullName>
            </value>
            <value>
                <fullName>188</fullName>
            </value>
            <value>
                <fullName>195</fullName>
            </value>
            <value>
                <fullName>212</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/DBA_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>DBA_Address_Line_1__c</fullName>
    <label>DBA Address Line 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/DBA_City__c.field-meta.xml
<CustomField>
    <fullName>DBA_City__c</fullName>
    <label>DBA City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/DBA_Name__c.field-meta.xml
<CustomField>
    <fullName>DBA_Name__c</fullName>
    <label>DBA Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/DBA_State__c.field-meta.xml
<CustomField>
    <fullName>DBA_State__c</fullName>
    <label>DBA State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ACG_States</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/DBA_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>DBA_Zip_Code__c</fullName>
    <label>DBA Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <label>Facility Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSL</fullName>
            </value>
            <value>
                <fullName>Lightning Scheduler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Spend_Category__mdt/Spend_Category__mdt.object-meta.xml
<CustomObject>
    <label>Spend Category</label>
    <pluralLabel>Spend Categories</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Spend_Category__mdt/fields/Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Club_Code__c</fullName>
    <label>Club Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Spend_Category__mdt/fields/Spend_Category__c.field-meta.xml
<CustomField>
    <fullName>Spend_Category__c</fullName>
    <label>Spend Category #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/Statement__c.object-meta.xml
<CustomObject>
    <label>Statement</label>
    <nameField>
        <displayFormat>ST#{00000000}</displayFormat>
        <label>Statement Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Statement__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Statements</relationshipLabel>
    <relationshipName>Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Unreconciled</fullName>
                <default>true</default>
                <label>Unreconciled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Statement_Field_Spend_Category_Mappings__mdt/Statement_Field_Spend_Category_Mappings__mdt.object-meta.xml
<CustomObject>
    <label>Statement Field Spend Category Mappings</label>
    <pluralLabel>Statement Field Spend Category Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Statement_Field_Spend_Category_Mappings__mdt/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Replaces the managed field &quot;Label&quot; with this field due to being unable to edit length of text.</description>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Statement_Field_Spend_Category_Mappings__mdt/fields/Spend_Category_Label__c.field-meta.xml
<CustomField>
    <fullName>Spend_Category_Label__c</fullName>
    <label>Spend Category Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/ACG_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <customValue>
        <fullName>NJ</fullName>
    </customValue>
    <masterLabel>States</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/AAAPaymentFlowHelper.cls
global without sharing class AAAPaymentFlowHelper {
    @InvocableMethod(label = 'Batch Payment Flow Helper')
    global static List<FlowOutput> runPaymentFlowHelper(List<FlowInput> input) {
        List<FlowOutput> outputList = new List<FlowOutput>();

        for (FlowInput flowInput : input) {
            FlowOutput output = new FlowOutput();
            List<String> invcsToUpdate = new List<String>();
            List<Payment__c> pmtsToInsert = new List<Payment__c>();
            List<Spend_Category__mdt> scMdtList = flowInput.scMdtList;
            List<Statement_Field_Spend_Category_Mappings__mdt> fieldSCMdtList = flowInput.fieldSCMdtList;
            List<Invoice__c> invoiceList = flowInput.invcList;
            BackOffice_Settings__c boSettings = flowInput.boSettings;
            Statement__c statement = flowInput.stmt;
            ServiceTerritory fac = flowInput.fac;
            String paymentDesc = 'FACILITY PAYMENT';
            String clubCode = boSettings.Club_Code__c;
            String pmtVendor = fac.Name;
            String pmtAddress = fac.Street;
            String pmtCity = fac.City;
            String pmtState = fac.State;
            String pmtZip = fac.PostalCode;
            Integer lineRow = 0;
            Map<String,List<String>> scToStmtFieldsMap = new Map<String,List<String>>();
            Map<String, String> spendCategoryMap = new Map<String, String>();
            Map<String, Object> facAdjCatInvcMap = new Map<String, Object>();
            Map<String, Object> statementFieldsToValue = statement.getPopulatedFieldsAsMap();

            // build spend category map
            for(Spend_Category__mdt scMdt : scMdtList) {
                spendCategoryMap.put(scMdt.Label, scMdt.Spend_Category__c);
            }

            //build Statement Category To Statement Field Mapping
            for (Statement_Field_Spend_Category_Mappings__mdt scTostFieldMdt : fieldSCMdtList) {
                String scLabel = scTostFieldMdt.Spend_Category_Label__c;
                String mdtLabel = scTostFieldMdt.Label__c;

                if (
                    scToStmtFieldsMap.get(scLabel) != null 
                    && scToStmtFieldsMap.get(scLabel).size() > 0
                ) {
                    List<String> lstStatementFields = scToStmtFieldsMap.get(scLabel);

                    lstStatementFields.add(mdtLabel);
                    scToStmtFieldsMap.put(scLabel, lstStatementFields);                                                    
                } else {
                    scToStmtFieldsMap.put(scLabel, new List<String>{mdtLabel});
                }           
            }

            if (clubCode == '212') {
                if (String.isNotBlank(fac.DBA_Name__c)) {
                    pmtVendor = fac.DBA_Name__c;
                }

                String dbaAddress = fac.DBA_Address_Line_1__c;
                String dbaCity = fac.DBA_City__c;
                String dbaState = fac.DBA_State__c;
                String dbaZip = fac.DBA_Zip_Code__c;

                if (
                    String.isNotBlank(dbaAddress)
                    && String.isNotBlank(dbaCity)
                    && String.isNotBlank(dbaState)
                    && String.isNotBlank(dbaZip)
                ) {
                    pmtAddress = dbaAddress;
                    pmtCity = dbaCity;
                    pmtState = dbaState;
                    pmtZip = dbaZip;
                }
            }

            for (String scLabel : scToStmtFieldsMap.keySet()) {
                if (
                    scToStmtFieldsMap.get(scLabel) != null 
                    && scToStmtFieldsMap.get(scLabel).size() > 0
                ) {
                    Decimal totalCost = 0.00;
                    String spendCatNumber = '';

                    for (String stFieldName : scToStmtFieldsMap.get(scLabel)) {
                        Object obj = statementFieldsToValue.get(stFieldName);

                        if (obj != null) {
                            String costStr = String.valueOf(obj);

                            totalCost += Decimal.valueOf(costStr);
                        }
                    }
                    
                    if (spendCategoryMap.get(scLabel) != null) {
                        spendCatNumber = spendCategoryMap.get(scLabel);
                    }
                    
                    if (totalCost != 0.00) {
                        pmtsToInsert.add(
                            new Payment__c(
                                Statement__c = statement.Id,
                                Service_Territory__c = fac.Id,
                                Vendor_Id__c = fac.Facility_Number__c,
                                Document_Date__c = statement.End_Date__c,
                                Document_Number__c = statement.Name,
                                Document_Description__c = paymentDesc,
                                Line_Row__c = ++lineRow,
                                Item_Description__c = scLabel,
                                Spend_Category__c = spendCatNumber,
                                Amount__c = totalCost,
                                Vendor_Name__c = pmtVendor,
                                Address_1__c = pmtAddress,
                                City__c = pmtCity,
                                State__c = pmtState,
                                Zip__c = pmtZip
                            )
                        );
                    }  
                }
            }

            if (invoiceList != null && invoiceList.size() > 0) {
                // iterate through invoices and build map for same facility adjustment categories
                for (Invoice__c invoice : invoiceList) {
                    if (invoice.Status__c == 'Ready for Payment') {
                        if (invoice.Type__c == 'Facility Adjustments') {
                            Map<String, Object> invcContainer;
                            String facAdjCat = invoice.Facility_Adjustment_Category__c;
                            String adjType = invoice.Facility_Adjustment_Type__c;
                            Decimal total = invoice.Total_Amount__c;
                            String vendorName = fac.Name;
                            String spendCategoryCode = spendCategoryMap.get(facAdjCat);
    
                            if (adjType == 'Debit') {
                                total = -total;
                            }
    
                            if (clubCode == '212' && String.isNotBlank(fac.DBA_Name__c)) {
                                vendorName = fac.DBA_Name__c;
                            }
    
                            if (facAdjCatInvcMap.get(facAdjCat) == null) {
                                invcContainer = new Map<String, Object>{
                                    'vendorId' => fac.Facility_Number__c,
                                    'itemDesc' => facAdjCat,
                                    'spendCat' => spendCategoryCode,
                                    'amount' => total,
                                    'vendorName' => vendorName
                                };
                            } else {
                                invcContainer = (Map<String, Object>) facAdjCatInvcMap.get(facAdjCat);
                                            
                                Decimal prevAmt = (Decimal) invcContainer.get('amount');
                                            
                                invcContainer.put('amount', prevAmt + total);
                            }
                            
                            facAdjCatInvcMap.put(facAdjCat, invcContainer);
                        }
                        
                        invoice.Status__c = 'Submitted for Payment';
                        invcsToUpdate.add(invoice.Id);
                    }
                }
            }

            // iterate over mapped facility adjustment categories and generate payment records
            for (String facAdjCatKey : facAdjCatInvcMap.keySet()) {
                Map<String, Object> invcCont = (Map<String, Object>) facAdjCatInvcMap.get(facAdjCatKey);

                pmtsToInsert.add(
                    new Payment__c(
                        Statement__c = statement.Id,
                        Service_Territory__c = fac.Id,
                        Vendor_Id__c = (String) invcCont.get('vendorId'),
                        Document_Date__c = statement.End_Date__c,
                        Document_Number__c = statement.Name,
                        Document_Description__c = paymentDesc,
                        Line_Row__c = ++lineRow,
                        Item_Description__c = (String) invcCont.get('itemDesc'),
                        Spend_Category__c = (String) invcCont.get('spendCat'),
                        Amount__c = (Decimal) invcCont.get('amount'),
                        Vendor_Name__c = (String) invcCont.get('vendorName'),
                        Address_1__c = pmtAddress,
                        City__c = pmtCity,
                        State__c = pmtState,
                        Zip__c = pmtZip
                    )
                );
            } 

            if (pmtsToInsert.size() > 0) {
                output.hasPmtsToInsert = true;
                output.pmtList = pmtsToInsert;
            }

            if (invcsToUpdate.size() > 0) {
                output.hasInvcsToUpdate = true;
                output.invcList = invcsToUpdate;
            }

            statement.Payment_Date__c = Date.today();
            statement.Processed__c = true;
            output.hasStmtToUpdate = true;
            output.stmt = statement;

            outputList.add(output);
        }

        return outputList;
    }

    global class FlowInput {
        @InvocableVariable(label = 'Statement') global Statement__c stmt;
        @InvocableVariable(label = 'Service Territory') global ServiceTerritory fac;
        @InvocableVariable(label = 'Back Office Settings') global BackOffice_Settings__c boSettings;
        @InvocableVariable(label = 'Spend Category Metadata') global List<Spend_Category__mdt> scMdtList;
        @InvocableVariable(label = 'Statement Field Spend Category Mapping Metadata') global List<Statement_Field_Spend_Category_Mappings__mdt> fieldSCMdtList;
        @InvocableVariable(label = 'Invoices') global List<Invoice__c> invcList;
    }
    
    global class FlowOutput {
        @InvocableVariable(label = 'Has Payments To Insert') global Boolean hasPmtsToInsert;
        @InvocableVariable(label = 'Payments To Insert') global List<Payment__c> pmtList;
        @InvocableVariable(label = 'Has Invoices To Update') global Boolean hasInvcsToUpdate;
        @InvocableVariable(label = 'Invoice Ids To Update') global List<String> invcList;
        @InvocableVariable(label = 'Has Statement To Update') global Boolean hasStmtToUpdate;
        @InvocableVariable(label = 'Statement To Update') global Statement__c stmt;
    }
}