unpackaged/main/default/objects/ClubName_To_Region_Mapping__mdt/ClubName_To_Region_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>ClubName To Region Mapping</label>
    <pluralLabel>ClubName_To_Region_Mapping</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/ClubName_To_Region_Mapping__mdt/fields/Club_Name__c.field-meta.xml
<CustomField>
    <fullName>Club_Name__c</fullName>
    <label>Club Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AAA North Dakota - 113</fullName>
                <default>true</default>
                <label>AAA North Dakota - 113</label>
            </value>
            <value>
                <fullName>AAA Chicago - 020</fullName>
            </value>
            <value>
                <fullName>AAA Michigan - 047</fullName>
            </value>
            <value>
                <fullName>AAA Minnesota/lowa - 049</fullName>
            </value>
            <value>
                <fullName>AAA Nebraska - 069</fullName>
            </value>
            <value>
                <fullName>AAA Wisconsin - 270</fullName>
            </value>
            <value>
                <fullName>Auto Club South - 014</fullName>
            </value>
            <value>
                <fullName>AAA Carolinas - 111</fullName>
            </value>
            <value>
                <fullName>AAA Colorado - 006</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ClubName_To_Region_Mapping__mdt/fields/Club_Region__c.field-meta.xml
<CustomField>
    <fullName>Club_Region__c</fullName>
    <label>Club Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACG</fullName>
                <default>true</default>
                <label>ACG</label>
            </value>
            <value>
                <fullName>CMC</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ERS_GetRegionRecordsFromClubNameTest.cls
@isTest
public class ERS_GetRegionRecordsFromClubNameTest {
   @isTest
     Public Static void getRegionNamesTest()
     {
      List<ClubName_To_Region_Mapping__mdt> regList=[SELECT Club_Region__c FROM ClubName_To_Region_Mapping__mdt WHERE Club_Name__c=:'AAA North Dakota - 113'];
       Test.startTest();
      List<string> lstRegions = ERS_GetRegionRecordsFromClubName.getRegionNames('AAA North Dakota - 113');
        Test.stopTest();
      If(lstRegions.size()>0){
           system.assertEquals(regList[0].Club_Region__c,lstRegions[0]);
      } 

     }
}