unpackaged/main/default/objects/Location/fields/Battery_Capable__c.field-meta.xml
<CustomField>
    <fullName>Battery_Capable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Battery Capable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Location/fields/Motorcycle_Capable__c.field-meta.xml
<CustomField>
    <fullName>Motorcycle_Capable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Motorcycle Capable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Location/fields/RV_Capable__c.field-meta.xml
<CustomField>
    <fullName>RV_Capable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RV Capable</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Location/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Location/fields/VehicleType__c.field-meta.xml
<CustomField>
    <fullName>VehicleType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Skill Type</label>
    <referenceTo>Vehicle_Type__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Location/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

unpackaged/main/default/objects/ProfileSkill/fields/Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Developer_Name__c</fullName>
    <label>Developer Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.Facility__c</field>
            <operation>equals</operation>
            <valueField>$Source.Primary_Service_Territory__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <formula>TEXT(Vehicle__r.Vehicle_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResourceSkill/fields/Skill_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>Skill_DeveloperName__c</fullName>
    <formula>Skill.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Skill_DeveloperName</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResourceSkill/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <defaultValue>&quot;Resource-Dependent&quot;</defaultValue>
    <label>Skill Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle-Dependent</fullName>
            </value>
            <value>
                <fullName>Resource-Dependent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Vehicles associated to a customer.  Member or non-member</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Skill__c/Vehicle_Skill__c.object-meta.xml
<CustomObject>
    <description>Junction object between Vehicle Type and Skill</description>
    <label>Vehicle Skill</label>
    <nameField>
        <displayFormat>VS-{0000}</displayFormat>
        <label>Vehicle Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>ProfileSkill</referenceTo>
    <relationshipLabel>Vehicle Skills</relationshipLabel>
    <relationshipName>Vehicle_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <description>Amount of Skill the resource will be granted when the vehicle is assigned</description>
    <label>Skill Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Skill__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <referenceTo>Vehicle_Type__c</referenceTo>
    <relationshipLabel>Vehicle Skills</relationshipLabel>
    <relationshipName>Vehicle_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Type__c/Vehicle_Type__c.object-meta.xml
<CustomObject>
    <label>Vehicle Type</label>
    <nameField>
        <label>Vehicle Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Vehicle_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Flatbed</fullName>
    </customValue>
    <customValue>
        <fullName>Light_Service</fullName>
        <label>Light Service</label>
    </customValue>
    <customValue>
        <fullName>Wheel_Lift</fullName>
        <label>Wheel Lift</label>
    </customValue>
    <customValue>
        <fullName>Locksmith</fullName>
    </customValue>
    <customValue>
        <fullName>Battery</fullName>
    </customValue>
    <customValue>
        <fullName>Landline</fullName>
        <isActive>false</isActive>
        <label>Landline</label>
    </customValue>
    <description>Available vehicle types driven by technicians</description>
    <masterLabel>Vehicle Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/FSL_VehicleSkills.cls
/**
 * @File Name          : FSL_VehicleSkills.cls
 * @Description        : 
 * @Author             : Rajesh Kemisetti
 * @Group              : 
 * @Last Modified By   : Rajesh Kemisetti
 * @Last Modified On   : 6/12/2020, 12:07:12 PM
 * @Modification Log   : 
 * Ver       Date            Author                 Modification
 * 1.0    4/27/2020   Rajesh Kemisetti     Initial Version
**/
public class FSL_VehicleSkills {   
    
    
    /**********
     * @Method Name: manipulateSkills
     * @Parameters:(Map<id,ServiceResource>, Map<Id, ServiceResource>, String)
     * @Return Value: none
     * @Description: Accepts the map of ServiceResources and creates ServiceResourceSkill based on vehicle type
       @Author: Divyendra Naidu
     * **********/ 

    //Start Method            
    public static void manipulateSkills(Map<Id, ServiceResource> oldMap, Map<Id, ServiceResource> newMap, String operation) {
        System.debug('Entering manipulateSkills');
        List<Skill> skillList = new List<Skill>([SELECT Id, DeveloperName FROM Skill WHERE DeveloperName IN
        ('Change_Tire','Extrication','Lockout_Entry','Locksmith','Tire_Fill')]);

        List<Id> skillIdList = new List<Id>();
        for(Skill sk : skillList) {
            skillIdList.add(sk.Id);
        }
        //Begin Insert Operation    
        if(operation == 'insert') {
            List<ServiceResourceSkill> srSkillList = new List<ServiceResourceSkill>();
            for(ServiceResource sr : newMap.values()) {
                for(Skill sk : skillList) {
                    ServiceResourceSkill srsTemp = new ServiceResourceSkill(SkillId = sk.id, ServiceResourceId = sr.Id, EffectiveStartDate = System.today(), SkillLevel = 1,Skill_Type__c = 'Resource-Dependent');
                    srSkillList.add(srsTemp);
                    }                    
            }          
            insert srSkillList;
        } //End Insert Operation
    }//End Method 
    
    public static void assignVehicleSkills(List<ServiceResource> modifiedServiceResources) {
        Set<ID> srIDSet = new Set<ID>();
        Set<ID> vehicleTypeIDSet = new Set<ID>();
        Map<String, Skill> skillMap = skillMapHelper();
        Map<ServiceResource, ID> resourceToVehicleTypeMap = new Map<ServiceResource, ID>();
        Set<Id> vehicleIds = new Set<Id>();
        Map<Id,Schema.Location> vehicleMap = new Map<Id,Schema.Location>();
        for(ServiceResource updatedSR : modifiedServiceResources){
            System.debug('updatedSR.Vehicle__c======>'+updatedSR.Vehicle__c);
            if(updatedSR.Vehicle__c != null) {
                vehicleIds.add(updatedSR.Vehicle__c);
            }
        }
        System.debug('vehicleIds====>'+vehicleIds);
        if(!vehicleIds.isEmpty()) {
            vehicleMap = new Map <Id,Schema.Location> ([Select Id, Vehicle_Type__c,VehicleType__c, Battery_Capable__c, RV_Capable__c, Motorcycle_Capable__c FROM Location WHERE Id IN: vehicleIds]);
        }
        System.debug('vehicleMap======>'+vehicleMap);
        // iterate over updated srs
        for(ServiceResource updatedSR : modifiedServiceResources){
            
            // add sr ids to set
            srIDSet.add(updatedSR.id); 
            
            // add vehicle type ids to set
            if(updatedSR.Vehicle__c != null) {
                vehicleTypeIDSet.add(vehicleMap.get(updatedSR.Vehicle__c).VehicleType__c);

                // create map of service resource (key) to vehicle type  (value / id)
                resourceToVehicleTypeMap.put(updatedSR, vehicleMap.get(updatedSR.Vehicle__c).VehicleType__c);
            }
        }       
        system.debug('**vehicleTypeIDSet**'+vehicleTypeIDSet);
        // query junction object using vehicle type IDs
        List<Vehicle_Skill__c> vehicleSkills = [SELECT id, Skill__c, Skill__r.Developer_Name__c, Skill_Level__c, Vehicle_Type__c
            FROM Vehicle_Skill__c 
            WHERE Vehicle_Type__c IN :vehicleTypeIDSet];
        System.debug('vehicleSkills===>'+vehicleSkills);
        // create map of vehicle type (key) to list of vehicle type skills (value)
        Map<ID, List<Vehicle_Skill__c>> vehicleTypeToSkillListMap = new Map<ID, List<Vehicle_Skill__c>>();
        List<Vehicle_Skill__c> profileSkills = new List<Vehicle_Skill__c>();
        for(Vehicle_Skill__c vehicleSkill : vehicleSkills) {
            if(vehicleTypeToSkillListMap.get(vehicleSkill.Vehicle_Type__c) != null) {
                vehicleTypeToSkillListMap.get(vehicleSkill.Vehicle_Type__c).add(vehicleSkill);
            }else {
                vehicleTypeToSkillListMap.put(vehicleSkill.Vehicle_Type__c,new List<Vehicle_Skill__c>{vehicleSkill});
            }
        }

        // query service resource skills assigned to srs
        List<ServiceResourceSkill> currentResourceSkills = [SELECT id, Skill_DeveloperName__c, Skill_Type__c, ServiceResourceId, SkillID, SkillLevel
            FROM ServiceResourceSkill
            WHERE ServiceResourceId IN :srIDSet AND Skill_Type__c = 'Vehicle-Dependent'];
        
        
        // create map of service resource ID to assigned skills
        Map<Id,List<ServiceResourceSkill>> currentResourcesVehicleSkills = new Map<Id,List<ServiceResourceSkill>>();
        for(ServiceResourceSkill currentResourceSkill : currentResourceSkills) {
            if(currentResourcesVehicleSkills.get(currentResourceSkill.ServiceResourceId) != null) {
                currentResourcesVehicleSkills.get(currentResourceSkill.ServiceResourceId).add(currentResourceSkill);
            }else {
                currentResourcesVehicleSkills.put(currentResourceSkill.ServiceResourceId,new List<ServiceResourceSkill>{currentResourceSkill});
            }
        }

        // iterate over assigned resource that was modified
        List<ServiceResourceSkill> skillsToDelete = new List<ServiceResourceSkill>(); 
        List<ServiceResourceSkill> skillsToInsert = new List<ServiceResourceSkill>();
        
        for(ServiceResource srToModify : modifiedServiceResources){
            skillsToDelete.addAll(assignedSkillToAppliedSkillParser(srToModify, currentResourcesVehicleSkills, vehicleTypeToSkillListMap, vehicleMap));
            skillsToInsert.addAll(appliedSkillToAssignedSkillModified(srToModify, currentResourcesVehicleSkills, vehicleTypeToSkillListMap, skillMap, vehicleMap));
        }
         
        // perform deletes
        if(!skillsToDelete.isEmpty()){
            delete skillsToDelete;
        }

        // perform inserts
        if(!skillsToInsert.isEmpty()){
            // TODO: Database.upsert with partial success
            Database.upsert(skillsToInsert,false);
        }

                 
            
    }
    
    public static Map<String, Skill> skillMapHelper(){
        Map<String, Skill> skillMap = new Map<String, Skill>();
        List<Skill> skillList = [SELECT Id, DeveloperName FROM Skill];
        for(Skill sk : skillList){
            skillMap.put(sk.DeveloperName, sk);
        }

        return skillMap;
    }

    public static List<ServiceResourceSkill> assignedSkillToAppliedSkillParser(ServiceResource currentSR, Map<Id,List<ServiceResourceSkill>> currentResourcesVehicleSkills, Map<ID, List<Vehicle_Skill__c>> vehicleTypeToSkillListMap, Map<Id,Schema.Location> vehicleMap){
        List<ServiceResourceSkill> skillsToDelete = new List<ServiceResourceSkill>();
        List<ServiceResourceSkill> assignedSkills = currentResourcesVehicleSkills.get(currentSR.id);
        if(assignedSkills != null) {
            for(ServiceResourceSkill srSkill : assignedSkills){
                Boolean matchFound = false;
                // iterate over skills that should be updated for this resouces vehicle type
                if(currentSR.Vehicle__c != null && vehicleMap.get(currentSR.Vehicle__c).VehicleType__c != null && vehicleTypeToSkillListMap.get(vehicleMap.get(currentSR.Vehicle__c).VehicleType__c) != null) {
                    List<Vehicle_Skill__c> vehicleTypeSkills = vehicleTypeToSkillListMap.get(vehicleMap.get(currentSR.Vehicle__c).VehicleType__c);
                    for(Vehicle_Skill__c skillKey : vehicleTypeSkills){
                        if(srSkill.Skill_DeveloperName__c == skillKey.Skill__r.Developer_Name__c){
                            matchFound = true;
                            
                            // upsert list?
                        }
                    }
                }
                
                
                // if no match found, add to delete list
                if(!matchFound){
                    skillsToDelete.add(srSkill);
                }        
            }
        }
        

        return skillsToDelete;
    }


    public static List<ServiceResourceSkill> appliedSkillToAssignedSkillModified(ServiceResource currentSR, Map<Id,List<ServiceResourceSkill>> currentResourcesVehicleSkills, Map<ID, List<Vehicle_Skill__c>> vehicleTypeToSkillListMap, Map<String, Skill> skillMap, Map<Id,Schema.Location> vehicleMap){
        List<ServiceResourceSkill> skillsToUpsert = new List<ServiceResourceSkill>();
        system.debug('currentSR**'+currentSR);
        system.debug('vehicleMap**'+vehicleMap);
        system.debug('vehicleTypeToSkillListMap**'+vehicleTypeToSkillListMap);
        if(currentSR.Vehicle__c != null && vehicleMap.get(currentSR.Vehicle__c).VehicleType__c != null &&  vehicleTypeToSkillListMap.get(vehicleMap.get(currentSR.Vehicle__c).VehicleType__c) != null) {
            List<Vehicle_Skill__c> vehicleTypeSkills = vehicleTypeToSkillListMap.get(vehicleMap.get(currentSR.Vehicle__c).VehicleType__c);
        
            for(Vehicle_Skill__c skillKey : vehicleTypeSkills){
                Boolean matchFound = false;
                // iterate over skills that should be updated for this resouces vehicle type
                List<ServiceResourceSkill> assignedSkills = currentResourcesVehicleSkills.get(currentSR.id);
                if(assignedSkills != null) {
                    for(ServiceResourceSkill srSkill : assignedSkills){
                        if(srSkill.Skill_DeveloperName__c == skillKey.Skill__r.Developer_Name__c){
                            matchFound = true;
                            // update the skill
                            srSkill.SkillLevel = skillKey.Skill_Level__c;
                            skillsToUpsert.add(srSkill);
                        }
                    }
                }
                // if no match found, create a new skill for this resource
                if(!matchFound){
                    ID skillID = skillMap.get(skillKey.Skill__r.Developer_Name__c).id;
                    ServiceResourceSkill newSRSkill = new ServiceResourceSkill();
                    
                    newSRSkill.EffectiveStartDate = DateTime.now();
                    //srSkill.EffectiveEndDate
                    newSRSkill.ServiceResourceId = currentSR.id;
                    newSRSkill.SkillId = skillID;
                    newSRSkill.SkillLevel = skillKey.Skill_Level__c;
                    newSRSkill.Skill_Type__c = 'Vehicle-Dependent';
                    skillsToUpsert.add(newSRSkill);
                }        
            }

        }
        
        return skillsToUpsert;
    }    
}//End Class