unpackaged/main/default/objects/Location/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Location/fields/In_Use__c.field-meta.xml
<CustomField>
    <fullName>In_Use__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Use</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Primary_Facility_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Facility_Id__c</fullName>
    <label>Primary Facility Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.Facility__c</field>
            <operation>equals</operation>
            <valueField>$Source.Primary_Service_Territory__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Vehicles associated to a customer.  Member or non-member</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/FSL_SelectTruckController.cls
/**
 * Created by divnaidu on 1/9/2019.
 */

public class FSL_SelectTruckController {

    @AuraEnabled
    public static List<String> getPickListValuesIntoList(Id uId){

        List<String> pickListValuesList = new List<String>();
        /*Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get(objectType);
        Schema.DescribeSObjectResult res = convertToObj.getDescribe();
        Schema.DescribeFieldResult fieldResult = res.fields.getMap().get(selectedField).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }*/
        ServiceResource sr = [SELECT Id, Name, Vehicle__c, Primary_Facility_Id__c FROM ServiceResource WHERE RelatedRecordId = :uId AND ResourceType = 'T'];
        ServiceTerritory st = [SELECT Id FROM ServiceTerritory WHERE Id =: sr.Primary_Facility_Id__c];
        List<Schema.Location> locList = new List<Schema.Location> ([SELECT Id, Name FROM Location WHERE Facility__c = :st.Id AND In_Use__c = false]);
        for(Schema.Location loc : locList) {
            pickListValuesList.add(loc.Name);
        }
        return pickListValuesList;
    }


}