unpackaged/main/default/objects/Location/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Location/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <label>Facility Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Location/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Location/fields/VehicleType__c.field-meta.xml
<CustomField>
    <fullName>VehicleType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Skill Type</label>
    <referenceTo>Vehicle_Type__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Location/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

unpackaged/main/default/objects/ProfileSkill/fields/Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Developer_Name__c</fullName>
    <label>Developer Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <formula>Primary_Service_Territory__r.Facility_Number__c</formula>
    <label>Facility Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Primary_Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field auto-populates the Service Territory selected as the Primary Territory</description>
    <label>Primary Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.Facility__c</field>
            <operation>equals</operation>
            <valueField>$Source.Primary_Service_Territory__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <formula>TEXT(Vehicle__r.Vehicle_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResourceSkill/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <defaultValue>&quot;Resource-Dependent&quot;</defaultValue>
    <label>Skill Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vehicle-Dependent</fullName>
            </value>
            <value>
                <fullName>Resource-Dependent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <label>Facility Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Vehicles associated to a customer.  Member or non-member</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Skill__c/Vehicle_Skill__c.object-meta.xml
<CustomObject>
    <description>Junction object between Vehicle Type and Skill</description>
    <label>Vehicle Skill</label>
    <nameField>
        <displayFormat>VS-{0000}</displayFormat>
        <label>Vehicle Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vehicle_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>ProfileSkill</referenceTo>
    <relationshipLabel>Vehicle Skills</relationshipLabel>
    <relationshipName>Vehicle_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Skill__c/fields/Skill_Level__c.field-meta.xml
<CustomField>
    <fullName>Skill_Level__c</fullName>
    <description>Amount of Skill the resource will be granted when the vehicle is assigned</description>
    <label>Skill Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Skill__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <referenceTo>Vehicle_Type__c</referenceTo>
    <relationshipLabel>Vehicle Skills</relationshipLabel>
    <relationshipName>Vehicle_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vehicle_Type__c/Vehicle_Type__c.object-meta.xml
<CustomObject>
    <label>Vehicle Type</label>
    <nameField>
        <label>Vehicle Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Vehicle_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Flatbed</fullName>
    </customValue>
    <customValue>
        <fullName>Light_Service</fullName>
        <label>Light Service</label>
    </customValue>
    <customValue>
        <fullName>Wheel_Lift</fullName>
        <label>Wheel Lift</label>
    </customValue>
    <customValue>
        <fullName>Locksmith</fullName>
    </customValue>
    <customValue>
        <fullName>Battery</fullName>
    </customValue>
    <customValue>
        <fullName>Landline</fullName>
        <isActive>false</isActive>
        <label>Landline</label>
    </customValue>
    <description>Available vehicle types driven by technicians</description>
    <masterLabel>Vehicle Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/FSL_VehicleSkills_Test.cls
@isTest
public class FSL_VehicleSkills_Test {
    
    static testMethod void manipulateSkillswithVehicleTest(){
        System.Test.startTest();
        
        List<Skill> skill = [SELECT Id, DeveloperName FROM Skill WHERE DeveloperName NOT IN
                             ('Battery_Replacement', 
                              'Change_Tire',
                              'Extrication', 
                              'Flatbed', 
                              'Light_Service',
                              'Lockout_Entry',
                              'Motorcycle_Capable',
                              'RV_Capable', 
                              'Tire_Fill', 
                              'Tow', 
                              'Wheel_Lift')];
        
        ServiceResource serviceResource = [select id, Vehicle__c, Primary_Service_Territory__c, Primary_Service_Territory__r.OperatingHoursId from serviceresource where ResourceType='T' limit 1];
        Map<Id, ServiceResource> newMap = new Map<Id, ServiceResource>();
        newMap.put(serviceResource.Id, serviceResource);
        FSL_VehicleSkills.manipulateSkills(new Map<Id, ServiceResource>(), newMap, 'insert'); 
        System.Test.stopTest();
    }
    
    static testMethod void manipulateSkills_UpdateTest(){
        System.Test.startTest();
        ServiceTerritory st = [select id from ServiceTerritory where facility_number__c = '9198'];
        List<ServiceResource> serviceResource = [select id, Vehicle__c, Vehicle__r.name, Primary_Service_Territory__c, Primary_Service_Territory__r.OperatingHoursId from serviceresource where ResourceType='T' limit 1];
        Vehicle_Type__c vtype = new Vehicle_Type__c(Name='Light_Service');
        insert vtype;
        Schema.Location loc = new Schema.Location(Name='Light_Service',
                                                  IsInventoryLocation=true,
                                                  IsMobile=true,
                                                  Vehicle_Type__c='Light_Service',
                                                  Facility_Number__c='9198',
                                                  Facility__c= st.id,
                                                 VehicleType__c = vtype.Id);
        insert loc; 
        Schema.Location location = [select id, VehicleType__c from Location where name='Light_Service'];
        
        ProfileSkill pskill = new ProfileSkill(name='Light_Service',Developer_Name__c='Light_Service');
        insert pskill;
        Skill sk = new Skill(developerName='Light_Service');
        //insert sk;
                
        Vehicle_Skill__c vs = new Vehicle_Skill__c();
        vs.Skill_Level__c =2;
        vs.Skill__c = pskill.id;
        vs.Vehicle_Type__c = vtype.id;
        insert vs;
        
        Map<Id, ServiceResource> oldMap = new Map<Id, ServiceResource>();
        oldMap.put(serviceResource[0].Id, serviceResource[0]);
        
        serviceResource[0].Vehicle__c = location.Id;
        Map<Id, ServiceResource> newMap = new Map<Id, ServiceResource>();
        newMap.put(serviceResource[0].Id, serviceResource[0]);
        
        
        
        List<ServiceResourceSkill> serResSkill_BeforeUpdate = [select Id from ServiceResourceSkill where serviceResourceId = :serviceResource[0].Id];
        system.debug('serResSkill_BeforeUpdate 64 ' + serResSkill_BeforeUpdate);
        
        FSL_VehicleSkills.manipulateSkills(oldMap, newMap, 'insert');
        FSL_VehicleSkills.assignVehicleSkills(serviceResource);

        
        ProfileSkill pskill1 = new ProfileSkill(name='test1');
        insert pskill1;
        
        Vehicle_Type__c vtype1 = new Vehicle_Type__c(Name=location.VehicleType__c);
        insert vtype1;
        
        Vehicle_Skill__c vs1 = new Vehicle_Skill__c();
        vs1.Skill_Level__c =2;
        vs1.Skill__c = pskill1.id;
        vs1.Vehicle_Type__c = vtype1.id;
        insert vs1;

        
        List<ServiceResourceSkill> serResSkill_AfterUpdate = [select Id from ServiceResourceSkill where serviceResourceId = :serviceResource[0].Id];
        serResSkill_AfterUpdate[0].Skill_Type__c = 'Vehicle-Dependent';
        update serResSkill_AfterUpdate[0];
        update serviceResource;
        FSL_VehicleSkills.assignVehicleSkills(serviceResource);
        //System.assert(serResSkill_BeforeUpdate.size() <= serResSkill_AfterUpdate.size(),'Unable to update the Service Resource Skill record');
        System.Test.stopTest();
    }
    
    @testSetup
    public static void dataSetup() {
        FSL_DataFactoryUtility.userdataSetup();
    }
}