unpackaged/main/default/objects/Location/fields/Vehicle_Name__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Name__c</fullName>
    <description>Formula Field for Truck. Service Resource Gantt Label is updated with this value when the Vehicle on that Service Resource is updated</description>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Location/recordTypes/Vehicle.recordType-meta.xml
<RecordType>
    <fullName>Vehicle</fullName>
    <active>true</active>
    <label>Vehicle</label>
</RecordType>

unpackaged/main/default/objects/ServiceResource/fields/Driver_can_go_Online_Offline__c.field-meta.xml
<CustomField>
    <fullName>Driver_can_go_Online_Offline__c</fullName>
    <formula>Primary_Service_Territory__r.Driver_can_go_Online_Offline__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver can go Online/Offline</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Last_Used_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Last_Used_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Used Vehicle</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Service Resources (Last Used Vehicle)</relationshipLabel>
    <relationshipName>Service_Resources1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Primary_Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field auto-populates the Service Territory selected as the Primary Territory</description>
    <label>Primary Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Location.Facility__c</field>
            <operation>equals</operation>
            <valueField>$Source.Primary_Service_Territory__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceResourceSkill/fields/Skill_DeveloperName__c.field-meta.xml
<CustomField>
    <fullName>Skill_DeveloperName__c</fullName>
    <formula>Skill.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Skill_DeveloperName</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Driver_can_go_Online_Offline__c.field-meta.xml
<CustomField>
    <fullName>Driver_can_go_Online_Offline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Driver can go Online/Offline</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <description>Vehicles associated to a customer.  Member or non-member</description>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0}</displayFormat>
        <label>Vehicle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ServiceResourceOnlineOfflineController.cls
public with sharing class ServiceResourceOnlineOfflineController {

    @AuraEnabled(cacheable=true)
    public static /*ServiceResource*/Map<String,String> getServiceResource(String userId)
    {
        System.debug('getServiceResource');
        ServiceResource sr = [SELECT Id,Vehicle__c,Primary_Service_Territory__c,Driver_can_go_Online_Offline__c,Primary_Service_Territory__r.Driver_can_go_Online_Offline__c 
            FROM ServiceResource WHERE RelatedRecordId = :userId LIMIT 1];
        String stId = sr.Primary_Service_Territory__c;

        System.debug(sr.getSobject('Primary_Service_Territory__r'));

        //probably not really needed to break this down like this but did it for debugging an issue
        Map<String,String> result = new Map<String,String>();
        result.put('Id',sr.Id);
        result.put('Vehicle__c',sr.Vehicle__c);
        result.put('Primary_Service_Territory__c',sr.Primary_Service_Territory__c);
        result.put('Driver_can_go_Online_Offline__c',(sr.Driver_can_go_Online_Offline__c == true) ? 'true':'false');

        return result;
    }
    
    @AuraEnabled
    public static String goOnline(String resourceId)
    {
        try {
            //what if no last used vehicle??
            ServiceResource sr = [SELECT Id,Vehicle__c,Vehicle__r.Vehicle_Name__c,FSL__GanttLabel__c,Last_Used_Vehicle__c 
                FROM ServiceResource 
                WHERE Id = :resourceId LIMIT 1];
            sr.Vehicle__c = sr.Last_Used_Vehicle__c;
            update sr;
            return sr.Vehicle__c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void goOffline(String resourceId)
    {
        try {
            ServiceResource sr = [SELECT Id,Vehicle__c,FSL__GanttLabel__c,Last_Used_Vehicle__c 
                FROM ServiceResource 
                WHERE Id = :resourceId LIMIT 1];

            sr.FSL__GanttLabel__c = 'DRIVER OFFLINE';
            sr.Last_Used_Vehicle__c = sr.Vehicle__c;
            sr.Vehicle__c = NULL;
            //System.debug(sr);
            update sr;

            List<ServiceResourceSkill> skills = [SELECT Id FROM ServiceResourceSkill 
                WHERE ServiceResourceId = :resourceId AND Skill_DeveloperName__c LIKE 'VEH%'];
            //System.debug(skills);
            delete skills;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}