unpackaged/main/default/objects/Allocations__c/Allocations__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AN-{000}</displayFormat>
        <label>Allocations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Allocations__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Charge to Account</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASIC</fullName>
            </value>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>PREMIER</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Allocations__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <label>Approved Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/FSL_AllocationTriggerHandlerTest.cls
@isTest
class FSL_AllocationTriggerHandlerTest {
    @isTest
    static void validateOtherAccountTest() {
        Boolean hasError = false;
        String validationError = 'Other Account field must be populated if Charge to Account is "OTHER"';

        try {
            insert new Allocations__c(
                Account__c = 'OTHER',
                Approved__c  = 50.00
            );
        } catch (Exception e) {
            if (e.getMessage().contains(validationError)) {
                hasError = true;
            }
        }

        System.assertEquals(true, hasError, 'Failed to validate field.');
    }
}