unpackaged/main/default/objects/Allocations__c/Allocations__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AN-{000}</displayFormat>
        <label>Allocations</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Allocations__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Charge to Account</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BASIC</fullName>
            </value>
            <value>
                <fullName>PLUS</fullName>
            </value>
            <value>
                <fullName>PREMIER</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Allocations__c/fields/Other_Account__c.field-meta.xml
<CustomField>
    <fullName>Other_Account__c</fullName>
    <label>Other Accounts</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Account__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BASIC LKSMTH</fullName>
            </value>
            <value>
                <fullName>BASIC MBR_CH</fullName>
            </value>
            <value>
                <fullName>BASIC OM</fullName>
            </value>
            <value>
                <fullName>BASIC TW</fullName>
            </value>
            <value>
                <fullName>BATT MATCH</fullName>
            </value>
            <value>
                <fullName>BATT WAR AGM</fullName>
            </value>
            <value>
                <fullName>BATT WARR</fullName>
            </value>
            <value>
                <fullName>ESCHEATED</fullName>
            </value>
            <value>
                <fullName>GOOD WILL</fullName>
            </value>
            <value>
                <fullName>GW AGM</fullName>
            </value>
            <value>
                <fullName>GW APPEAL</fullName>
            </value>
            <value>
                <fullName>GW CCDISP</fullName>
            </value>
            <value>
                <fullName>GW MMTM</fullName>
            </value>
            <value>
                <fullName>GW PB</fullName>
            </value>
            <value>
                <fullName>GW PC</fullName>
            </value>
            <value>
                <fullName>GW REIM</fullName>
            </value>
            <value>
                <fullName>GW RETAIL</fullName>
            </value>
            <value>
                <fullName>GW TP</fullName>
            </value>
            <value>
                <fullName>LEGL REIM</fullName>
            </value>
            <value>
                <fullName>PLUS LKSMTH</fullName>
            </value>
            <value>
                <fullName>PLUS TW</fullName>
            </value>
            <value>
                <fullName>PR 200 ML TW</fullName>
            </value>
            <value>
                <fullName>PR BAT AGM</fullName>
            </value>
            <value>
                <fullName>PR BATT REM</fullName>
            </value>
            <value>
                <fullName>PR HOM LKOT</fullName>
            </value>
            <value>
                <fullName>PR LKSMTH</fullName>
            </value>
            <value>
                <fullName>PR ONTHE WAY</fullName>
            </value>
            <value>
                <fullName>PR TOLLS</fullName>
            </value>
            <value>
                <fullName>RECOV COST</fullName>
            </value>
            <value>
                <fullName>TRAV ACC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FSL_AllocationTriggerHandler.cls
public class FSL_AllocationTriggerHandler extends FSL_TriggerDispatcher.TriggerHandlerBase {
    List<Allocations__c> newList = Trigger.new;
    List<Allocations__c> oldList = Trigger.old;
    Map<Id, Allocations__c> newMap = (Map<Id, Allocations__c>) Trigger.newMap;
    Map<Id, Allocations__c> oldMap = (Map<Id, Allocations__c>) Trigger.oldMap;

    public override Boolean isDisabled() {
        return FSL_TriggerUtility.isDisabled('Allocations__c');
    }

    public override void beforeInsert() {
        validateOtherAccount(newList);
    }

    public static void validateOtherAccount(List<Allocations__c> allocations) {
        for (Allocations__c allocation : allocations) {
            if (allocation.Account__c == 'OTHER' && allocation.Other_Account__c == null) {
                allocation.addError('Other Account field must be populated if Charge to Account is "OTHER".');
            }
        }
    }
}