unpackaged/main/default/objects/VehicleServiceNotification__c/VehicleServiceNotification__c.object-meta.xml
<CustomObject>
    <label>Vehicle Service Notification</label>
    <nameField>
        <label>VehicleServiceNotification</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Service Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/VehicleServiceNotification__c/fields/Name_of_Triage_Tab__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Triage_Tab__c</fullName>
    <label>Name of Triage Tab</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/VehicleServiceNotification__c/fields/ServiceDescription__c.field-meta.xml
<CustomField>
    <fullName>ServiceDescription__c</fullName>
    <label>ServiceDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/VehicleServiceNotification__c/fields/ServiceNotificationText__c.field-meta.xml
<CustomField>
    <fullName>ServiceNotificationText__c</fullName>
    <label>ServiceNotificationText</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/VehicleServiceNotification__c/fields/VehicleMake__c.field-meta.xml
<CustomField>
    <fullName>VehicleMake__c</fullName>
    <label>VehicleMake</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/VehicleServiceNotification__c/fields/VehicleModel__c.field-meta.xml
<CustomField>
    <fullName>VehicleModel__c</fullName>
    <label>VehicleModel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/VehicleServiceNotification__c/fields/VehicleYear__c.field-meta.xml
<CustomField>
    <fullName>VehicleYear__c</fullName>
    <label>VehicleYear</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ERS_Case_VehicleNotificationMapping.cls
public class ERS_Case_VehicleNotificationMapping {
	@AuraEnabled(cacheable=true)
    public static String getVehicleNotification(String VehicleInfomation){

       string CurrentTab;
       string ServiceType;
       string VehicleYear;
       string VehicleMake;
       string VehicleModel;

       String setVehicleServiceNotification;     
       List<string> VehicleInfo = new List<string>();

        if (string.isNotEmpty(VehicleInfomation)){      
        VehicleInfo = VehicleInfomation.split('_');       
        CurrentTab = VehicleInfo[0].toUpperCase();
        ServiceType = VehicleInfo[0].toUpperCase();
        VehicleYear = VehicleInfo[1].toUpperCase();
        VehicleMake = VehicleInfo[2].toUpperCase();
        VehicleModel =VehicleInfo[3].toUpperCase();        
       
        System.debug('VehicleInfo ' +CurrentTab + ServiceType + VehicleYear + VehicleMake + VehicleModel );
  
        //Get all the custom object mappings specific to the Current tab.
            
        List<VehicleServiceNotification__c> NotificationList = [SELECT  ServiceNotificationText__c                                          
                                                                        FROM VehicleServiceNotification__c
																        WHERE Name_of_Triage_Tab__c =:CurrentTab   
                                                                        AND ServiceDescription__c  =:ServiceType 
                                                                        AND  VehicleYear__c  =:VehicleYear 
                                                                        AND  VehicleMake__c  =:VehicleMake  
                                                                        AND  VehicleModel__c  =:VehicleModel                                                                                                                                  
                                                                        ];    
             
           
       
        if(!NotificationList.isEmpty()){
            	//Search through the custom object records
                for(VehicleServiceNotification__c NotificationRec : NotificationList){
                if ( VehicleInfomation!=NULL && NotificationRec.ServiceNotificationText__c!= NULL ) 
                {  
                    setVehicleServiceNotification= NotificationRec.ServiceNotificationText__c;  
                }
            }
        }
        
    }
    return  setVehicleServiceNotification;   
      
  }
}