unpackaged/main/default/objects/FSL_Application_Log__c/FSL_Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>AN-{00000000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Unscheduling</fullName>
            </value>
            <value>
                <fullName>Glympse</fullName>
            </value>
            <value>
                <fullName>CallCreate</fullName>
            </value>
            <value>
                <fullName>GlympseOut</fullName>
            </value>
            <value>
                <fullName>GlympseIn</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>AddressChange</fullName>
            </value>
            <value>
                <fullName>RoutingChange</fullName>
            </value>
            <value>
                <fullName>LKL</fullName>
            </value>
            <value>
                <fullName>Call Clear</fullName>
            </value>
            <value>
                <fullName>ETALog</fullName>
            </value>
            <value>
                <fullName>IVRLookup</fullName>
            </value>
            <value>
                <fullName>ServiceTrackingLog</fullName>
            </value>
            <value>
                <fullName>WOCreateEventLog</fullName>
            </value>
            <value>
                <fullName>WOStatusUpdateLog</fullName>
            </value>
            <value>
                <fullName>RetrieveWorkOrders</fullName>
            </value>
            <value>
                <fullName>Update Facility</fullName>
            </value>
            <value>
                <fullName>Delayed Copy to Clear Queue</fullName>
            </value>
            <value>
                <fullName>CalculateDistanceInMiles</fullName>
            </value>
            <value>
                <fullName>ServiceLineItemFailed</fullName>
            </value>
            <value>
                <fullName>ValidateWaitTime</fullName>
            </value>
            <value>
                <fullName>CalculatedMileage</fullName>
            </value>
            <value>
                <fullName>Clear Queue</fullName>
            </value>
            <value>
                <fullName>UpsertResourceAbsence</fullName>
            </value>
            <value>
                <fullName>WOJeopardyAPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/FSL_DeleteApplicationLogs.cls
/*
*********************************************************************************************************
Class         :  FSL_DeletepriorResourceAbsenceList_Batch.cls
Objective    :  This batch is to delete Application Logs based on the time period given by Running user 
*********************************************************************************************************

//Script for Running Batch Manually 

/*FSL_DeleteApplicationLogs  delApplogs= new FSL_DeleteApplicationLogs('FSL_Application_Log__c',30);
      Database.executeBatch(delApplogs);*/

public class FSL_DeleteApplicationLogs /*implements Database.Batchable<sObject>,Schedulable*/ {
    // public final Integer NoOfDaysCreatedAgo;
    // public final String Operation;
    // public final string APIName;
    
    // public FSL_DeleteApplicationLogs (Integer noOfDaysCreatedAgo,String Operation, string APIName) {
        
    //     this.NoOfDaysCreatedAgo= NoOfDaysCreatedAgo;
    //     this.Operation = Operation;
    //     this.APIName = APIName;
    // }
    
    // public Database.QueryLocator start(Database.BatchableContext bc){
    //     String queryString = 'SELECT ID, Operation__c' + ' FROM FSL_Application_Log__c ' +
    //         ' WHERE Operation__c=\'' +Operation+ '\' AND API_Name__c=\'' +APIName+ '\' AND createdDate < LAST_N_DAYS:'+NoOfDaysCreatedAgo;

    //     system.debug('---------------'+queryString);
    //     return Database.getQueryLocator(queryString);
    // }        
    
    // public void execute(Database.BatchableContext bc, List<sObject> scope){       
    //     List<FSL_Application_Log__c> aplist= (List<FSL_Application_Log__c>)scope;
    //     System.debug('======>'+scope);
    //     delete aplist;
    // }
    
    // public void finish(Database.BatchableContext bc){
    //   AsyncApexJob a = [Select Id, Status,ExtendedStatus,NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email    from AsyncApexJob where Id =:BC.getJobId()];
    //     Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    //     String[] toAddresses = new String[] {a.CreatedBy.Email};
    //     mail.setToAddresses(toAddresses);
    //     mail.setSubject('Delete Application Logs ' + a.Status);
    //     mail.setPlainTextBody('records processed ' + a.TotalJobItems +   ' with '+ a.NumberOfErrors + ' failures.');
    //     Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    // }
        
    // public void execute(SchedulableContext sc) {
    //     Database.executeBatch(new FSL_DeleteApplicationLogs(10,'Update',''));
    // }
}