unpackaged/main/default/objects/FSL_Application_Log__c/FSL_Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>AN-{00000000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Unscheduling</fullName>
            </value>
            <value>
                <fullName>Glympse</fullName>
            </value>
            <value>
                <fullName>CallCreate</fullName>
            </value>
            <value>
                <fullName>GlympseOut</fullName>
            </value>
            <value>
                <fullName>GlympseIn</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>AddressChange</fullName>
            </value>
            <value>
                <fullName>RoutingChange</fullName>
            </value>
            <value>
                <fullName>LKL</fullName>
            </value>
            <value>
                <fullName>Call Clear</fullName>
            </value>
            <value>
                <fullName>ETALog</fullName>
            </value>
            <value>
                <fullName>IVRLookup</fullName>
            </value>
            <value>
                <fullName>ServiceTrackingLog</fullName>
            </value>
            <value>
                <fullName>WOCreateEventLog</fullName>
            </value>
            <value>
                <fullName>WOStatusUpdateLog</fullName>
            </value>
            <value>
                <fullName>RetrieveWorkOrders</fullName>
            </value>
            <value>
                <fullName>Update Facility</fullName>
            </value>
            <value>
                <fullName>Delayed Copy to Clear Queue</fullName>
            </value>
            <value>
                <fullName>CalculateDistanceInMiles</fullName>
            </value>
            <value>
                <fullName>ServiceLineItemFailed</fullName>
            </value>
            <value>
                <fullName>ValidateWaitTime</fullName>
            </value>
            <value>
                <fullName>CalculatedMileage</fullName>
            </value>
            <value>
                <fullName>Clear Queue</fullName>
            </value>
            <value>
                <fullName>UpsertResourceAbsence</fullName>
            </value>
            <value>
                <fullName>WOJeopardyAPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Application Logs</relationshipLabel>
    <relationshipName>Application_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FSL_Calculated_Mileage_Line_Item__c/FSL_Calculated_Mileage_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Calculated Mileage Line Item</label>
    <nameField>
        <displayFormat>CMLI - {0000}</displayFormat>
        <label>CMLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calculated Mileage Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Calculated_Mileage_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Product2.ProductCode</field>
            <operation>equals</operation>
            <value>CE</value>
        </filterItems>
        <filterItems>
            <field>Product2.ProductCode</field>
            <operation>equals</operation>
            <value>CT</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Calculated Mileage Line Items</relationshipLabel>
    <relationshipName>Calculated_Mileage_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FSL_Calculated_Mileage_Line_Item__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Quantity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Calculated_Mileage_Line_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>Calculated_Mileage_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FSL_MileageCalculatedUtilityTest.cls
/**
 * @File Name          : FSL_MileageCalculatedUtilityTest.cls
 * @Description        : 
 * @Author             : Dylan Truong
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 09/20/2021
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    09/20/2021   Dylan Truong          ERS-223670 :Updates to Mileage and ER Calculation
*  1.1    10/25/2021   Dylan Truong          ERS-226141 :Reimplement Calculate Mileage by Using Bing Webservice instead built in DISTANCE Function
*  1.2    11/25/2021   Dylan Truong          ERS-222039 :Reimplement Calculate Mileage: Replace Exist OM/TW Logic With New CE/CT Service Line Items Logic
**/

@IsTest
public with sharing class FSL_MileageCalculatedUtilityTest {
        @IsTest
        static void testCalculateMileageFromFlow(){
            FSL_MileageCalculatedUtility.CalculateMileage calMileage =  new FSL_MileageCalculatedUtility.CalculateMileage();
            Product2  p = new Product2 (productCode='OM');
            WorkOrder wo = new WorkOrder();
    
            calMileage.originLatitude = '33.847';
            calMileage.originLongitude = '-118.231';
            calMileage.destinationLatitude = '33.727972';
            calMileage.destinationLongitude = '-117.790392';
            calMileage.workOrderId = wo.Id;
            calMileage.productCode = 'OM';
            List<FSL_MileageCalculatedUtility.CalculateMileage> calMileages = new List<FSL_MileageCalculatedUtility.CalculateMileage>();
            calMileages.add(calMileage);
            Test.startTest();
            FSL_MileageCalculatedUtility.calculateMileageFromFlow(calMileages);
            Test.stopTest();
            List<FSL_Calculated_Mileage_Line_Item__c> sli = [SELECT Id, Product__c, Work_Order__c, Unit__c FROM FSL_Calculated_Mileage_Line_Item__c WHERE  Product__c=:p.Id];
            System.assertEquals(true, sli.size()>0);
            
        }

        @IsTest
        static void testCalculateMileageFromFlow_Exception(){
            FSL_MileageCalculatedUtility.CalculateMileage calMileage =  new FSL_MileageCalculatedUtility.CalculateMileage();
            Product2  p = new Product2 (productCode='OM');
            WorkOrder wo = new WorkOrder();
            calMileage.originLatitude = '33.847';
            calMileage.originLongitude = '-118.231';
            calMileage.destinationLatitude = '33.727972';
            calMileage.destinationLongitude = '0';
            calMileage.workOrderId = wo.Id;
            calMileage.productCode = 'OM';
            FSL_MileageCalculatedUtility.CalculateMileageService calService = new FSL_MileageCalculatedUtility.CalculateMileageService(calMileage);
            calService.distanceService = new MappingServiceMock(true);
                    
            Test.startTest();
            calService.calculateDistance();
            Test.getEventBus().deliver();
            Test.stopTest();
            List<FSL_Application_Log__c> appLogs = [SELECT Id, Operation__c, Error_Message__c FROM FSL_Application_Log__c];
            System.assertEquals(true, appLogs.size() > 0);
        
        }
    
        @IsTest
        static void testCalculateDistanceInMile(){
   
            FSL_MileageCalculatedUtility.CalculateMileage calMileage =  new FSL_MileageCalculatedUtility.CalculateMileage();
            calMileage.originLatitude = '33.847';
            calMileage.originLongitude = '-118.231';
            calMileage.destinationLatitude = '33.727972';
            calMileage.destinationLongitude = '-117.790392';
            FSL_MileageCalculatedUtility.CalculateMileageService calService = new FSL_MileageCalculatedUtility.CalculateMileageService(calMileage);
            calService.distanceService = new MappingServiceMock(false); 
            Test.startTest();
            Decimal distance = calService.calculateDistanceInMile();
            Test.stopTest();
            System.assertEquals(1.0,distance);
        }

        public class MappingServiceMock implements FSL_Mapping.IMap {
            private Boolean isException = false;
            public MappingServiceMock(Boolean isException) {
                this.isException = isException;
            }

            public Decimal calculateDistanceInMiles( Double latOrigin, Double longOrigin, Double latDestination, Double longDestination ) {
                if (isException) {
                    throw new MockingException();
                } else {
                    return 1.0; 
                }
                
            }
        }

        public class MockingException extends Exception {

        }

    

}