unpackaged/main/default/objects/FSL_Application_Log__c/FSL_Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>AN-{00000000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Application_Log__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Query</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Clear</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Unscheduling</fullName>
            </value>
            <value>
                <fullName>Glympse</fullName>
            </value>
            <value>
                <fullName>CallCreate</fullName>
            </value>
            <value>
                <fullName>GlympseOut</fullName>
            </value>
            <value>
                <fullName>GlympseIn</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>AddressChange</fullName>
            </value>
            <value>
                <fullName>RoutingChange</fullName>
            </value>
            <value>
                <fullName>LKL</fullName>
            </value>
            <value>
                <fullName>Call Clear</fullName>
            </value>
            <value>
                <fullName>ETALog</fullName>
            </value>
            <value>
                <fullName>IVRLookup</fullName>
            </value>
            <value>
                <fullName>ServiceTrackingLog</fullName>
            </value>
            <value>
                <fullName>WOCreateEventLog</fullName>
            </value>
            <value>
                <fullName>WOStatusUpdateLog</fullName>
            </value>
            <value>
                <fullName>RetrieveWorkOrders</fullName>
            </value>
            <value>
                <fullName>Update Facility</fullName>
            </value>
            <value>
                <fullName>Delayed Copy to Clear Queue</fullName>
            </value>
            <value>
                <fullName>CalculateDistanceInMiles</fullName>
            </value>
            <value>
                <fullName>ServiceLineItemFailed</fullName>
            </value>
            <value>
                <fullName>ValidateWaitTime</fullName>
            </value>
            <value>
                <fullName>CalculatedMileage</fullName>
            </value>
            <value>
                <fullName>Clear Queue</fullName>
            </value>
            <value>
                <fullName>UpsertResourceAbsence</fullName>
            </value>
            <value>
                <fullName>WOJeopardyAPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/Reciprocal__c.object-meta.xml
<CustomObject>
    <label>Reciprocal</label>
    <nameField>
        <displayFormat>REC-{000}</displayFormat>
        <label>Reciprocal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reciprocals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reciprocal__c/fields/Member__c.field-meta.xml
<CustomField>
    <fullName>Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reciprocals</relationshipLabel>
    <relationshipName>Reciprocals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Member_ID__c.field-meta.xml
<CustomField>
    <fullName>Member_ID__c</fullName>
    <label>Member ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Reciprocals</relationshipLabel>
    <relationshipName>Reciprocals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ReciprocalServiceContractLkpQueueable.cls
public class ReciprocalServiceContractLkpQueueable implements Queueable, Database.AllowsCallouts {
	public Map<Id, Reciprocal__c> reciprocals = new Map<Id, Reciprocal__c>();
    
    public ReciprocalServiceContractLkpQueueable (Map<Id, Reciprocal__c> rcpls ) {
        reciprocals = rcpls;
    }
    
    public void execute(QueueableContext qc) {
        Map<Id, Reciprocal__c> reciprocalsProc = new Map<Id, Reciprocal__c>();
        List<Reciprocal__c> updateRecList = new List<Reciprocal__c>();
		List<FSL_Application_Log__c> appLogInsertList = new List<FSL_Application_Log__c>();
        Integer noOfElements = 0;
        
        if (reciprocals.size() > 0) {
            for(Reciprocal__c rec : reciprocals.values()) {
				//Restricting to 1 record because there is a call to Class.Util_ManageAccessTokens.callOAuth which needs to save current record
            	if (noOfElements >= 1) {
					break; 
				} 

                reciprocalsProc.put(rec.Id, rec);
            	reciprocals.remove(rec.Id);
            	noOfElements++;
            }      
            
        	for(Reciprocal__c rec : reciprocalsProc.values()) {
            	if (!String.isBlank(rec.Member_Id__c)) {
					Map<String, String> mapRequestParams  = new Map<String, String>{
						'memberId' => rec.Member_Id__c
					};

            		if (mapRequestParams != null && !mapRequestParams.isEmpty()) {
            			try {
            				ACG_GlobalSearchController.Results res = 
								ACG_GlobalSearchController.invokeMembershipAPIs(
									'lookup', mapRequestParams, ''
								);

                			rec.Member__c = res?.updatedRecordId;
							rec.Service_Contract__c = res?.contract?.contractId;
                			updateRecList.add(rec);
            			} catch (Exception e) {
							String errMsg = e.getMessage() + '\n\n' + e.getStackTraceString();

							appLogInsertList.add(
								new FSL_Application_Log__c(
									Operation__c = 'ReciprocalServiceContractLkpQueueable',
									Error_Message__c = errMsg
								)
							);
        				}
        			}
        		}
        	}
        }
        
		if (updateRecList.size() > 0) {
			update updateRecList;
		}

		if (appLogInsertList.size() > 0) {
			insert appLogInsertList;
		}
        
        if (reciprocals.size() > 0) {
			System.enqueueJob(new ReciprocalServiceContractLkpQueueable(reciprocals));
        }
    }
}