unpackaged/main/default/objects/FSL_User_Message__c/FSL_User_Message__c.object-meta.xml
<CustomObject>
    <label>User Message</label>
    <nameField>
        <displayFormat>UM-{000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_User_Message__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <description>Message Id per requirements documentation</description>
    <label>Message Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/FSL_User_Message__c/fields/Message_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Text__c</fullName>
    <description>Message verbiage displayed to the user</description>
    <label>Message Text</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/FSL_User_Message__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassignment</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>En Route</fullName>
            </value>
            <value>
                <fullName>On Location</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>In Tow</fullName>
            </value>
            <value>
                <fullName>Tow Complete</fullName>
            </value>
            <value>
                <fullName>Override Resource Preference</fullName>
            </value>
            <value>
                <fullName>Tow Loaded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Override_Resource_Preference__c/Override_Resource_Preference__c.object-meta.xml
<CustomObject>
    <label>Override Resource Preference</label>
    <nameField>
        <label>Override Resource Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Override Resource Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Override_Resource_Preference__c/fields/Scheduling_Override__c.field-meta.xml
<CustomField>
    <fullName>Scheduling_Override__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Scheduling Override</label>
    <referenceTo>Service_Territory_Scheduling_Override__c</referenceTo>
    <relationshipLabel>Override Resource Preferences</relationshipLabel>
    <relationshipName>Override_Resource_Preferences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Override_Resource_Preference__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Override Resource Preferences</relationshipLabel>
    <relationshipName>Override_Resource_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Override_Resource_Preference__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Override Resource Preferences</relationshipLabel>
    <relationshipName>Override_Resource_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Override_Resource_Preference__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Excluded</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Service_Territory_Scheduling_Override__c/Service_Territory_Scheduling_Override__c.object-meta.xml
<CustomObject>
    <label>Service Territory Scheduling Override</label>
    <nameField>
        <label>Service Territory Scheduling Override Na</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Territory Scheduling Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Service_Territory_Scheduling_Override__c/fields/Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Service_Territory__c</fullName>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Territory Scheduling Overrides</relationshipLabel>
    <relationshipName>Service_Territory_Scheduling_Overrides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Primary_Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>Primary_Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field auto-populates the Service Territory selected as the Primary Territory</description>
    <label>Primary Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Service Resources</relationshipLabel>
    <relationshipName>Service_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Zip_Code_Coverage__c/Zip_Code_Coverage__c.object-meta.xml
<CustomObject>
    <label>Zip Code Coverage</label>
    <nameField>
        <label>Zip Code Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Coverage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Zip_Code_Coverage__c/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Zip Code Coverage</relationshipLabel>
    <relationshipName>Service_Resource</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FSL_OverrideResourcePrefTriggerHandler.cls
public with sharing class FSL_OverrideResourcePrefTriggerHandler extends FSL_TriggerDispatcher.TriggerHandlerBase {

    List<Override_Resource_Preference__c> newList = Trigger.new;
    List<Override_Resource_Preference__c> oldList = Trigger.old;
    Map<Id, Override_Resource_Preference__c> newMap = (Map<Id, Override_Resource_Preference__c>)Trigger.newMap;
    Map<Id, Override_Resource_Preference__c> oldMap = (Map<Id, Override_Resource_Preference__c>)Trigger.oldMap;

    //========================================================================================================================
    //========================================================================================================================
    public override Boolean isDisabled() {
        return FSL_TriggerUtility.isDisabled('Override_Resource_Preference__c');
    }

    //========================================================================================================================
    //========================================================================================================================
    public override void beforeInsert() {
        validatePreferenceEntries(newList);
    }

    //========================================================================================================================
    //========================================================================================================================
    public override void beforeUpdate() {
        validatePreferenceEntries(newList);
    }


    //========================================================================================================================
    //========================================================================================================================
    //========================================================================================================================


    public static void validatePreferenceEntries(List<Override_Resource_Preference__c> newOrps) {
        System.debug('Entering Validate Preference Entries');
        try{
            Map<String, String> errorMessages = FSL_OverrideResourcePrefTriggerHandler.getErrorMessages();
            List<Id> overrideIds = new List<Id>();
            List<Id> resourceIds = new List<Id>();
            for(Override_Resource_Preference__c orp : newOrps){
                overrideIds.add(orp.Scheduling_Override__c);
                resourceIds.add(orp.Service_Resource__c);
            }
            Map<Id, ServiceResource> newOrpResourceMap = new Map<Id, ServiceResource>([SELECT Id, Primary_Service_Territory__c FROM ServiceResource WHERE Id IN :resourceIds]);
            Map<Id, Service_Territory_Scheduling_Override__c> overrideMap = new Map<Id, Service_Territory_Scheduling_Override__c>([SELECT Id, (SELECT Name, Type__c, Service_Territory__c, Service_Resource__c, Service_Resource__r.Primary_Service_Territory__c FROM Override_Resource_Preferences__r) FROM Service_Territory_Scheduling_Override__c WHERE Id IN :overrideIds]);
            for(Override_Resource_Preference__c newOrp : newOrps){
                for(Override_Resource_Preference__c existingOrp : overrideMap.get(newOrp.Scheduling_Override__c).Override_Resource_Preferences__r){
                    if(newOrp.Service_Territory__c != null && existingOrp.Service_Territory__c != null){
                        if(newOrp.Service_Territory__c == existingOrp.Service_Territory__c && newOrp.Id != existingOrp.Id){
                            newOrp.addError(errorMessages.get('Territory-Territory Match'));
                            System.debug('Adding error on ' + newOrp.Name);
                        }
                    } else if(newOrp.Service_Territory__c != null && existingOrp.Service_Territory__c == null && newOrp.Id != existingOrp.Id){
                        if(newOrp.Service_Territory__c == existingOrp.Service_Resource__r.Primary_Service_Territory__c){
                            newOrp.addError(errorMessages.get('Territory-Resource Primary Match'));
                            System.debug('Adding error on ' + newOrp.Name);
                        }
                    } else if(newOrp.Service_Resource__c != null && existingOrp.Service_Resource__c != null && newOrp.Id != existingOrp.Id){
                        if(newOrp.Service_Resource__c == existingOrp.Service_Resource__c){
                            newOrp.addError(errorMessages.get('Resource-Resource Match'));
                            System.debug('Adding error on ' + newOrp.Name);
                        }
                    } else if(newOrp.Service_Resource__c != null && existingOrp.Service_Resource__c == null){
                        if(newOrpResourceMap.get(newOrp.Service_Resource__c).Primary_Service_Territory__c == existingOrp.Service_Territory__c && newOrp.Id != existingOrp.Id){
                            newOrp.addError(errorMessages.get('Resource Primary-Territory Match'));
                            System.debug('Adding error on ' + newOrp.Name);
                        }
                    }
                }
            }
        }catch (Exception e){
            System.debug('Error Caught Validating Override Resource Preferences: ' + e);
            System.debug(e.getStackTraceString());
        }
    }

    public static Map<String, String> getErrorMessages(){
        Map<String, String> errorMessageMap = new Map<String, String>();
        Map<String, String> defaultMessages = new Map<String, String>();
        for(FSL_User_Message__c um : [SELECT Id, Message_Id__c, Message_Text__c FROM FSL_User_Message__c WHERE Reference__c = 'Override Resource Preference']){
            errorMessageMap.put(um.Message_Id__c, um.Message_Text__c);
        }
        defaultMessages.put('Territory-Territory Match', 'The Service Territory matches an existing Territory Preference on the override');
        defaultMessages.put('Territory-Resource Primary Match', 'The Service Territory matches an existing Resource Preference\'s Primary Service Territory on the override');
        defaultMessages.put('Resource-Resource Match', 'The Service Resource matches an existing Resource Preference on the override');
        defaultMessages.put('Resource Primary-Territory Match', 'The Service Resource\'s Primary Service Territory matches an existing Territory Preference on the override');
        
        if(errorMessageMap.size() != 4){
            return defaultMessages;
        } else {
            return errorMessageMap;
        }
    }
}