unpackaged/main/default/objects/ERS_Watch_List__c/ERS_Watch_List__c.object-meta.xml
<CustomObject>
    <description>Tracks membership information for members on the ERS watch list.</description>
    <label>ERS Watch List Member</label>
    <nameField>
        <displayFormat>EWL-{0000}</displayFormat>
        <label>ERS Watch List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERS Watch List Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ERS_Watch_List__c/fields/AAA_ACA_AssociateID__c.field-meta.xml
<CustomField>
    <fullName>AAA_ACA_AssociateID__c</fullName>
    <label>Associate Id</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ERS_Watch_List__c/fields/AAA_ACA_Club_Code__c.field-meta.xml
<CustomField>
    <fullName>AAA_ACA_Club_Code__c</fullName>
    <label>Club Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ERS_Watch_List__c/fields/AAA_ACA_MembershipID__c.field-meta.xml
<CustomField>
    <fullName>AAA_ACA_MembershipID__c</fullName>
    <label>Member ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Winter_Advisory__c/Winter_Advisory__c.object-meta.xml
<CustomObject>
    <description>General service advisory text</description>
    <label>Service Advisory</label>
    <nameField>
        <label>Winter Advisory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Advisories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Winter_Advisory__c/fields/Advisory_Message_Display__c.field-meta.xml
<CustomField>
    <fullName>Advisory_Message_Display__c</fullName>
    <label>Advisory Message Display</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Winter_Advisory__c/recordTypes/ERS_Watch_List.recordType-meta.xml
<RecordType>
    <fullName>ERS_Watch_List</fullName>
    <active>true</active>
    <description>Warning type for ERS Watch List. Only one active record will be displayed at a time.</description>
    <label>ERS Watch List</label>
</RecordType>

unpackaged/main/default/classes/WatchListHelper.cls
/**
* @File Name : WatchListHelper.cls
* @Description : For https://aaa-ne.atlassian.net/browse/SSFI-931, Gets active warning for ERS watch list
* @Author : John Orzechowski
* @Last Modified On : June 4, 2025 - updated getWatchListStatus to handle null Account_Member_Id
**/


public without sharing class WatchListHelper {
	@AuraEnabled(cacheable=true)
    public static String getWarningText() {
           Winter_Advisory__c[] adv = [
                SELECT Advisory_Message_Display__c 
                FROM Winter_Advisory__c
                WHERE RecordType.DeveloperName = 'ERS_Watch_List' 
                AND Active__c = true
                Limit 1
            ]; 
            
            if (adv.size() > 0) {
             return adv[0].Advisory_Message_Display__c;
            }
            else {
                return null;
            }

    }

    @AuraEnabled(cacheable=true)
    public static Boolean getWatchListStatus(String AAA_ACA_Club_Code, String AAA_ACA_MembershipID, String AAA_ACA_AssociateId, String Account_Member_Id) {
        
        
        ERS_Watch_List__c[] ewlm = new List<ERS_Watch_List__c>(); 

        if( Account_Member_Id?.length() == 16 ) {
            String AccountClubCode = String.escapeSingleQuotes(Account_Member_Id).mid(3,3); 
            String AccountMembershipId = String.escapeSingleQuotes(Account_Member_Id).mid(6,7);
            String AccountAssociateId = String.escapeSingleQuotes(Account_Member_Id).mid(13,2);
            

            ewlm = [
                SELECT Id 
                FROM ERS_Watch_List__c
                WHERE (( AAA_ACA_Club_Code__c = :AAA_ACA_Club_Code 
                AND AAA_ACA_MembershipID__c = :AAA_ACA_MembershipID
                AND AAA_ACA_AssociateID__c = :AAA_ACA_AssociateId ) 
                OR ( AAA_ACA_Club_Code__c = :AccountClubCode
                AND AAA_ACA_MembershipID__c = :AccountMembershipId 
                AND AAA_ACA_AssociateID__c = :AccountAssociateId ))
                AND Active__c = true
                LIMIT 1
            ];
        } else {
            ewlm = [
                SELECT Id 
                FROM ERS_Watch_List__c
                WHERE  AAA_ACA_Club_Code__c = :AAA_ACA_Club_Code 
                AND AAA_ACA_MembershipID__c = :AAA_ACA_MembershipID
                AND AAA_ACA_AssociateID__c = :AAA_ACA_AssociateId 
                AND Active__c = true
                LIMIT 1
            ];
        }

        if (ewlm.size() > 0) {
            return TRUE; 
        }
        else {
            return FALSE;
        } 


    }
}