unpackaged/main/default/objects/BackOffice_Settings__c/BackOffice_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>BackOffice Settings</label>
</CustomObject>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/FSL_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SLI - {0000}</displayFormat>
        <label>SLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Calculated_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Unit__c</fullName>
    <label>Calculated Quantity (TW/OM)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Override_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Override_Pricing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Pricing</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Quantity</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FSL_TroubleCode__c/FSL_TroubleCode__c.object-meta.xml
<CustomObject>
    <label>TroubleCode</label>
    <nameField>
        <displayFormat>TR Code -{0000}</displayFormat>
        <label>TroubleCode Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TroubleCodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_TroubleCode__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_TroubleCode__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>TroubleCodes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Club_Code__c.field-meta.xml
<CustomField>
    <fullName>Club_Code__c</fullName>
    <label>Club Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
            </value>
            <value>
                <fullName>002</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>014</fullName>
            </value>
            <value>
                <fullName>018</fullName>
            </value>
            <value>
                <fullName>020</fullName>
            </value>
            <value>
                <fullName>023</fullName>
            </value>
            <value>
                <fullName>036</fullName>
            </value>
            <value>
                <fullName>045</fullName>
            </value>
            <value>
                <fullName>047</fullName>
            </value>
            <value>
                <fullName>049</fullName>
            </value>
            <value>
                <fullName>057</fullName>
            </value>
            <value>
                <fullName>065</fullName>
            </value>
            <value>
                <fullName>066</fullName>
            </value>
            <value>
                <fullName>069</fullName>
            </value>
            <value>
                <fullName>071</fullName>
            </value>
            <value>
                <fullName>080</fullName>
            </value>
            <value>
                <fullName>084</fullName>
            </value>
            <value>
                <fullName>104</fullName>
            </value>
            <value>
                <fullName>111</fullName>
            </value>
            <value>
                <fullName>113</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>130</fullName>
            </value>
            <value>
                <fullName>137</fullName>
            </value>
            <value>
                <fullName>160</fullName>
            </value>
            <value>
                <fullName>177</fullName>
            </value>
            <value>
                <fullName>188</fullName>
            </value>
            <value>
                <fullName>195</fullName>
            </value>
            <value>
                <fullName>212</fullName>
            </value>
            <value>
                <fullName>240</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <label>Facility Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Clearing_Code__c.field-meta.xml
<CustomField>
    <fullName>Clearing_Code__c</fullName>
    <label>Clearing Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clear_Codes</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <formula>ServiceTerritory.Facility_Number__c</formula>
    <label>Facility Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/In_Tow_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>In_Tow_Timestamp__c</fullName>
    <label>In Tow Timestamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/On_Location_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>On_Location_Timestamp__c</fullName>
    <label>On Location Timestamp</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Record_Type_Dev_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Dev_Name__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <label>Record Type Dev Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Resolution_Code__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Code__c</fullName>
    <label>Resolution Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CAR_ConsolidatedResoCodes</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Tow.recordType-meta.xml
<RecordType>
    <fullName>Tow</fullName>
    <active>true</active>
    <label>Tow</label>
</RecordType>

unpackaged/main/default/classes/AAAWorkOrderClearCodeLogicInvokable.cls
global without sharing class AAAWorkOrderClearCodeLogicInvokable {
    @InvocableMethod(label = 'Call Clear Code Logic')
    global static List<FlowOutput> runClearCodeLogic(List<FlowInput> input) {
        List<FlowOutput> outputList = new List<FlowOutput>();

        if (input != null && input.size() > 0) {
            BackOffice_Settings__c boSettings = BackOffice_Settings__c.getOrgDefaults();
            
            for (FlowInput flowInput : input) {
                FlowOutput output = new FlowOutput();
                WorkOrder wo = flowInput.workOrder;
                List<FSL_Service_Line_Item__c> sliList = flowInput.sliList;
                Boolean woIsUpdated = false;

                if (boSettings.Club_Code__c == '212' || boSettings.Club_Code__c == 'TTT') {
                    List<FSL_TroubleCode__c> troubleCodeLists = [
                        SELECT Id, Code__c 
                        FROM FSL_TroubleCode__c 
                        WHERE Work_Order__c =: wo.Id
                    ];
                    ServiceTerritory svcTerritory = [
                        SELECT Id, Facility_Number__c 
                        FROM ServiceTerritory 
                        WHERE Id =: wo.ServiceTerritoryId
                        LIMIT 1
                    ]; 
                    Boolean troubleCodeStartWithSix = false;
                    Boolean troubleCodeNotInOneEight = true;
                    Boolean troubleCodeCheckWhenSLIIsBA = false;
                    List<String> troubleCodeListOneEight = new List<String>{'1', '8'};
                    List<String> troubleCodeListSLIIsBA = new List<String>{'0', '1', '1V', '5', '7', '7A', '7B', '7C', '7H', '7L'};
                    List<String> facListOHB = new List<String>{'OHB01', 'OHB02', 'OHB03', '0HB04'};
                    List<String> clearingCodeBA = new List<String>{'2G', '2T', 'BN', 'SD', 'SF'};
        
                    for (FSL_TroubleCode__c currTroubleCode : troubleCodeLists) {
                        String troubleCode = currTroubleCode.Code__c;
        
                        if (troubleCode?.startsWith('6')) {
                            troubleCodeStartWithSix = true;  
                        }
        
                        if (troubleCodeListOneEight.contains(troubleCode)) {
                            troubleCodeNotInOneEight = false;
                        }
        
                        if (troubleCodeListSLIIsBA.contains(troubleCode)) {
                            troubleCodeCheckWhenSLIIsBA = true;
                        }
                    } 
                    
                    if (wo.Clearing_Code__c != 'XX') {
                        for (FSL_Service_Line_Item__c currSLI : sliList) {
                            if (
                                String.isNotBlank(wo.Resolution_Code__c)
                                && wo.Resolution_Code__c.startsWith('G') 
                                && currSLI.Product_Code__c == 'TW' 
                                && troubleCodeStartWithSix
                            ) {
                                currSLI.Unit__c = 0;
                                currSLI.Cost__c = 0;
                                currSLI.Override_Pricing__c = true;

                                if (boSettings.Club_Code__c == '212') {
                                    wo.Clearing_Code__c = '2G';
                                } else if (Test.isRunningTest()) {
                                    wo.Clearing_Code__c = 'XX';
                                }

                                woIsUpdated = true;
                            } else if (
                                troubleCodeStartWithSix 
                                && currSLI.Product_Code__c == 'WN' 
                                && svcTerritory.Facility_Number__c != 'TUL'
                                && !svcTerritory.Facility_Number__c?.endsWith('N')
                                && (
                                    (wo.In_Tow_Timestamp__c?.second() - wo.On_Location_Timestamp__c?.second()) < 30 
                                )
                            ) {
                                currSLI.Unit__c = 0; 
                                currSLI.Cost__c = 0;
                                currSLI.Override_Pricing__c = true;
                            } else if (!troubleCodeStartWithSix && currSLI.Product_Code__c == 'MX') {
                                currSLI.Cost__c = 0;
                                currSLI.Override_Pricing__c = true;    
                            } else if (
                                !troubleCodeStartWithSix 
                                && troubleCodeNotInOneEight
                                && !facListOHB.contains(svcTerritory.Facility_Number__c)
                                && (
                                    currSLI.Product_Code__c == 'MA' 
                                    || currSLI.Product_Code__c == 'PP'
                                )
                            ) {
                                currSLI.Unit__c = 0;
                                currSLI.Cost__c = 0;
                                currSLI.Unit_Price__c = 0;
                                currSLI.Override_Pricing__c = true; 
                            } else if (
                                currSLI.Product_Code__c == 'BA' 
                                && troubleCodeCheckWhenSLIIsBA == true 
                                && wo.Resolution_Code__c?.startsWith('N') 
                                && (
                                    clearingCodeBA.contains(wo.Clearing_Code__c)
                                    || boSettings.Club_Code__c == 'TTT'
                                )
                                && wo.On_Location_Timestamp__c != null 
                                && wo.In_Tow_Timestamp__c == null
                            ) {
                                wo.Clearing_Code__c = 'NG';
                                woIsUpdated = true;
                            } else if (
                                troubleCodeStartWithSix 
                                && wo.Resolution_Code__c?.startsWith('N') 
                                && wo.On_Location_Timestamp__c != null 
                                && wo.In_Tow_Timestamp__c != null 
                                && wo.Clearing_Code__c == 'BN'
                            ) {
                                // wo.Clearing_Code__c = '2T';   
                            }      
                        }                        
                    }
                } else if (boSettings.Club_Code__c == '240') {
                    List<String> resCodeCancelTow = new List<String>{'X001', 'X002', 'R199', 'R007', 'R006', 'R003', 'R002', 'R001'};
                    
                    for (FSL_Service_Line_Item__c currSLI : sliList) {
                        Boolean isWOTypeTow = wo.Record_Type_Dev_Name__c == 'Tow';
                        Boolean isTowCancelled = isWOTypeTow && resCodeCancelTow.contains(wo.Resolution_Code__c);
        
                        if (isTowCancelled && currSLI.Product_Code__c == 'TW') {
                            currSLI.Cost__c = null;
                            currSLI.Unit__c = null;
                            currSLI.Calculated_Unit__c = null;
                            currSLI.Override_Pricing__c = true;
                        }
                    }
                }
    
                output.workOrder = wo;
                output.outputList = sliList;
                output.woIsUpdated = woIsUpdated;
                outputList.add(output);
            }
        }

        return outputList;
    }
    
    global class FlowInput {
        @InvocableVariable(label = 'Work Order') global WorkOrder workOrder;
        @InvocableVariable(label = 'SLI List') global List<FSL_Service_Line_Item__c> sliList;
    }
    
    global class FlowOutput {
        @InvocableVariable(label = 'WO Output') global WorkOrder workOrder;
        @InvocableVariable(label = 'SLI Output') global List<FSL_Service_Line_Item__c> outputList;
        @InvocableVariable(label = 'WO Clearing Code Updated') global Boolean woIsUpdated;
    }
}
// comment for deploy diff