unpackaged/main/default/objects/Default_State_PTA__mdt/Default_State_PTA__mdt.object-meta.xml
<CustomObject>
    <description>Will show member our promise time of arrival in triage when case is submitted.</description>
    <label>Default State PTA</label>
    <pluralLabel>Default State PTAs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Default_State_PTA__mdt/fields/PTA__c.field-meta.xml
<CustomField>
    <fullName>PTA__c</fullName>
    <label>PTA</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Default_State_PTA__mdt/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Battery</fullName>
            </value>
            <value>
                <fullName>Tow</fullName>
            </value>
            <value>
                <fullName>Flat Tire</fullName>
            </value>
            <value>
                <fullName>Vehicle Lockout</fullName>
            </value>
            <value>
                <fullName>Fuel</fullName>
            </value>
            <value>
                <fullName>Extrication</fullName>
            </value>
            <value>
                <fullName>Home Lockout</fullName>
            </value>
            <value>
                <fullName>Locksmith</fullName>
            </value>
            <value>
                <fullName>Extrication Tow Only</fullName>
            </value>
            <value>
                <fullName>Battery Test</fullName>
            </value>
            <value>
                <fullName>Light Service</fullName>
            </value>
            <value>
                <fullName>Full Service</fullName>
                <isActive>false</isActive>
                <label>Full Service</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Default_State_PTA__mdt/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AL</fullName>
                <default>true</default>
                <label>AL</label>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NM</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>OH</fullName>
            </value>
            <value>
                <fullName>OK</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>RI</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>VT</fullName>
            </value>
            <value>
                <fullName>WV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/DefaultStatePTATest.cls
@isTest
private class DefaultStatePTATest {
    
    @isTest
    static void getDSPTA_Test() {
        // get one record for testing purposes
        Default_State_PTA__mdt validRec = [SELECT PTA__c, State__c, Service_Type__c FROM Default_State_PTA__mdt LIMIT 1];
        String state = validRec.State__c;
        String serviceType = validRec.Service_Type__c;
        
        Test.startTest();
        
        // test 1 : valid entries
        Assert.AreEqual(DefaultStatePTA.getDefaultStatePTA(state, serviceType),validRec.PTA__c,'DefaultStatePTA valid');
        // test 2 : invalid service type
        Assert.AreEqual(DefaultStatePTA.getDefaultStatePTA(state,'Gibberish'),0,'DefaultStatePTA invalid ServiceType');
        // test 3 : invalid state
        Assert.AreEqual(DefaultStatePTA.getDefaultStatePTA('ZX',serviceType),0,'DefaultStatePTA invalid State');
        
        // For the system time tests
        Integer transitMinutes = DefaultStatePTA.getDefaultStatePTA ( state, serviceType);
        DateTime testTime = DateTime.newInstance ( DateTime.now().getTime() + (transitMinutes * 60 * 1000) );
        
        // Test return of normal DT
        Assert.AreEqual( DefaultStatePTA.getPTADateTime(state, serviceType), testTime, 'DefaultStatePTA invalid datetime');
        testTime = DateTime.newInstance ( DateTime.now().getTime() + (transitMinutes * 60 * 1000) );
        
        // Test UTC representation
        //Standard format is yyyy-MM-ddTHH:mm:ss.sssZ (e.g. '2022-03-30T21:37:58.012Z')
        String ptaAsUTC1 = JSON.serialize (testTime);
        String ptaAsUTC2 = DefaultStatePTA.getPtaAsStandardUTC ( state, serviceType );
        Assert.AreEqual( ptaAsUTC1.substring(0,19), ptaAsUTC2.substring(0,19) );
        
        String fmt = 'HH:mm';
        String hhmm = DateTime.newInstance ( DateTime.now().getTime() + (transitMinutes * 60 * 1000) ).format (fmt);
        Assert.AreEqual( hhmm, DefaultStatePTA.getPtaAsHourMin ( state, serviceType ) );
        
        Test.stopTest();
    }
}