unpackaged/main/default/objects/Driver_Logout_Event__e/Driver_Logout_Event__e.object-meta.xml
<CustomObject>
    <description>Driver Logout Platform Event</description>
    <label>Driver Logout Event</label>
    <pluralLabel>Driver Logout Events</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Driver_Logout_Event__e/fields/DriverID__c.field-meta.xml
<CustomField>
    <fullName>DriverID__c</fullName>
    <description>Driver Id</description>
    <label>DriverID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Driver_Logout_Event__e/fields/DriverName__c.field-meta.xml
<CustomField>
    <fullName>DriverName__c</fullName>
    <description>Logged in Driver Name</description>
    <label>DriverName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Driver_Logout_Event__e/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Event Description</description>
    <label>Event</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Driver_Logout_Event__e/fields/EventTime__c.field-meta.xml
<CustomField>
    <fullName>EventTime__c</fullName>
    <description>Event Time</description>
    <label>EventTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Driver_Logout_Event__e/fields/FacilityID__c.field-meta.xml
<CustomField>
    <fullName>FacilityID__c</fullName>
    <description>Facility ID</description>
    <label>FacilityID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Driver_Logout_Event__e/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <description>Salesforce Logged in  User ID</description>
    <label>UserID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Driver_Id__c.field-meta.xml
<CustomField>
    <fullName>Driver_Id__c</fullName>
    <label>Driver Id</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceResource/fields/Facility_Number__c.field-meta.xml
<CustomField>
    <fullName>Facility_Number__c</fullName>
    <formula>Primary_Service_Territory__r.Facility_Number__c</formula>
    <label>Facility Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DriverLogoutEventTriggerHandler.cls
public class DriverLogoutEventTriggerHandler {
 
    Public Static Void Run(List<LogoutEventStream> logoutList){
     // System.debug('after insert'+ logoutList[0]);
      LogoutEventStream event = logoutList[0];

     Integer isPermission = [SELECT count() FROM PermissionSetAssignment where AssigneeId = :event.UserId and 
                              PermissionSet.name ='Mobile_Technician_Permission_Set' ];
               
    IF(isPermission > 0)
    {
       Driver_Logout_Event__e record = new Driver_Logout_Event__e();
      //record.EventIdentifier__c = event.EventIdentifier;
      // record.UserId__c = event.UserId;
   
       record.EventTime__c = event.EventDate;
       record.Event__c= 'End Shift'; 
        
       List<ServiceResource> srList = [Select Facility_Number__c,name, Driver_Id__c,RelatedRecordId from ServiceResource where RelatedRecordId = :event.UserId];
       record.DriverName__c = srList[0].name;
       String facility_num = srList[0].Facility_Number__c;
       String driver_id =    srList[0].Driver_Id__c;
        
       record.DriverId__c = driver_id;
       record.FacilityID__c = facility_num ; 
        
       EventBus.publish(record);
    }

    

  }
}