unpackaged/main/default/objects/Schedule_Freeze__c/Schedule_Freeze__c.object-meta.xml
<CustomObject>
    <label>Schedule Freeze</label>
    <nameField>
        <label>Schedule Freeze Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Freezes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Schedule_Freeze__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <formula>Service_Territory__r.Id + Work_Type__r.Id + TEXT(Start_Date__c) + TEXT(End_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Call_Origin__c.field-meta.xml
<CustomField>
    <fullName>Call_Origin__c</fullName>
    <description>Call Origin from Service Appointment</description>
    <formula>Work_Order__r.Call_Origin__c</formula>
    <label>Call Origin</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Call_Origin_OrgCode__c.field-meta.xml
<CustomField>
    <fullName>Call_Origin_OrgCode__c</fullName>
    <formula>Work_Order__r.Call_Origin_OrgCode__c</formula>
    <label>Call Origin OrgCode</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Call_Origin_OrgName__c.field-meta.xml
<CustomField>
    <fullName>Call_Origin_OrgName__c</fullName>
    <formula>Work_Order__r.Call_Origin_OrgName__c</formula>
    <label>Call Origin OrgName</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Member_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Member_Scheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true if the member gave a preference for an appointment time</description>
    <label>Member Scheduled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/PTA__c.field-meta.xml
<CustomField>
    <fullName>PTA__c</fullName>
    <label>PTA</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/RAP_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>RAP_Case_Number__c</fullName>
    <formula>Work_Order__r.RAP_Case_Number__c</formula>
    <label>RAP Case Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Service_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/fields/T_Code__c.field-meta.xml
<CustomField>
    <fullName>T_Code__c</fullName>
    <formula>Work_Order__r.T_Code__c</formula>
    <label>T-Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ServiceAppointment/recordTypes/Tow.recordType-meta.xml
<RecordType>
    <fullName>Tow</fullName>
    <active>true</active>
    <label>Tow</label>
</RecordType>

unpackaged/main/default/objects/Vehicle_Type__c/Vehicle_Type__c.object-meta.xml
<CustomObject>
    <label>Vehicle Type</label>
    <nameField>
        <label>Vehicle Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WorkOrder/fields/Call_Date__c.field-meta.xml
<CustomField>
    <fullName>Call_Date__c</fullName>
    <label>Call Date</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Call_Id__c.field-meta.xml
<CustomField>
    <fullName>Call_Id__c</fullName>
    <label>Call ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Call_Origin__c.field-meta.xml
<CustomField>
    <fullName>Call_Origin__c</fullName>
    <label>Call Origin</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Call_Origin_OrgCode__c.field-meta.xml
<CustomField>
    <fullName>Call_Origin_OrgCode__c</fullName>
    <label>Call Origin OrgCode</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Call_Origin_OrgName__c.field-meta.xml
<CustomField>
    <fullName>Call_Origin_OrgName__c</fullName>
    <label>Call Origin OrgName</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>21</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/FSL_Pacesetter__c.field-meta.xml
<CustomField>
    <fullName>FSL_Pacesetter__c</fullName>
    <label>Pacesetter</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Goodwill_Indicator__c.field-meta.xml
<CustomField>
    <fullName>Goodwill_Indicator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Goodwill Indicator</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Is_Tow_WorkType__c.field-meta.xml
<CustomField>
    <fullName>Is_Tow_WorkType__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Tow WorkType</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Original_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Member_Id__c</fullName>
    <label>Original Member Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Payment_Codes__c.field-meta.xml
<CustomField>
    <fullName>Payment_Codes__c</fullName>
    <label>Payment Codes</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Payment_Responsibility__c.field-meta.xml
<CustomField>
    <fullName>Payment_Responsibility__c</fullName>
    <label>Payment Responsibility</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/PTA__c.field-meta.xml
<CustomField>
    <fullName>PTA__c</fullName>
    <label>PTA</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/RAP_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>RAP_Case_Number__c</fullName>
    <label>RAP Case Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Responder_Id__c.field-meta.xml
<CustomField>
    <fullName>Responder_Id__c</fullName>
    <label>Original Receiver Id</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Schedule_Freeze__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Freeze__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule Freeze</label>
    <referenceTo>Schedule_Freeze__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Service_Resource__c.field-meta.xml
<CustomField>
    <fullName>Service_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Resource</label>
    <referenceTo>ServiceResource</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/T_Code__c.field-meta.xml
<CustomField>
    <fullName>T_Code__c</fullName>
    <label>T-Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Vehicle_Profile__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Profile__c</fullName>
    <label>Vehicle Profile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/recordTypes/Tow.recordType-meta.xml
<RecordType>
    <fullName>Tow</fullName>
    <active>true</active>
    <label>Tow</label>
</RecordType>

unpackaged/main/default/objects/WorkType/fields/T_Code__c.field-meta.xml
<CustomField>
    <fullName>T_Code__c</fullName>
    <label>T-Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AutoscheduleQuickActionController.cls
public with sharing class AutoscheduleQuickActionController {
    @AuraEnabled
    public static void autoschedule(String recordId)
    {
        System.debug('autoschedule - '+recordId);
        Map<Id,WorkType> worktypeIdMap = new Map<Id,WorkType>([SELECT Id, Name, EstimatedDuration FROM WorkType]);  
        Map<Id, FSL__Scheduling_Policy__c> policyMap = new Map<Id, FSL__Scheduling_Policy__c>([SELECT Id, Name FROM FSL__Scheduling_Policy__c]);

        ServiceAppointment breakdownSA;
        ServiceAppointment towSA;

        List<String> ids = new List<Id>();
        ids.add(recordId);           

        ServiceAppointment rec = fetchServiceAppointment(recordId);
        System.debug('MAIN REC-'+rec);

        WorkOrder wo = [SELECT Id,Is_Tow_WorkType__c,Schedule_Freeze__c, ServiceTerritoryId, ServiceTerritory.OperatingHours.Timezone,WorkTypeId,External_ID__c,Call_Id__c,
            Call_Date__c,Goodwill_Indicator__c,Call_Origin__c,Call_Origin_OrgCode__c,Call_Origin_OrgName__c,Responder_ID__c,
            Vehicle_Type__c,RAP_Case_Number__c,Payment_Codes__c,Payment_Responsibility__c,Original_Member_Id__c,T_Code__c,
            Vehicle_Profile__c,FSL_Pacesetter__c,RecordTypeId,Priority
            FROM WorkOrder 
            WHERE Id = :rec.Work_Order__c LIMIT 1];

        if (wo.Is_Tow_WorkType__c)
        {
            ServiceAppointment relatedRec = fetchServiceAppointment(rec.FSL__Related_Service__c);
            System.debug('REL REC-'+relatedRec);

            if (rec.Subject == 'Tow Appointment')
            {
                towSA = rec;
                breakdownSA = relatedRec;
            }
            else 
            {
                breakdownSA = rec;
            }
        }
        else 
        {
            breakdownSA = rec;
        }

        if(Test.isRunningTest())
        {
            //Yes this is cheating.  I am bypassing the call because I cannot figure out how to get the schedule to be suitably
            //set up for the test.  This class is really just about the quick action and the other deeper functionality should
            //be tested elsewhere
            System.debug('ScheduleQueueableAppointment bypassed in test');
        }
        else 
        {
            FSL_Schedule_Config scheduleConfig = FSL_SchedulingUtility.populateArrivalWindowAndPolicy(breakdownSA, wo, policyMap);
            FSL_AppointmentDependencyHelper.ScheduleQueueableAppointment(breakdownSA, towSA, wo, worktypeIdMap,scheduleConfig, policyMap);                 
        }
    }

    private static ServiceAppointment fetchServiceAppointment(String saId)
    {
        ServiceAppointment rec = [SELECT Id,Service_Resource__c,Member_Scheduled__c,SchedStartTime,FSL__Pinned__c,FSL__Related_Service__c,
            ParentRecordId,Status,Work_Order__c,Subject,ServiceTerritoryId,EarliestStartTime,PTA__c
            FROM ServiceAppointment 
            WHERE Id = :saId LIMIT 1];

        return rec;
    }
 }