unpackaged/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Audit Log</label>
    <nameField>
        <displayFormat>AL-{0000000000}</displayFormat>
        <label>Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Audit_Log__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Audit Logs</relationshipLabel>
    <relationshipName>Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Clear_Code_Mapping__mdt/Clear_Code_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Clear Code Mapping</label>
    <pluralLabel>Clear Code Mappings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Clear_Code_Mapping__mdt/fields/Base_Pay_Percent__c.field-meta.xml
<CustomField>
    <fullName>Base_Pay_Percent__c</fullName>
    <label>Base Pay Percent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/FSL_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SLI - {0000}</displayFormat>
        <label>SLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Calculated_Unit__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Unit__c</fullName>
    <label>Calculated Quantity (TW/OM)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Charge_to_Account__c.field-meta.xml
<CustomField>
    <fullName>Charge_to_Account__c</fullName>
    <label>Charge to Account</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Cleared_Timestamp_TOD_Code__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Timestamp_TOD_Code__c</fullName>
    <formula>Work_Order__r.Cleared_Timestamp_TOD_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cleared Timestamp TOD Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Override_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Override_Pricing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Override Pricing</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3)</booleanFilter>
        <filterItems>
            <field>Product2.ProductCode</field>
            <operation>notEqual</operation>
            <value>CE</value>
        </filterItems>
        <filterItems>
            <field>Product2.ProductCode</field>
            <operation>notEqual</operation>
            <value>CT</value>
        </filterItems>
        <filterItems>
            <field>Product2.Name</field>
            <operation>notEqual</operation>
            <value>CT - Calculated Tow</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Line Items (Product)</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Ready_for_Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_Invoicing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for Invoicing</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Requested_Cost__c.field-meta.xml
<CustomField>
    <fullName>Requested_Cost__c</fullName>
    <label>Requested Cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Requested_Unit__c.field-meta.xml
<CustomField>
    <fullName>Requested_Unit__c</fullName>
    <label>Requested Unit</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Cost__c +  Tax__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Quantity</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FSL_Service_Line_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ServiceTerritory/fields/Is_Fleet__c.field-meta.xml
<CustomField>
    <fullName>Is_Fleet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an indicator that the service territory is a club fleet location</description>
    <inlineHelpText>Only check this box if the service territory is a club fleet location</inlineHelpText>
    <label>Is Fleet</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/BO_Editable_WO_Specific_Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>BO_Editable_WO_Specific_Membership_Level__c</fullName>
    <label>BO Editable WO Specific Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plus</fullName>
            </value>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Premier RV</fullName>
            </value>
            <value>
                <fullName>Plus RV</fullName>
            </value>
            <value>
                <fullName>Classic RV</fullName>
            </value>
            <value>
                <fullName>Basic</fullName>
                <default>true</default>
                <label>Basic</label>
            </value>
            <value>
                <fullName>Everyday</fullName>
            </value>
            <value>
                <fullName>CLASSICRV</fullName>
                <isActive>false</isActive>
                <label>CLASSICRV</label>
            </value>
            <value>
                <fullName>PLUSRV</fullName>
                <isActive>false</isActive>
                <label>PLUSRV</label>
            </value>
            <value>
                <fullName>PREMIERRV</fullName>
                <isActive>false</isActive>
                <label>PREMIERRV</label>
            </value>
            <value>
                <fullName>Premier Motorcycle</fullName>
                <isActive>false</isActive>
                <label>Premier Motorcycle</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <isActive>false</isActive>
                <label>Y</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Cleared_Timestamp_TOD_Code__c.field-meta.xml
<CustomField>
    <fullName>Cleared_Timestamp_TOD_Code__c</fullName>
    <formula>IF(  Created_Time__c  &lt;=   TIMEVALUE(&quot;18:59:00.000&quot;) &amp;&amp; Created_Time__c  &gt;=  TIMEVALUE (&quot;06:00:00.00&quot;), &quot;D 06:00-18:59&quot;,
     IF ( Created_Time__c  &lt;=   TIMEVALUE(&quot;23:59:00.000&quot;) &amp;&amp; Created_Time__c  &gt;=  TIMEVALUE (&quot;19:00:00.00&quot;) , &quot;N1 19:00-23:59&quot;,
        IF( Created_Time__c  &lt;=   TIMEVALUE(&quot;05:59:00.000&quot;) &amp;&amp; Created_Time__c  &gt;=  TIMEVALUE (&quot;00:00:00.00&quot;) , &quot;N2 00:00 – 05:59&quot;,
             &quot;&quot;
         )
     )
)</formula>
    <label>Cleared Timestamp TOD Code</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Clearing_Code__c.field-meta.xml
<CustomField>
    <fullName>Clearing_Code__c</fullName>
    <label>Clearing Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Clear_Codes</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Facility_Contract__c.field-meta.xml
<CustomField>
    <fullName>Facility_Contract__c</fullName>
    <formula>ServiceTerritory.Contract__r.Id</formula>
    <label>Facility Contract</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WorkOrder/fields/Resolution_Code__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Code__c</fullName>
    <label>Resolution Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CAR_ConsolidatedResoCodes</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Clear_Codes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>8X</fullName>
    </customValue>
    <customValue>
        <fullName>BK</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>CC</fullName>
    </customValue>
    <customValue>
        <fullName>M8</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <customValue>
        <fullName>MX</fullName>
    </customValue>
    <customValue>
        <fullName>N1</fullName>
    </customValue>
    <customValue>
        <fullName>N2</fullName>
    </customValue>
    <customValue>
        <fullName>N3</fullName>
    </customValue>
    <customValue>
        <fullName>N4</fullName>
    </customValue>
    <customValue>
        <fullName>N5</fullName>
    </customValue>
    <customValue>
        <fullName>N9</fullName>
    </customValue>
    <customValue>
        <fullName>NX</fullName>
    </customValue>
    <customValue>
        <fullName>RR</fullName>
    </customValue>
    <customValue>
        <fullName>XX</fullName>
    </customValue>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>2A</fullName>
        <isActive>false</isActive>
        <label>2A</label>
    </customValue>
    <customValue>
        <fullName>XE</fullName>
        <isActive>false</isActive>
        <label>XE</label>
    </customValue>
    <customValue>
        <fullName>SF</fullName>
        <isActive>false</isActive>
        <label>SF</label>
    </customValue>
    <customValue>
        <fullName>SD</fullName>
        <isActive>false</isActive>
        <label>SD</label>
    </customValue>
    <customValue>
        <fullName>PR</fullName>
        <isActive>false</isActive>
        <label>PR</label>
    </customValue>
    <customValue>
        <fullName>NG</fullName>
        <isActive>false</isActive>
        <label>NG</label>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
        <isActive>false</isActive>
        <label>NE</label>
    </customValue>
    <customValue>
        <fullName>M9</fullName>
        <isActive>false</isActive>
        <label>M9</label>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
        <isActive>false</isActive>
        <label>CA</label>
    </customValue>
    <customValue>
        <fullName>BN</fullName>
        <isActive>false</isActive>
        <label>BN</label>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
        <isActive>false</isActive>
        <label>BM</label>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
        <isActive>false</isActive>
        <label>AD</label>
    </customValue>
    <customValue>
        <fullName>2T</fullName>
        <isActive>false</isActive>
        <label>2T</label>
    </customValue>
    <masterLabel>Clear Codes</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/AAACalcSvcItemCostTest.cls
@isTest
public class AAACalcSvcItemCostTest {
    @isTest
    static void calcSvcItemCostTest() {
        WorkOrder wo = AAAFlowInvocableTest.setupTowSLIs('G101', '000');
        List<FSL_Service_Line_Item__c> sliList = [
            SELECT
                Id,
                Product__c,
                Product_Code__c,
                Work_Order__c,
                Cost__c,
                Unit__c,
                Calculated_Unit__c,
                Tax__c,
                Override_Pricing__c,
                Total_Price__c,
                Cleared_Timestamp_TOD_Code__c,
                Requested_Unit__c,
                Requested_Cost__c,
                Charge_to_Account__c,
                Ready_for_Invoicing__c
            FROM FSL_Service_Line_Item__c
            WHERE Work_Order__c = :wo.Id
        ];
        AAACalcSvcItemCost.FlowInput flowInput = new AAACalcSvcItemCost.FlowInput();

        wo = [
            SELECT
                Id,
                Clearing_Code__c,
                BO_Editable_WO_Specific_Membership_Level__c,
                Facility_Contract__c,
                Cleared_Timestamp_TOD_Code__c,
                CaseId,
                Resolution_Code__c,
                ServiceTerritory.State,
            	ServiceTerritory.Is_Fleet__c //AGB added for SSFI-651
            FROM WorkOrder
            WHERE Id = :wo.Id
            LIMIT 1
        ];
        flowInput.sliList = sliList;
        flowInput.wo = wo;

        List<AAACalcSvcItemCost.FlowOutput> flowOutput = AAACalcSvcItemCost.runCalcSvcItemCost(
            new List<AAACalcSvcItemCost.FlowInput>{flowInput}
        );
        List<FSL_Service_Line_Item__c> resSLIList = flowOutput[0].outputList;
        List<Audit_Log__c> resAuditList = flowOutput[0].auditList;
        FSL_Service_Line_Item__c resSLI = resSLIList[0];

        System.assertEquals(resSLI.Ready_for_Invoicing__c, true, 'Failed to price SLI.');
        System.assertEquals(resSLI.Cost__c, 15.0, 'Failed to price SLI.');
        System.assertEquals(resAuditList != null, true, 'Failed to generate Audit Log.');
    }

    public static Clear_Code_Mapping__mdt mockCCMapping() {
        return new Clear_Code_Mapping__mdt(
            Base_Pay_Percent__c = 100
        );
    }
}